### ISSUE TITLE
ERROR: Unable to extract uploader name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### ISSUE THREAD

**Issue by devalthakkar** [mps-youtube/mps-youtube#1008]

**Comment by ablizno** [comment]
pip3 install --user youtube-dl --upgrade

**Comment by SmartMetal** [comment]
I am having this same issue,  unresolved by updating both mps-youtube and youtube-dl. I am on a 64-bit Windows environment running Windows 10. I'm using the released EXE version. Just wanted to share with the devs.
