### ISSUE TITLE
Filename issues?

### ISSUE THREAD

**Issue by AdamKnube** [mps-youtube/mps-youtube#1009]
When trying to `dvpl` this playlist: list=PLjZRIC6PMEFkWSAyAcwsiqCIbKXe9lMoF
I am given this error:
Problem playing last item: [Errno 2] No such file or directory: '/home/knube/Downloads/mps/Acquisitions Incorporated: The C Team/Franchise Opportunities - S1 E1 - Acquisitions Inc: The C Team.mp4'[1/5>

## Issue / Suggestion

I think it may be due to the excessive use of spaces, '-' and, ':' characters not wanting
to be included in file names but I have not looked into it too far yet.
I can tell you it does in fact create the directory named: 
/home/knube/Downloads/mps/Acquisitions Incorporated: The C Team/,
but seems to fail after that. 

If the problem is due to the characters in the filename/folder then I would suggest
something like this (pardon the psudocode): 
name = name.replace('"', '').replace(':', '')

## Your Environment

Arch Linux Stable - Current
KDE Plasma - Current

mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.09.01
Python version     : 3.7.4 (default, Jul 16 2019, 07:12:58)
[GCC 9.1.0]
Processor          :
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.2.11-arch1-1-ARCH-x86_64-with-arch
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/knube/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8

Arch Linux Stable - Current

mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Aug  6 14:50:47 CEST 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.1

Cheers.

**Comment by Nojus297** [comment]
#1023 should fix it.
