### ISSUE TITLE
Problem playing last item: HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by vialvirt** [mps-youtube/mps-youtube#1011]
##  Problem playing last item: HTTP Error 500: Internal Server Error 
When notifier is set false I get this error when trying to play results from search with 1 +  enter. When notifier is set true I get this error instead:  "Problem playing last item: [WinError 2] The system cannot find the file specified". This error does not appear every time, but roughly on every other video. I'm using the executable version of mpsyt for windows. I can still download from youtube, and I can acces video comments and info with no trouble. The strange thing is, these erros appear on videos that I have been able to view just fine before.

## Your Environment
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.08.13
Python version     : 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
Processor          : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
Machine type       : AMD64
Architecture       : 64bit, WindowsPE
Platform           : Windows-10-10.0.18362-SP0
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : C:\Users\username\AppData\Roaming\mps-youtube

**Comment by Nojus297** [comment]
In terminal
`mpsyt help config`
```
<...>
      set notifier <notifier app> - call <notifier app> with each new song title
<...>
```
It's supposed to run a command each time a song is played with that song title. `True` or `False` is not a valid option.
You should probably run
`set notifier` (with no value)
to set it to none.
https://github.com/mps-youtube/mps-youtube/blob/3b479cbba1a0928f707ea4b72314afe0a2156476/mps_youtube/player.py#L128-L129
