### ISSUE TITLE
Error: retrying infinite loop

### ISSUE THREAD

**Issue by sebastienwood** [mps-youtube/mps-youtube#1017]
## Issue / Suggestion
I updated with `brew update && brew upgrade` this morning. Since then, when trying to play a song in mpsyt CLI, a loop with text "error retrying" can be seen where the progression bar should be/no song is playing. When trying  few song, the same error happen.

## Your Environment
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.07.30
Python version     : 3.7.4 (default, Sep  7 2019, 18:27:02) 
[Clang 10.0.1 (clang-1001.0.46.4)]
Processor          : i386
Machine type       : x86_64
Architecture       : 64bit, 
Platform           : Darwin-18.7.0-x86_64-i386-64bit
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : ~/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : fr_CA.UTF-8

**Comment by sebastienwood** [comment]
After further tests, it seems I can still access the download feature. So mpsyt manages to connect to youtube (search, download) and only the play feature seems impacted.

**Comment by jpadkins** [comment]
Try running `brew cask install mpv` again if you're using the `mpv` player.

I've been hitting the same issue after doing a brew upgrade and I noticed brew cask no longer listed mpv as being installed, even though I could run still mpv via the command line. Once I ran the install command again the issue went away. Perhaps something changed with how homebrew links apps?

**Comment by sebastienwood** [comment]
> Try running `brew cask install mpv` again if you're using the `mpv` player.
> 
> I've been hitting the same issue after doing a brew upgrade and I noticed brew cask no longer listed mpv as being installed, even though I could run still mpv via the command line. Once I ran the install command again the issue went away. Perhaps something changed with how homebrew links apps?

Solves the issue thanks ! :)
