### ISSUE TITLE
Running mpsyt --help causes the terminal text color to stay yellow

### ISSUE THREAD

**Issue by Chronomly** [mps-youtube/mps-youtube#1026]
## Issue / Suggestion
I attempted to run `mpsyt --help` and it doesn't reset the terminal font color after changing it to yellow

## Your Environment
0.2.8
Fedora 30
mpv

## Screenshot
https://when-will.disilla.org/be/done/m5PUT2tgXRmn.png

**Comment by Nojus297** [comment]
What terminal emulator?

**Comment by Chronomly** [comment]
GNOME Terminal with Bash

**Comment by Nojus297** [comment]
Well, I'm not sure. I can't reproduce it.

**Comment by Chronomly** [comment]
https://when-will.disilla.org/be/done/m5PUT2tgXRmn.png

**Comment by Nojus297** [comment]
ccab53b5f0a2779a7d7935bbb81402a3094334a0
#931
Looks like it has been fixed. Try with current develop version.

**Comment by hrnr** [comment]
This should be fixed.
