### ISSUE TITLE
mpv release 0.32.0

### ISSUE THREAD

**Issue by Deracinator** [mps-youtube/mps-youtube#1052]
## Issue

Mpv's latest release deprecates and disallows the previous double dashed parameters syntax, for example: `--force-media-title <string>` parameter now needs to be written `--force-media-title=<string>` this makes mpsyt to break completely if mpv is in the latest version, single dash parameters in the previous syntax are still functional but deprecated and it's use is discouraged, mpv will emit a warning every time it founds this kind of syntax(eg. `-force-media-title <string>`.
More information about this latest release can be found at: https://github.com/mpv-player/mpv/releases/tag/v0.32.0

## Environment
```
mpsyt --version
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2020.01.24
Python version     : 3.8.1 (default, Jan 22 2020, 06:38:00) 
[GCC 9.2.0]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.4.14-arch1-1-x86_64-with-glibc2.2.5
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/deracinator/.config/mps-youtube
env:TERM           : xterm-termite
env:SHELL          : /bin/zsh
env:LANG           : en_US.UTF-8

$ mpv --version
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.2
```

Running on ArchLinux 5.4.14-arch1-1

**Comment by FarisHijazi** [comment]
uninstall `pip uninstall mps-youtube` then install the latest development release

This worked for me:

```
pip install git+https://github.com/mps-youtube/mps-youtube.git
```

**Comment by bester69** [comment]
> uninstall `pip uninstall mps-youtube` then install the latest development release
> 
> This worked for me:
> 
> ```
> pip install git+https://github.com/mps-youtube/mps-youtube.git
> ```

mpv 0.32, mpsyt 0.2.8
Thanks a lot, this worked for me as well.
