### ISSUE TITLE
Dead link about youtube api key in wiki

### ISSUE THREAD

**Issue by DBX12** [mps-youtube/mps-youtube#1059]
## Issue / Suggestion
The link about getting an API key for youtube is dead (on [this wiki page](https://github.com/mps-youtube/mps-youtube/wiki/Troubleshooting))
I suggest replacing it with this one, if it describes the same procedure:
https://www.slickremix.com/docs/get-api-key-for-youtube/

**Comment by Di9** [comment]
Done - https://github.com/mps-youtube/mps-youtube/wiki/Troubleshooting
Also added command how to clean cache.

**Comment by tommysolsen** [comment]
Thank you for updating the wiki!

**Comment by DBX12** [comment]
Today I learned, you can edit wiki pages directly without a PR :)
