### ISSUE TITLE
HTTP not supported [Win10]

### ISSUE THREAD

**Issue by Frostcard** [mps-youtube/mps-youtube#1075]
Can't seem to get around the above mentioned issue on a Windows machine (x64)
The player and other dependencies seem to be correctly installed

Problem playing last item: Lane 8 - Groundhog Day, a mixtape ERROR: M_cnYbSUkCI: Youtube says: HTTP is not supported.
[1/20>> **ERROR: vzXtr0E_LWA: YouTube said: HTTP is not supported.**

mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2020.03.24
Python version     : 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]
Processor          : Intel64 Family 6 Model 92 Stepping 9, GenuineIntel
Machine type       : AMD64
Architecture       : 32bit, WindowsPE
Platform           : Windows-10-10.0.18362-SP0
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : C:\Users\Frostcard\AppData\Roaming\mps-youtube

**Comment by HackedByATree** [comment]
@Frostcard How did you fix this issue?

**Comment by Frostcard** [comment]
> 
> 
> @Frostcard How did you fix this issue?

Wow, it's been a while :)
As my memory completely fails me, I can only suggest potential routes I might have taken:

- Set a different API key
- Make sure to install it correctly within the same directory
- Try using _mplayer_ if you previously tried with _mpv_ or _vlc_
- Clean the AppData files (regarding mps-youtube)
