### ISSUE TITLE
"Problem playing last item: HTTP Error 403: Forbidden"

### ISSUE THREAD

**Issue by ghost** [mps-youtube/mps-youtube#1082]
mps-youtube was working fine for 1-2 days after changing the API key, but since yesterday I am getting this error. I have tried changing the API key again too, but it didn't fix this. However, this is not the case with all the videos. Some videos randomly start playing while others always give this error.
`Problem playing last item: HTTP Error 403: Forbidden`

Specs : 

`[arco@arco-linux ~]$ mpsyt --version
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2020.03.24
Python version     : 3.8.2 (default, Apr  8 2020, 14:31:25) 
[GCC 9.3.0]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.6.8-arch1-1-x86_64-with-glibc2.2.5
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/arco/.config/mps-youtube
env:TERM           : xterm-termite
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8
`

**Comment by anirudhRowjee** [comment]
I am facing the same issue too.

**Comment by benchile55** [comment]
This is completely true.. this old 403 error is back, but the old way to solve it did not work out for me and decided to remove mps-youtube by now

**Comment by anirudhRowjee** [comment]
[This](https://github.com/mps-youtube/mps-youtube/issues/1071#issuecomment-614456026) is what I tried , and it's working well so far (from #1063)

**Comment by benchile55** [comment]
> [This](https://github.com/mps-youtube/mps-youtube/issues/1071#issuecomment-614456026) is what I tried , and it's working well so far (from #1063)

 Nope .. this is not working.. I was doing that  every day  I used mps-youtube until last Tuesday.. and  after that..deleting xxcache.py file from .config/mpsyoutube/   stopped doing that trick in my system

**Comment by paulo-sampaio** [comment]
creating an api-key on google, with acces to youtube data v3 enabled, and setting it up on ~/.config/mpsyoutube/config.json solved this issue to me.

**Comment by benchile55** [comment]
I could solve  this issue upgrading mpsyt  2.8 into mpsyt-git version from AUR arch Linux.. keeping regular updated official mpv and youtube-dl packages in Manjaro Linux 19

**Comment by iamtalhaasghar** [comment]
see #1191
