### ISSUE TITLE
unable to play

### ISSUE THREAD

**Issue by Creator54** [mps-youtube/mps-youtube#1112]
After using
/music
typed the video number
getting this issue, am i using it wrong ?

note: i did changed the api key cuz with the default one was giving error 403
## Issue / Suggestion
![share](https://user-images.githubusercontent.com/34543609/90327714-47cdd300-dfb4-11ea-9589-a61618837091.png)

## Your Environment
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2020.06.16.1
Python version     : 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.6.19-2-MANJARO-x86_64-with-glibc2.2.5
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/creator54/.config/mps-youtube
env:TERM           : xterm-kitty
env:SHELL          : /bin/fish
env:LANG           : en_IN.UTF-8

**Comment by Gitkubikon** [comment]
I have the exact same issue, maybe its a recent bug

**Comment by Creator54** [comment]
> I have the exact same issue, maybe its a recent bug.
> However, i figured that using the git version works.
> 
> `yay -S mps-youtube-git`
> 
> In the git version you can disable/enable mpris, that is causing the error.

thnx it worked
