### ISSUE TITLE
ERROR: YouTube said: Unable to extract video data

### ISSUE THREAD

**Issue by vietnguyen07** [mps-youtube/mps-youtube#1136]
## Issue / Suggestion

Hi all,
I have an issue with mpsyt:
1. I created my own API key and already set it in mpsyt
2. When I try to search or play result, I have this error message and cannot continue:
   Search results for babyshark                            [1/25>
> ERROR: j8z7UjET1Is: YouTube said: Unable to extract video data
According to my search, it may has some relations to youtube-dl?
What can I do to overcome this?
## Your Environment

1. Im running ubuntu 20.04 on Rasp 4-8G
2. mpsyt version:
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.2 (youtube-dl backend)
youtube-dl version : 2020.09.14
Python version     : 3.8.6 (default, Sep 25 2020, 09:36:53) 
[GCC 10.2.0]
Processor          : aarch64
Machine type       : aarch64
Architecture       : 64bit, ELF
Platform           : Linux-5.8.0-1010-raspi-aarch64-with-glibc2.32
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/viet/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8

**Comment by jegornagel** [comment]
Same here. I can't move anywhere after this error.

**Comment by darkhz** [comment]
You'll have to delete the cache file first, its usually located in 
`/home/<user>/.config/mps-youtube/cache_py_x.x.x`

I've faced this problem multiple times before, deleting the cache always works.

**Comment by amacgregor** [comment]
I'm facing this as well delete the cache did nothing

**Comment by kieracarman** [comment]
I'm also having this issue, api_key set, deleted cache and still not working.

**Comment by samkellerhals** [comment]
I am also having the same issue, set new api key and deleted cache also not able to extract video data.

**Comment by samkellerhals** [comment]
**A temporary workaround:**

- Search for songs you want to listen to using `mpsyt` by doing `/song name`
- Clip youtube video URL to clipboard using `x <song_number>` (you need to have installed `pyperclip`)
- In another terminal window play the music using `mpv <youtube_url> --no-video`

**Comment by windowswithoutborders** [comment]
+1 right here on this issue on macOS 11.1. Followed the instructions for deleting pycache and setting the new api and getting unable to extract video data. I just heard about this program too and it would be my preferred way of listening to music off youtube if only it would work :(.

**Comment by Ja-sonYun** [comment]
I fixed this problem with remove mpv installed using brew and install with pip.

**Comment by cloudytheconqueror** [comment]
I fixed the issue by uninstalling and reinstalling a newer version of `youtube-dl`.

I think simply upgrading it will work: `pip install youtube-dl --upgrade`

**Comment by jav-12** [comment]
Same error here. @cloudytheconqueror do we need to install youtube-dl as well to work with mpsyt ?

**Comment by sfolje0** [comment]
Maybe related to https://github.com/ytdl-org/youtube-dl/issues/26152?

**Comment by Solarapollo05** [comment]
I think i found a possible fix. I updated youtube-dl `pip3 install youtube-dl --upgrade` This seemed to fix it after reloading mps.

**Comment by sfolje0** [comment]
> 
> 
> I think i found a possible fix. I updated youtube-dl `pip3 install youtube-dl --upgrade` This seemed to fix it after reloading mps.

Yes, so I suspect. While the fix already mentioned in previous comments.

**Comment by kilianso** [comment]
I'm still having this issue on MacOS 10.15.7

I tried to uninstall mps-youtube using brew and reinstalled it using `pip3 install mps-youtube`.
After that the terminal shows: `mpsyt: command not found` - so i tried to set the PATH variable and still no luck.

So i reinstalled it using brew again and whenever i search something i see the error:
`Youtube said: Unable to extract video data`.

I tried it with mpv and Mplayer, no difference and i set my own YT API Key.

Any idea?

**Comment by ir1979** [comment]
Install youtube-dl using `pip3 install youtube-dl` and add it to your `PATH`. Check where is the package you are running.

**Comment by mastersaints888** [comment]
### Solved 

- uninstall youtube-dl
- run command 
`sudo snap install youtube-dl  # version 2021.06.06+git7fb9564` 
- enjoy

**Comment by mk8486** [comment]
try to remove and then upgrade with this command

`sudo -H pip install --upgrade youtube-dl`

**Comment by mk8486** [comment]
> try to remove and then upgrade with this command
> 
> `sudo -H pip install --upgrade youtube-dl`

if not work install python3

**Comment by shafi-sfdc** [comment]
Above suggestion from @mk8486  worked for me

**Comment by taichuai** [comment]
you can use yt-dlp replace youtube-dl, ex:
`yt-dlp -f ‘bv[ext=mp4]+ba[ext=m4a]’ –embed-metadata –merge-output-format mp4 [https://youtu.be/sKrT6mBrosc](https://link.zhihu.com/?target=https%3A//youtu.be/sKrT6mBrosc)`
