### ISSUE TITLE
Music stopping before the end

### ISSUE THREAD

**Issue by astahjmo** [mps-youtube/mps-youtube#1140]
## Issue / Suggestion
All songs are stopping when they reach 80% - 95%
There is no error or anything, he simply ends the song

## Your Environment
○$ mpsyt --version
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2021.01.03
Python version     : 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.10.5-arch1-1-x86_64-with-glibc2.32
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/astah/.config/mps-youtube
env:TERM           : xterm-kitty
env:SHELL          : /usr/bin/zsh
env:LANG           : pt_BR.UTF-8

## MPlayer Info

mplayer -v   
MPlayer SVN-r38157 (C) 2000-2019 MPlayer Team
CPU vendor name: AuthenticAMD  max cpuid level: 6
CPU: AMD C-50 Processor (Family: 20, Model: 1, Stepping: 0)
extended cpuid-level: 27
extended cache-info: 33587520
Detected cache-line size is 64 bytes
CPUflags:  MMX: 1 MMX2: 1 3DNow: 0 3DNowExt: 0 SSE: 1 SSE2: 1 SSE3: 1 SSSE3: 1 SSE4: 0 SSE4.2: 0 AVX: 0
Compiled with runtime CPU detection.
get_path('codecs.conf') -> '/home/astah/.mplayer/codecs.conf'
Reading optional codecs config file /home/astah/.mplayer/codecs.conf: No such file or directory
Reading optional codecs config file /etc/mplayer/codecs.conf: 225 audio & 468 video codecs
init_freetype
Using SSE2 Optimized OnScreenDisplay
get_path('fonts') -> '/home/astah/.mplayer/fonts'

**Comment by darkhz** [comment]
Playing with mplayer is currently buggy, this bug is already well known.Use mpv as an alternative, and set playerargs to --no-video

**Comment by astahjmo** [comment]
I getting this error with mpv:

Error parsing commandline option title: option requires parameter
Make sure you're using e.g. '--title=value' instead of '--title value'.
Exiting... (Fatal error)

## Mpv version
[cplayer] Command line options: '--v'
[cplayer] mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.51.100
[cplayer]    libavcodec      58.91.100
[cplayer]    libavformat     58.45.100
[cplayer]    libswscale      5.7.100
[cplayer]    libavfilter     7.85.100
[cplayer]    libswresample   3.7.100
[cplayer] FFmpeg version: n4.3.1
[cplayer] 
[cplayer] Configuration: /usr/bin/waf configure --prefix=/usr --confdir=/etc/mpv --enable-cdda --enable-dvb --enable-dvdnav --enable-libarchive --enable-libmpv-shared --disable-build-date
[cplayer] List of enabled features: 52arch alsa asm caca cdda cplayer cplugins cuda-hwaccel cuda-interop debug-build drm dvbin dvdnav egl egl-drm egl-helpers egl-x11 ffmpeg ffnvcodec gbm gbm.h gl gl-wayland glibc-thread-name glob glob-posix gpl iconv jack javascript jpeg lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared libplacebo librt linux-fstatfs linux-input-event-codes lua memfd_create optimize plain-gl posix posix-or-mingw pthreads pulse rubberband shaderc shaderc-shared stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-vulkan vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vt.h vulkan wayland wayland-protocols x11 xv zlib
[cplayer] Reading config file /etc/mpv/encoding-profiles.conf
[cplayer] Applying profile 'default'...
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.51.100
[cplayer]    libavcodec      58.91.100
[cplayer]    libavformat     58.45.100
[cplayer]    libswscale      5.7.100
[cplayer]    libavfilter     7.85.100
[cplayer]    libswresample   3.7.100
[cplayer] FFmpeg version: n4.3.1
[cplayer] 
[cplayer] Usage:   mpv [options] [url|path/]filename
[cplayer] 
[cplayer] Basic options:
[cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[cplayer]  --no-audio        do not play sound
[cplayer]  --no-video        do not play video
[cplayer]  --fs              fullscreen playback
[cplayer]  --sub-file=<file> specify subtitle file to use
[cplayer]  --playlist=<file> specify playlist file
[cplayer] 
[cplayer]  --list-options    list all mpv options
[cplayer]  --h=<string>      print options which contain the given string in their name
[cplayer] 
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Set property: shared-script-properties -> 1

**Comment by Ja-sonYun** [comment]
try to install mps-youtube with ```pip3 install --user -U git+https://github.com/mps-youtube/mps-youtube.git```.
I had same issue but fixed with above command.

**Comment by astahjmo** [comment]
Fixed for me too, thanks
