### ISSUE TITLE
Errors viewing comments and attempts to play any video

### ISSUE THREAD

**Issue by brawnswubb** [mps-youtube/mps-youtube#1142]
## Issue / Suggestion
 
I've tried running it from the command line and the results are identical to the bugs I encountered inside the app. Some assistance would be greatly appreciated 
![pic-selected-210118-1146-03](https://user-images.githubusercontent.com/74217576/104957509-330fc400-59c6-11eb-94de-943e5b7dafb8.png) 

using mpv version 0.33.0 

When trying to view the comments on any video(c option) I get an time error as well. 
![pic-selected-210118-1204-32](https://user-images.githubusercontent.com/74217576/104958773-87b43e80-59c8-11eb-887d-aa3bbbf17710.png)

May or may not be relevant, butI have fedora on another drive and whenever I boot into it and back into my current OS, RTC is usually off. I use date --set and hwclock --systohw to correct the issue. This does not fix the issue I'm experiencing with the app.

**Comment by Masacaai** [comment]
Use the experimental development branch. I had the same problem and switching to the it fixed it for me.

**Comment by brawnswubb** [comment]
That actually worked! Thank you
