### ISSUE TITLE
RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used

### ISSUE THREAD

**Issue by rbreaves** [mps-youtube/mps-youtube#1154]
When playing a track it plays, but this error appears

## Issue / Suggestion
Appears to be related to the buffer size being set to 1 on a POpen somewhere, not sure of the impact of removing it or setting it to 0 but that appears to be the suggested solution.

https://github.com/pkgcore/pkgcheck/commit/714c016381b53246b449dd9c3116811e50db744f
https://github.com/pkgcore/pkgcheck/issues/187

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=953056

## Your Environment
```
mpsyt --version
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2021.03.03
Python version     : 3.8.5 (default, Jan 27 2021, 15:41:15)
[GCC 9.3.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : ~/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /usr/bin/zsh
env:LANG           : C.UTF-8
```
Running this in WSL1 Ubuntu 20.04.

**Comment by rbreaves** [comment]
Also MPRIS complains about not being able to initialize x11 - but I am not running a DE so.. yea no real display to speak of. I could set that up but I don't need a GUI/DE running.

**Comment by otisdog8** [comment]
Pretty sure that's a warning, I edited the file /usr/bin/mpsyt to turn off warnings (arch):
```python
import warnings
warnings.filterwarnings("ignore")
```
