### ISSUE TITLE
vlc play with no gui

### ISSUE THREAD

**Issue by OctopuSS7** [mps-youtube/mps-youtube#1157]
How would I change the way vlc is invoked here? I would use vlc -Idummy to do this normally. Is there a way to specify the command used to open the player?

## Your Environment
mpsyt version: 0.2.8
pafy version: 0.5.5 (youtube-dl backend)
youtube-dl version: 2021.03.31
Python version: 3.8.6
Platform: Windows-10
VLC Version: 3.0.11

**Comment by gagan-git-sardar** [comment]
I want to contribute

**Comment by iamtalhaasghar** [comment]
I have just added this feature [yewtube](https://github.com/iamtalhaasghar/yewtube#installation), a fork of mps-youtube. You can install it in 5 easy steps.
<br>
![image](https://user-images.githubusercontent.com/46928648/147875552-95983943-c117-4ba6-b351-8a9da5e02f4c.png)
