### ISSUE TITLE
Youtube Error 403

### ISSUE THREAD

**Issue by Mohanbarman** [mps-youtube/mps-youtube#1158]
Whenever I type any search query it returns 
`Youtube Error 403: The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.`
## Your Environment

I am running arch linux
python version : `3.9.2`
mysyt version : `0.2.8`
youtube-dl version : `2021.03.25`

**Comment by HamishFleming** [comment]
same exact environment, same exact problem.

**Comment by grandangelo** [comment]
I just ran into the very same issue.
Please take a look [here](https://github.com/mps-youtube/mps-youtube/issues/1143#issue-792680370), it is explained how to create an API key and get rid of that error.
If it works also for you, please close the issue :blush:

**Comment by iamtalhaasghar** [comment]
> I just ran into the very same issue.
> Please take a look [here](https://github.com/mps-youtube/mps-youtube/issues/1143#issue-792680370), it is explained how to create an API key and get rid of that error.
> If it works also for you, please close the issue blush

Yes, this issue needs to be closed as it is already a known problem. You people need to update your api key.

**Comment by Mohanbarman** [comment]
> I just ran into the very same issue.
> Please take a look [here](https://github.com/mps-youtube/mps-youtube/issues/1143#issue-792680370), it is explained how to create an API key and get rid of that error.
> If it works also for you, please close the issue

Thanks, fixed :)
