### ISSUE TITLE
please read

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [mps-youtube/mps-youtube#1185]
Youtube Error 403: The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.

this happpened and im using mpv (as far as i know in his last version 0.34.0) and windows 10 amd64 and im in python 3.10.1
(so im using the pypi version) and i think that your app don't work because of ffmpeg or an error from the api or simply google being google

**Comment by soyDESKTOP68A2MRFT** [comment]
this is the output from "mpsyt --version"



mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2021.12.17
Python version     : 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]
Processor          : Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
Machine type       : AMD64
Architecture       : 64bit, WindowsPE
Platform           : Windows-10-10.0.19043-SP0
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : C:\Users\10\AppData\Roaming\mps-youtube

**Comment by Blackskydk** [comment]
You need to create your own api key at google, and use `set api_key {API_KEY}` in mpsyt

**Comment by Poseidon444** [comment]
which api key Youtube data v3 ?

**Comment by Blackskydk** [comment]
https://developers.google.com/youtube/v3/getting-started

**Comment by Poseidon444** [comment]
> https://developers.google.com/youtube/v3/getting-started

Thanks a lot

**Comment by iamtalhaasghar** [comment]
or try out [yewtube - a fork of mps-youtube](https://github.com/iamtalhaasghar/yewtube) if you don't want to use Youtube API Key.
