### ISSUE TITLE
I have mutliple troubles with mpsyt

### ISSUE THREAD

**Issue by Fennix900** [mps-youtube/mps-youtube#1190]
I can search and downloads videos without any problems
But i am not able to watch any videos.
I tried to use different players, no success
I can do nothing else than download videos

after choosing a video, i get following error:

Problem playing last item: [Errno 32] Broken pipe   [1/17>
> Error parsing commandline option title: option requires parameter

Exiting... (Fatal error)

mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.2 (youtube-dl backend)
youtube-dl version : 2021.04.26
Python version     : 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.4.0-96-generic-x86_64-with-glibc2.29
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/fennix900/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8
env:LANGUAGE       : en_US

im using linux mint xfce version

the player im using right now is the mpv player
i tried the mplayer but it didnt work

**Comment by iamtalhaasghar** [comment]
see #1191
