### ISSUE TITLE
Last.fm scrobbling support

### ISSUE THREAD

**Issue by andrewmy** [mps-youtube/mps-youtube#142]
It would be a very nice feature to scrobble the tracks.
Posting to the API is quite easy, not so sure about authentication.

**Comment by ids1024** [comment]
Authentication with last.fm requires an api key.  Should the user provide their own?  An api key included with mpsyt would be visible to anyone.

http://www.last.fm/api/scrobbling
http://www.last.fm/api/authentication

**Comment by np1** [comment]
Another consideration is that a lot of items played through mps-youtube are not songs or items that should be scrobbled - how do we determine which items should be scrobbled? How do we determine the artist and track names with confidence? Perhaps if this is implemented it should only apply to items that were retrieved using the `album` command.

**Comment by w-hive** [comment]
+1 for this!

You could probably add the support in easily with pyscrobbler

https://github.com/offmessage/pyscrobbler
