### ISSUE TITLE
Why mps-yt don't play 1080p videos...

### ISSUE THREAD

**Issue by hafuz** [mps-youtube/mps-youtube#151]
Hi,
Thanks for this really good work.
I don't understand why when i play a video available in real 1080p on the youtube site, pmsyt plays it in 720p.
The same for download.
PS: my max-res is 2160p
For example, this one: http://www.youtube.com/watch?v=Y9LxT3v7XaA
Cheers

**Comment by ids1024** [comment]
Apparently mpv has experimental support for DASH video.  To try it, use `mpv --ytdl-format=bestvideo+bestaudio`.  Some changes would have to be made in how mpsyt calls mpv to use this functionality.

**Comment by rcspam** [comment]
Magnific, i hope that you remember to include a user command in mps-yt
Cheers

**Comment by Nordic89** [comment]
Can confirm that
[code]
--ytdl-format=bestvideo+bestaudio
[/code]
definitely works on videos straight from youtube (with mpv). Unfortunately it does not work when added to mps-youtube with playerargs.

**Comment by rcspam** [comment]
Yes i confirm that works on command line but not in mps-yt playerargs.

**Comment by Nordic89** [comment]
@ids1024 

Is there any way to incorporate this into the next release?

**Comment by rcspam** [comment]
+1

**Comment by ids1024** [comment]
I have implemented rudimentary DASH support in the `dash` branch: https://github.com/np1/mps-youtube/tree/dash

Run `set mpv_use_dash true` to enable. You must also have the player set to mpv and `show_video` enabled. Note that resolution it gives in the terminal is currently incorrect for dash videos. Some tweaks are needed before this can be merged.

**Comment by snow3461** [comment]
Hi ! Where are you on this? Is the dash branch impossible to merge with master? I would love to be able to play at 1080p. Will DASH streams be supported at one point?

**Comment by ids1024** [comment]
The `dash` branch is a hack that will never be merged. However, a proper implementation is planned at some point.

The `player.py` file needs to be refactored somewhat before proper dash support can be implemented. Currently it assumes there is only one stream, but with dash there are two: the video stream and the audio stream.

**Comment by snow3461** [comment]
Ok. Thanks for the heads-up.

**Comment by WisdomCode** [comment]
Still no updates?
If not, mpv can handle youtube links without any additional options given, getting the video stream, choosing resolution etc by itself. This may not be what everyone wants, but it would be an easy option to give for those who prefer their videos in full hd. 

Basically, just call:
`mpv "youtubeurl"`
for example:
`mpv "https://www.youtube.com/watch?v=a1Y73sPHKxw"`
Any kind of specific wishings regarding how mpv handles the video can be given from command line as well (and therefore probably with the playerargs option).
AFAIK every command there is for passing to youtube-dl can also be passed to mpv.
For example, to not get anything over 1080p, just pass
`--ytdl-format=bestvideo[height<=?1080]`

Sorry if I am getting it wrong, it seems kind of straightforward to me, so I thought I might share it.
Also, this seems to me like an important feature, so I was wondering that there is not much information here. I'd be glad to help if there is a further problem.

**Comment by disrupted** [comment]
any progress on this? @WisdomCode described it perfectly.

**Comment by MIKSby** [comment]
Still no updates? This feature is perfect!

**Comment by Ofloo** [comment]
I would assume --ytdl-format=bestvideo[height<=?1080] but doesn't help

**Comment by barracuda156** [comment]
> Still no updates? If not, mpv can handle youtube links without any additional options given, getting the video stream, choosing resolution etc by itself. This may not be what everyone wants, but it would be an easy option to give for those who prefer their videos in full hd.

@WisdomCode Do you know which is the lowest version of `mpv` that can do this?

**Comment by WisdomCode** [comment]
@barracuda156 Sorry, I think you're a little late to the party. My Post was made seven years ago, so whatever version the lowest version was, you will have a higher one right now.
I used Xubuntu 18.04 and the mpv from the apt repository at the time, if you really want to backtrace it.
But it's not really useful anymore, youtube-dl, which handles this playing, has been superseded by the fork yt-dlp. I think its also implemented into mpv in a similar fashion and shares the basic syntax, so basically it could work mostly identical. But I don't use yewtube anymore, or mpv to play youtube-videos, so I have not checked this. My main reason was the lack of hardware decoding support in browsers for Linux, something that has been comfortably fixed by now.

**Comment by barracuda156** [comment]
@WisdomCode Got it, thank you for a detailed reply.

P. S. On powerpc browsers – at least so for – are poor for video playback, so alternatives are needed.
