### ISSUE TITLE
YouTube playlist retrieval fetches maximum of 200 items (pafy bug) 

### ISSUE THREAD

**Issue by Jarshvor** [mps-youtube/mps-youtube#192]
hi, im sorry if this is the wrong place to ask about this, or if its been brought up before, but I cant get mpsyt to display all items on a large youtube-playlist. (https://www.youtube.com/playlist?list=PLF6F3B71FFD2611B5)

ive tried the dump command but it only makes it to the 200th item, (184 on the list since some vids have been deleted).

is there something im missing?

**Comment by ids1024** [comment]
You can go through pages with n and p, but you get the same issue as you have with dump.  This is a bug in pafy (which has the same author as mpsyt).  I think I know what is causing this and I will see if I can fix it and submit a PR.

**Comment by Jarshvor** [comment]
thanks ids1024, appreciate it! ;)

**Comment by ids1024** [comment]
Should be fixed with mpsyt and pafy git (mps-youtube/pafy#127).
