### ISSUE TITLE
Displaying/Grabbing the media URL from Search Results?

### ISSUE THREAD

**Issue by ninjada** [mps-youtube/mps-youtube#196]
I can't seem to workout how to achieve this, but it'd be handy to display or even quick copy the actual URL of videos in search results.

Is this possible or could it be added as feature request?

**Comment by np1** [comment]
Do you want the url of the video on the YouTube website or the url of the content stream?

If it's the former it can be viewed by entering `i <number>` and copied to the clipboard using `x <number>` (requires python xerox module to be installed).

If you want the url to stream/download the content, it's not possible currently although it would be fairly straightforward to implement.

**Comment by ninjada** [comment]
yeh sorry, the stream content URL.

**Comment by fehmi** [comment]
+1
