### ISSUE TITLE
Limited results for `all`

### ISSUE THREAD

**Issue by tarwich** [mps-youtube/mps-youtube#201]
When playing all songs from a YouTube user, it would be nice if the system could somehow play all the songs instead of limiting you to the hight of the terminal window.

**Steps to reproduce**
 - Run `mpsyt`
 - Type `user smoothmcgroove`
 - Type `all`

**Expected result**
Should play all 70+ videos for user

**Actual result**
Limits playback entries to height of terminal window

**Comment by np1** [comment]
Yep that would be useful, the `dump` command could be made to work with user results as well as YouTube playlists.

**Comment by bendem** [comment]
Would it be much more work than adding `g.last_search_query.get("user")` [here](https://github.com/np1/mps-youtube/blob/develop/mps_youtube/main.py#L3971)?
