### ISSUE TITLE
Split code into several files

### ISSUE THREAD

**Issue by ids1024** [mps-youtube/mps-youtube#208]
A curses interface as requested in #139 seems like a good idea.  One issue with this is that curses is not supported on Windows, although there does appear to be an extension to get curses working on Windows with pdcurses.  I think it would be a good idea to first separate the backend code from the user interface, to allow having options for multiple user interfaces (for example, to fallback to the current one on Windows, or a GUI).

On a related note, the code could be generally made more modular and split into several files.

@np1 What do you think of this?

**Comment by np1** [comment]
Yup it would be good to split the code into several modules. I'd be glad to do that.

**Comment by ids1024** [comment]
These are the files I am thinking about:
- `main.py`: argument parsing, initialization
- `globals.py`: replace `g` class
- `backend.py`: contains code shared between interfaces
- `config.py`: handling of configuration
- `interfaces/basic.py`: contains a class with the current user interface
- `interfaces/curses.py`: future curses interface

Other ideas:
- As mentioned above, the user interface will be implemented as a class to make it easy to switch for another one.
- An `mpv` and `mplayer` class can be written providing the same interface so that the differences between the two are handled in one part of the code

**Comment by ids1024** [comment]
I plan to start working on this after PR #210 is merged and a new version is released.  Splitting the program into several files is trivial, but it could be harder to fully separate the ui code from the backend so that the latter can be swapped for another.

**Comment by np1** [comment]
@ids1024 do you mind if I do this task (splitting to multiple file)? I'd like to give it a go after the PR is merged.

**Comment by ids1024** [comment]
That's fine; just consider the file layout I mentioned above and note that a major part of my idea is to make the user interface part of the code a separate module/class so that it can be easily switched.

**Comment by ids1024** [comment]
Somewhat related to this, do you think it would make sense to move code in mpsyt using the Youtube api to pafy?  It could be useful to others using the pafy library and it seems more logical to me.

You would have to get permission to license the code under LGPL from anyone who contributed this code, if any was not written by you.

**Comment by np1** [comment]
Yes that would be good too.

**Comment by ids1024** [comment]
I have started working on this, although there is still a great deal of code in main.py and more work to be done.

**Comment by ids1024** [comment]
With commit 2117ded3a27bd2e0345266f1f22fe85771cbe2cf, I think this can finally be called done. Some things may need to be moved around a little, and perhaps a bug or two emerged in the process, but mpsyt is definitely no longer one file.
