### ISSUE TITLE
Option to save start and end times for songs.

### ISSUE THREAD

**Issue by jonathanware** [mps-youtube/mps-youtube#216]
Many music videos have some sort of scene at the beginning before the actual song starts and using official music videos seems to be the best way to ensure a YouTube video doesn't get taken down for copyright infringement.

If we could have an option to tell a song saved to a playlist to always start at a certain second that would help solve the problem. (The same issue sometimes applies for the end of a music video as well)

As an example the actual song in Taylor Swifts Style doesn't start until 10 seconds in.  Roar by Katy Perry doesn't start until 9 seconds in and the song ends at 4:01 with the video being 4:29 long. You get the idea.

**Comment by ids1024** [comment]
This should be possible to implement. What kind of interface do you think it should have? Something like `add videonum, startime, endtime` perhaps, or can you think of something better?

**Comment by jonathanware** [comment]
Something as simple as starttime, endtime would work great I feel. It doesn't need to be all that complicated.

**Comment by ids1024** [comment]
This should be simple to implement in mpv, which has `--start` and `--end` options. I can't see a way to do this in mplayer, however.
