### ISSUE TITLE
Yank title of current playing song.

### ISSUE THREAD

**Issue by r8b7xy** [mps-youtube/mps-youtube#227]
Yanking/copying title of current playing song as a cleat text will be quite handy.
e.g. yy will yank 'The Rolling Stones - Start Me Up' which i can paste into my browser for future searching and adding music to my itunes

**Comment by EduardoRT** [comment]
You can yank it, but not while playing ( still ) you'll need xerox and then using x <option> will copy the video url in your clipboard. This will be a good addition though, you won't have to leave the video to yank the url.
