### ISSUE TITLE
MPSYT not working through php script

### ISSUE THREAD

**Issue by arbakker** [mps-youtube/mps-youtube#231]
Hi,

I have an apache server with php script that takes a URL as a post parameter (to a youtube video) and then starts mpsyt (v 0.2.3) through:

`exec('mpsyt playurl "'.$url.'" 2>&1');`

When I execute this by submitting an url in my browser mpyst fails to run properly and I receive the following output from mpsyt:

`Fetched video info Getting content length a1Y73sPHKxw; m4a 256k; 0 Mb error: retrying Fetched video info Getting content length a1Y73sPHKxw; mp4 640x360; 0 Mb error: retrying Fetched video info Getting content length a1Y73sPHKxw; flv 320x240; 0 Mb error: retrying Fetched video info Getting content length a1Y73sPHKxw; 3gp 320x240; 0 Mb`

When I execute the same line logged in as the http user in a terminal session mpsyt runs just fine. Any idea what could be the problem?

**Comment by ids1024** [comment]
Mpsyt is probably not the best program to use for this. You would be better off using `mpv URL ` (requires youtube-dl).

**Comment by n1tr0-5urf3r** [comment]
I managed this with creating a temporary file containing the link I entered in the php form
My bash script uses grep to get the link from the file
```
<?php
        $youtubeLink= $_POST['ytsearch'];
        print($youtubeLink);
        $dateiname = "youtubeTemp.php";
        $handler = fOpen($dateiname , "a+");
        fWrite($handler , $youtubeLink);
        fClose($handler);
        trim(@shell_exec("/usr/local/bin/ytsearch.sh"));
?>
```
ytsearch.sh
```
#!/bin/bash

FILE=/var/www/youtubeTemp.php
url=`head -n 1 $FILE`
rm $FILE

sudo /usr/local/bin/mpsyt playurl $url
```
