### ISSUE TITLE
Noise

### ISSUE THREAD

**Issue by mydesireiscoma** [mps-youtube/mps-youtube#258]
Ubuntu 14.04 with latest updates

Installed with instructions, placed at: 
http://www.webupd8.org/2014/02/new-command-line-youtube-player-and.html

On some tracks in playlists, instead music, i hear only noise. 
As example, i run player, then do:

I search for playlist

> pls within temptation playlist

Then select playlist

> 1 

Then select song

> 2

**Comment by lol768** [comment]
I can't reproduce this using either the latest stable code or PR #256. I'm using mpv as the player.

When I follow your steps, the player plays video with ID "jDJpf2mQ0w4" (title is "Within Temptation - Faster Music Video"), is this the same for you? Can you play the song if you use "da 2" and then play the locally downloaded file?

**Comment by mydesireiscoma** [comment]
Yes, same video. 
But i don't download any song, i just do search (pls keyword) and then just enter numbers without anything (e.g. 1, then 2). 
If i use "da 2" and then play locally downloaded file - all works fine.

Maybe there something wrong in guide?

**Comment by JKatzwinkel** [comment]
Could reproduce with Python 2.7.3, pafy 0.3.72, MPlayer svn r34540, ffmpeg  6:0.8.17-1 on Debian 7.8 (wheezy) (` 3.14-0.bpo.1-amd64 #1 SMP Debian 3.14.12-1~bpo70+1 (2014-07-13) x86_64 GNU/Linux`)

**Comment by mydesireiscoma** [comment]
Mb something wrong with codecs... or player...

**Comment by lol768** [comment]
Switched over to mpv and I can reproduce this. It's interesting because it seems to play twice as fast for me.

**Comment by ids1024** [comment]
I can't seem to reproduce this on my Archlinux system with that video and either mpv or mplayer.

@mydesireiscoma If you're using mplayer, using mpv instead will likely fix it. Install mpv and run `set player mpv` in mpsyt.

**Comment by mydesireiscoma** [comment]
With `mpv` all works fine, @ids1024 , thanks for solution.
And also, when i used `mplayer`, i noticed what i can play no more than 16 songs.
I mean, if i'll open youtube playlist with 32 songs, then in `mpsyt` i can see and play only first 16 songs, no more, only less

sorry for bad English ;)
