### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by pipointzero** [mps-youtube/mps-youtube#266]
Hi,
I am trying to use mps-youtube on a RaspberryPi with Volumio distribution which is a modified Raspbian.
1- I had issue with mplayer which I wasn't able to run without sudo. I solved this problem by adding the user "volumio" to the audio group. So now I can play audio files with mplayer alone without sudo.
2- Then I wasn't able to run mpsyt without sudo. I solved this by creating the folders ~/.config and ~/.config/mps-youtube and by changing the owner using "sudo chown -R volumio ~/.config/mps-youtube" command. Now I can launch mpsyt without sudo.
3- But when I run mpsyt and I play a song, no sound is coming out.
4- I tried to use mpv but it is not working for an libnav issue...
Would you have some ideas I could try to solve this ?
Thanks a lot.

**Comment by ids1024** [comment]
Do you get a status bar showing that it is playing? Does increasing the volume with the `*` key help?

**Comment by pipointzero** [comment]
Yes the status bar is displayed and moving, however even if I put maximum volume with 0 or * it doesn't change anything.

**Comment by ids1024** [comment]
You can try using mpv instead of mplayer.

**Comment by nguyenvinhlinh** [comment]
@pipointzero does it work ?

**Comment by pipointzero** [comment]
Hi, no it doesn't work for a different reason. Actually mpv doesn't work because it says something like it wasn't compiled with the same version of libnav than the one installed on the system.
I wonder if the problem is not Volumio which could be shipped with outdated packages.
Sorry for my late answer.

**Comment by pipointzero** [comment]
Ok, I installed it on a fresh Raspbian and everything works. Problem solved.
Thanks.

**Comment by ids1024** [comment]
@pipointzero Is it working with mplayer, or have you switched to mpv now?

**Comment by pipointzero** [comment]
I don't use it any more because it stops playing after 2 minutes like other people already experienced.
Mpv package is not available for raspbian, so I should build it my self. Unfortunately, I didn't find any help on the subject and the compilation doesn't seem trivial because of a lot of weird dependencies.
So I am passively waiting for a solution because I don't have programming skills.

**Comment by pipointzero** [comment]
Hi, problem solved using python 3.2 and the corresponding pip version.
You must force pip tu use python 3.2 and everything will work fine with mplayer.
(on raspbian)
