### ISSUE TITLE
Remove landscape?

### ISSUE THREAD

**Issue by lol768** [mps-youtube/mps-youtube#273]
Since the code was updated to only support Python3, it seems that landscape.io has been unable to parse the `main.py` file and I'm not sure how useful the service remains. It might be worth looking into some alternatives?

https://landscape.io/github/np1/mps-youtube/136

https://github.com/landscapeio/landscape-issues/issues/32

https://docs.landscape.io/faq.html#troubleshooting

> **Does Landscape work with Python3?**
> Unfortunately not yet. This is a heavily requested feature however and so development is underway!

**Comment by ids1024** [comment]
Are there any services that provide similar functionality but support python 3? In a quick search, I can't seem to find any. Hopefully it will add support for python 3, but who knows when that will happen...

**Comment by hrnr** [comment]
I think #208 will help. Hopefully as codebase is still mostly python2 compliant we could go with some ignores and make use of landscape.

**Comment by ids1024** [comment]
@hrnr Look at the output of landscape. It can't even parse the file because of the use of the print() function.

I have removed the landscape badge from readme.rst.

**Comment by hrnr** [comment]
what you think about #281? It should make landscape happy again.
