### ISSUE TITLE
Reverse search order

### ISSUE THREAD

**Issue by JoeGaebel** [mps-youtube/mps-youtube#290]
You can set the search result order as relevance, date, views, or rating - it would be awesome to reverse the order based on those metrics. Ie. Least viewed, or more practical - newest videos. One could use that feature when looking at a particular Youtube user, and sorting for the newest videos

**Comment by lol768** [comment]
Not sure this is possible. The `order` field passed to the API must be one of:

* date – Resources are sorted in reverse chronological order based on the date they were created.
* rating – Resources are sorted from highest to lowest rating.
* relevance – Resources are sorted based on their relevance to the search query. This is the default value for this parameter.
* title – Resources are sorted alphabetically by title.
* videoCount – Channels are sorted in descending order of their number of uploaded videos.
* viewCount – Resources are sorted from highest to lowest number of views.

You could try and emulate it by seeking to the 'last' page of a search results list but unfortunately the results are [capped](http://stackoverflow.com/a/27526563) and it seems there are [issues](https://code.google.com/p/gdata-issues/issues/detail?id=5990) with the pagination too. You'd probably need to either step through all pages of results to get the token for the last page (probably about 50 HTTP requests) and it seems like the results counter is [inaccurate anyway](https://code.google.com/p/gdata-issues/issues/detail?id=4282).

As far as I can see the only thing you could do is reverse one page of results (so you'd end up seeing the 50th most viewed video as the least viewed with the most viewed at the bottom) which probably isn't very useful.

**Comment by JKatzwinkel** [comment]
@lol768 Given all those observations you are making there: If we can get the number of results we can display at best (like 500) and the number of results we can display on one page and can specify the start index in an API call, would this not suffice for us to emulate reverse order displayal?

**Comment by lol768** [comment]
@JKatzwinkel Perhaps, but it wouldn't be anywhere near accurate. Keep in mind that the results counter appears to be incorrect (per the linked bug report), so we could end up generating page tokens for pages which don't exist or aren't the last page in the results. Add in the cap, and we'd miss off the least viewed or earliest videos.

IMO it'd probably be better to try and get YouTube to [officially support this](https://code.google.com/p/gdata-issues/issues/detail?id=5993).

**Comment by JKatzwinkel** [comment]
Ok thanks, I get it now and agree on us better not doing some reverse-order stunt for now.

**Comment by ids1024** [comment]
I agree with @lol768 and @JKatzwinkel. Maybe Google will add this functionality to the API, but until then there is no good way to implement such a thing.

**Comment by ids1024** [comment]
Closing for now. It can be reopened if youtube ever implements such functionality.
