### ISSUE TITLE
Doesn't download full YouTube playlists

### ISSUE THREAD

**Issue by hotice** [mps-youtube/mps-youtube#294]
mps-youtube doesn't download complete YouTube playlists. The app can only download (e.g. using ``dapl <playlisturl>``) the songs that fit on the terminal screen height - so for instance, when used with the standard Gnome Terminal window size, it only downloads 21-22 items from the playlist. If for instance I maximize the terminal window, then it can download more items (40-45 or so).

Tested using mps-youtube 0.2.4 under Ubuntu 15.04.

**Comment by JKatzwinkel** [comment]
I have had this taken care of in another branch, can re-apply fix as soon as I find a little time.

**Comment by pnutus** [comment]
I'm not sure if this is the same bug, but if I say `save` when viewing a YouTube playlist, I expect the entire playlist to be downloaded. Instead, it only downloads the visible items. Looking in the help, this seems to be the intended behavior: `save or save <name> - save the displayed items as a playlist`. However, I can't find any way to just save a YouTube playlist locally (which to me seems more useful than the current behavior).

**Comment by ids1024** [comment]
@pnutus try running `dump` to get all the items, then `save`.
