### ISSUE TITLE
Song stop

### ISSUE THREAD

**Issue by robotrono** [mps-youtube/mps-youtube#297]
I play my youtube list then select one song after for any seconds the song stop. Sorry for my bad english. 

mpsyt version  : 0.2.4
   notes       : released 13 May 2015
pafy version   : 0.3.72
Python version : 3.4.0 (default, Apr 11 2014, 13:05:11)
[GCC 4.8.2]
Processor      : x86_64
Machine type   : x86_64
Architecture   : 64bit, ELF
Platform       : Linux-2.6.32-042stab094.7-x86_64-with-Ubuntu-14.04-trusty
sys.stdout.enc : ANSI_X3.4-1968
default enc    : utf-8
Config dir     : /root/.config/mps-youtube
env:TERM       : xterm
env:SHELL      : /bin/bash

Screen: http://puu.sh/i6Woo/2fc7d6da69.png

**Comment by robotrono** [comment]
mplayer is the problem...

**Comment by laapsaap** [comment]
Do you know what is going wrong with mplayer? I didnt update mplayer but got similar problem after updating mps-youtube.

**Comment by robotrono** [comment]
When I set mplayer, the song go too fast and dont play correctly, I'm testing mpv now

**Comment by maxlath** [comment]
It seems I have a comparable issue: since the last update (0.2.4), mps stops playing after a few minutes. I'm using mplayer too, and couldn't test with mpv to see if it fixes the problem

**Comment by JKatzwinkel** [comment]
I experienced this before in combination with what is described in #258.
