### ISSUE TITLE
PiTFT support

### ISSUE THREAD

**Issue by qkpham** [mps-youtube/mps-youtube#308]
Hello,

I am trying to make mps-youtube work on a PiTFT Plus from Adafruit. Screen is 320x240 resolution. I am using mplayer with the following arguments (as shown in Adafruit tutorial): 

-vo fbdev2:/dev/fb1 -x 240 -y 320 -framedrop 

max_res is set to lowest resolution 240p ( playback used to work using youtube-dl + mplayer)

Also I'd like to change the splashscreen as it is all scrambled due to low resolution of the display.

Thank you

**Comment by ids1024** [comment]
You can change the splash screen by manually editing the code. Change the value of `logo_txt` in the `logo` function to a blank string or whatever you want. Are you having any difficulty other than the splash screen?

**Comment by qkpham** [comment]
Yes, as I said, video does not play on the PiTFT using mplayer. I used to use youtube-dl set at 240p and then I played the video using mplayer. Does not seem to work on mpsyt for some reason. I have used set show_video, max_res and window size etc.. Any idea?

**Comment by ids1024** [comment]
Can you give any more details, like an error message? Also, you can try using mpv rather than mplayer.

**Comment by ids1024** [comment]
Also, does it work fine on the same raspberry pi if it is connected to a full sized display instead of the PiTFT?

**Comment by IonicaBizau** [comment]
Any solution to this? From what I know there is a frame/second limitation for LCD screens. Is there a way to hack it to watch videos?

Thanks! :apple:

**Comment by ids1024** [comment]
@IonicaBizau Are you able to use mpv or mplayer (whichever mpsyt is set to use as a backend) to play a video on the lcd outside of mpsyt? Does mpsyt work on a large display instead of the small lcd?

**Comment by IonicaBizau** [comment]
> Does mpsyt work on a large display instead of the small lcd?

Yes, that's working smoothly after `sudo apt-get install`ing `mplayer2`. Btw, this is awesome solution for watching YouTube videos on pi! Thanks a lot! :sparkles: 

I will try it on my 3.5" display too.

**Comment by IonicaBizau** [comment]
Actually is working relatively good, like I already specified it's a little bit laggy due to the frames per second limit (hardware limitation).

But after some minutes (let's say 7-10 minutes of playing a long video) it starts to lag (pauses and starts and pauses again). There is already a related issue (#242), I don't know if it has the same cause or not...

Anyway, I'm pretty happy with using this tool on my pi. :smile:

**Comment by IonicaBizau** [comment]
(btw, to stop the video lagging that occurs after some minutes, I press <kbd>→</kbd>, and then it stops lagging for some minutes)

**Comment by IonicaBizau** [comment]
@ids1024 However, I am noticing that the video part is slower than the audio–is there a way to set the frames per second?

**Comment by ids1024** [comment]
Using `set playerargs` you can pass arguments to mplayer/mpv. Look at the man page for that. There probably is an option for that.

**Comment by qkpham** [comment]
Could you provide me the arguments & player settings required to play videos on PiTFT with MPV? Doesn't show video on mine. Thank you

**Comment by IonicaBizau** [comment]
@ids1024 I also know how to do that. I installed mpv on my pi, but how do I set mpv to skip frames?

In mpv manual I see this:

```sh
       --hr-seek-framedrop=<yes|no>
              Allow  the  video  decoder  to drop frames during seek, if these
              frames are before the seek target. If this is  enabled,  precise
              seeking  can  be faster, but if you're using video filters which
              modify timestamps or add new frames,  it  can  lead  to  precise
              seeking  skipping  the  target  frame. This e.g. can break frame
              backstepping when deinterlacing is enabled.

              Default: yes
```

Maybe `set playerargs "--hr-seek-framedrop=yes"` should work?

**Comment by IonicaBizau** [comment]
@qkpham Try `set playerargs "--hr-seek-framedrop=yes"`––and give me feedback if that solved the problem. To show the video, do `set show_video true`.

**Comment by qkpham** [comment]
Video does not seem to play - time is stuck to 00:00. Is there any other settings I should modify? I've set resolution to 240p and I've tried 320x240 for window_size + fullscreen as true

**Comment by IonicaBizau** [comment]
@qkpham What operating system are you using? Is `mpv` working if you play an audio file?

**Comment by qkpham** [comment]
I'm using Raspbian Jessie. When I set show_video to false . Time works and audio plays correctly.

**Comment by IonicaBizau** [comment]
@qkpham Maybe try to play a local video file using `mpv your-video.mp4` and see if that works. If I understand correctly, `mpsyt` is just a :cool: bridge between the YouTube  API and a local video player (`mplayer`, `mpv` etc).

**Comment by qkpham** [comment]
I know that before I started to use mpsyt, it would work perfectly using mplayer and youtube-dl with adafruit pitft tutorial for playing videos. Just wondering how that would be with mpv.

**Comment by qkpham** [comment]
I managed to make it work under X with hr-seek-framedrop args but how can I make it work in console-mode only? I guess it has to do with switching to different framebuffer?
