### ISSUE TITLE
Flattr donations

### ISSUE THREAD

**Issue by orschiro** [mps-youtube/mps-youtube#312]
Hi all, 

Great piece of software that you're developing!

I would like to support you on flattr.com. 

Do you plan to support flattr donations?

Warmly,

Robert

**Comment by ids1024** [comment]
I don't know how that would really work for a project with multiple contributors. @np1 wrote most of the code, but has stopped developing mpsyt for lack of time (#259), and I have taken over development. Other people have also made significant contributions. Probably the majority of the code for porting to the new youtube API (#256) was written by @JKatzwinkel. The mpris support (#210), which is the most exciting recent feature, was implemented mostly by @hrnr. Those are just the recent contributions that come to mind, there have been numberous other by several other people.
