### ISSUE TITLE
Redraw screen on terminal window resize

### ISSUE THREAD

**Issue by Atlantic777** [mps-youtube/mps-youtube#313]
It seems that terminal window size is detected on each redraw, and redraw is triggered only on a player's event. It would be nice to add one more event which will trigger redrawing of mps-youtube window - the terminal resize.

Here's BDD style scenario:

```
Given that you have mps-youtube running,
When you resize that window
Then mps-youtube should redraw
And fit into new dimensions.
```

The problem is that when I start mps-youtube and it's only window in a tilling wm workspace, then it occupies whole screen. That looks like in the first image. When I open another window, then mps-youtube window is resized, and it is jagged out until I change playlist, do search or something else. it looks like in the second picture.

![Imgur](http://i.imgur.com/Pc6J6wDm.png)
[original size](http://i.imgur.com/Pc6J6wD.png)

![Imgur](http://i.imgur.com/EMWfxvhm.png)
[original size](http://i.imgur.com/EMWfxvh.png)

**Comment by ids1024** [comment]
I don't know how simple that would be. A curses interface is planned (#139) at some point, and that should allow things like this.

**Comment by Atlantic777** [comment]
Every solution for handling this event which I have found so far is related to curses. I didn't notice that curses interface idea is accepted and planned (hooray!).

Anyway, if someone has a quick solution for registering such event handler without using curses, please notice me. It should be as easy as 10 lines of code to support this.

**Comment by ids1024** [comment]
I hope to have a curses ui in the next release, but no guarantees.

**Comment by Atlantic777** [comment]
Guys in the `#python` IRC channel suggested me using *SIGWINCH*. (thanks _habnabit)

Wikipedia says this:

> **SIGWINCH**
>  The SIGWINCH signal is sent to a process when its controlling terminal changes its size (a window change).

Here's a simple demo:

``` python
import signal

def resize_handler(signum, frame):
  print("Resize happened")

signal.signal(signal.SIGWINCH, resize_handler)

# now resize window
```

**Comment by Atlantic777** [comment]
By the way, where we can/will be able to follow development of curses interface?

**Comment by ids1024** [comment]
I'll try SIGWINCH.

I haven't started working on a curses ui yet, but when I do I will post more info to that issue.

**Comment by ids1024** [comment]
It looks like implementing this is not as simple as it might seem, with how the code is structured. That said, the same changes will be needed for the curses interface, so it is definitely worth doing.

**Comment by ids1024** [comment]
It also looks like SIGWINCH is (unsurprisingly) Unix only, so something else would be needed to implement it on Windows.

**Comment by JKatzwinkel** [comment]
I don't think there are a lot of people using i3 on windows.

**Comment by Atlantic777** [comment]
Yup, but resize redraw feature is related to any WM and any OS.

**Comment by ids1024** [comment]
Another method would be to just repeatedly check the terminal size in a separate thread, but that would not be preferable. This can probably wait for a curses ui.

**Comment by ids1024** [comment]
So, how should it handle pagination? If, say, mpsyt is open to a search or playlist on page 3, and then the window is resized to half the size. The easy solution would be to just load page 3, but it would have entirely different items on it than the original one.

**Comment by bendem** [comment]
I'd say it should display the page that contains the element that was at the top before the resize. But that's probably just an arbitrary decision and it shouldn't happen that often anyway.

**Comment by ids1024** [comment]
That is an option, but what if the user is playing a video at the bottom of the list?

I think that could also have strange results if there are several resizes...

**Comment by JKatzwinkel** [comment]
In a curses UI, I always imagined pagination to be obsolete and to have a scrollable result list and a 'load more' command instead.
