### ISSUE TITLE
user <username> not found (always)

### ISSUE THREAD

**Issue by VdeVatman** [mps-youtube/mps-youtube#319]
Whenever I use "user" command it just doesn't work, for example, if I try:
```
user magicofrahat 
```
Answer would be: 

![this](http://oi57.tinypic.com/2s0oil0.jpg) 

When it clearly exists: https://www.youtube.com/user/MagicofRahat

I'm running on version 0.2.5 without any error dump, any idea of why this happen?

PS: I noticed that although it says the username wasn't found, I write it as "magicofrahat", but even so it says "MagicofRahat" as it realy is, so it seems like it is finding the username, but it doesn't.

**Comment by ids1024** [comment]
That is strange, and I am getting the same issue on my computer, but not with every user. That one does not work, but `user rushvevo` does. I will look into this.

**Comment by ids1024** [comment]
Ok, I found the issue. By default, mpsyt only searches in the `music` category, while none of the videos by that user are in that category. Use `set search_music false` to  change this.

**Comment by VdeVatman** [comment]
It works now, thanks.

**Comment by mobiuscoffee** [comment]
I have the same problem and using `set search_music false` doesn't fix it. At least not for the `user` command. It does fix it in searches strangely.

**Comment by ids1024** [comment]
@mobiuscoffee Maybe your problem is related to caching. Run `clearcache` and try again with `search_music` set to `false`.

**Comment by mobiuscoffee** [comment]
Ran `clearcache` and made sure `search_music` was set to false, but `user` still has the same problem.

**Comment by ids1024** [comment]
@mobiuscoffee do you have this issue with the same user (`magicofrahat`)?

**Comment by mobiuscoffee** [comment]
Just tried with `magicofrahat` and I had the same issue. I had been trying with `letsplay` and `rooster teeth` and a few others that resulted in the same error.

**Comment by ids1024** [comment]
@mobiuscoffee Are you running the latest version of mps-youtube?

**Comment by mobiuscoffee** [comment]
just ran `install --upgrade` and the problem is fixed!
