### ISSUE TITLE
Installed latest version but not recognised

### ISSUE THREAD

**Issue by orschiro** [mps-youtube/mps-youtube#320]
Dear all, 

I installed the latest version `0.2.5` on eOS (Ubuntu 14.04). 

However, as you can see in the below screenshot, the command `mpsyt` still launches the previous version `0.2.4`. I already rebooted my system and reloaded my Shell session. 

Any ideas?

Thanks!

Robert

![image](https://cloud.githubusercontent.com/assets/170947/8350959/fff2b130-1b29-11e5-8422-4ab88e33bb02.png)

**Comment by ids1024** [comment]
I don't know what is causing this. Does it say "v0.2.4" under "youtube" on the splash screen? It is not visible in this screenshot. Does the mix command, which was added in 0.2.5, work? For that, open some playlist and type `mix 1` (or the number of any other track). What is the output of `which mpsyt` in the shell?

**Comment by orschiro** [comment]
@ids1024 

Thanks for the valuable hint to check with `which`. It turned out that a local copy was stored under `/usr/local/bin`. I removed this one and re-installed the latest `deb` package. Now it properly launches the latest version. 

Thanks for your help!

Robert
