### ISSUE TITLE
Problem parsing video name with the symbol "&"

### ISSUE THREAD

**Issue by snow3461** [mps-youtube/mps-youtube#321]
Hi,

I'm encountering problems every time I try to play a video which name contains the symbol "&"

It's like it's trying to interpret what's after the "&" as a command as I get the message : "not recognised as internal command..."

I'll be happy to sort this out, but I don't know where to start, like how to get a log file for this error ?

Thanks

EDIT : I does happen for master and develop branches.

**Comment by lol768** [comment]
Can you provide an example video? I can play "c5TJgpowg_k" (name 'The Kite String Tangle & Dustin Tebbutt - Illuminate') using mpv with no issues.

**Comment by snow3461** [comment]
Ok,this is also happening with your video. I guess it's my setup then. I'm on windows 8 and I run mpsyt by typing mpsyt in my windows terminal. Any clue?

**Comment by ids1024** [comment]
Fixed in commit 0b103fc40fabd05089b3642197389975f1c04a90 on the develop branch.

**Comment by snow3461** [comment]
thanks a lot for this!
