### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by DCurro** [mps-youtube/mps-youtube#323]
I'm having lots of trouble running main.py.  Are there 'build' instructions somewhere?

**Comment by lol768** [comment]
Should just be a case of cloning and running the '[mpsyt](https://github.com/mps-youtube/mps-youtube/blob/develop/mpsyt)' script. Are you seeing any errors/output when trying the above?

**Comment by DrKondor** [comment]
Me some too. I've installed mps-youtube before, easy peasy. But this time the script trips up with this error:

File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 54, in <module>
    from urllib.request import urlopen, build_opener
ImportError: No module named request

**Comment by DCurro** [comment]
Hey thanks for the heads up. I'm new to python and I assumed mpsyt was a
binary, not a script

**Comment by lol768** [comment]
@DrKondor 

> File "/usr/local/lib/python**2.7**...

See https://github.com/mps-youtube/mps-youtube/commit/3f7c9928d98625c2c98234d707f866e2df49450b

**Comment by DrKondor** [comment]
OK. So, to clarify, mpsyt now requires Python 3. So, you'll need to install (on Debian Jessie anyway):

[sudo] pip install python3-pip

Then follow the install instructions.

**Comment by ids1024** [comment]
Python is an interpreted language, so there is no building required. You can run the `mpsyt` script from the source directory, or install it.

@DCurro Are you still having any problems?

**Comment by DCurro** [comment]
I mistook mpsyt for a binary and not a bash script. It's been resolved
thanks so much!
