### ISSUE TITLE
Doesn't seem to play stream with UTF8 characters

### ISSUE THREAD

**Issue by nkahoang** [mps-youtube/mps-youtube#324]
Hi,

I'm having issues playing clips with UTF8 characters. An example can be reproduced as:

1. Launch `mpsyt`.
2. Set player to `mpv` (mplayer doesn't seem to work anymore as many streams on YouTube are https now)
3. Search for a song (example: `/giac mo co that`)
4. Play the first song (`1`)

Mpsyt seems to get into a loop of `error: retrying` (I modified the log of the app and it returns the exit code from mpv. Most of the time this value is 1 or 2)

Downloading the song and then play it afterward is fine.

My `mpsyt --debug`:

```
mpsyt version  : 0.2.5
   notes       : released 1 June 2015
pafy version   : 0.3.74
Python version : 3.4.3 (default, May  1 2015, 19:14:18)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)]
Processor      : i386
Machine type   : x86_64
Architecture   : 64bit,
Platform       : Darwin-14.4.0-x86_64-i386-64bit
sys.stdout.enc : UTF-8
default enc    : utf-8
Config dir     : /Users/myusername/.config/mps-youtube
env:TERM       : xterm-256color
env:SHELL      : /bin/zsh
env:LANG       : en_AU.UTF-8
```

**Comment by lol768** [comment]
Which video in particular are you trying to play (I can play Xm-G4R_Xdnk locally without the loop)? Keep in mind the search results will vary based on what `order` and `search_music` are set to.

**Comment by nkahoang** [comment]
Hi `lol768`

It was `P4EHM976bw8`

**Comment by ids1024** [comment]
Use `set playerargs --msg-level=all=status` and try again for more information about what the issue is.

**Comment by nkahoang** [comment]
Ah it turns out to be a problem with my ffmpeg (I got `ffmpeg https protocol not found recompile with openssl or gnutls enabled`) . You might want to add this fix to your troubleshooting faqs or something.

`brew install ffmpeg --enable-openssl --with-openssl` to install a version of `ffmpeg` that supports openssl. Then uninstall and reinstall mpv to link with the new ffmpeg lib.

And mpsyt works again with mpv for me. Thanks!
