### ISSUE TITLE
Web frontend or android/ios remote?

### ISSUE THREAD

**Issue by lukasmrtvy** [mps-youtube/mps-youtube#327]
Hi, is there any plan that includes a developing web frontend or android / ios remote?
Because i didn't find any other server applications, that plays youtube playlists and have friendly user interface (managing playlists and songs from youtube)
Mopidy has a youtube backend, but you have to add manually songs to m3u playlist.
Thanks

**Comment by ids1024** [comment]
A curses interface is planned ( #139) in the near future. My idea to to have a system that would allow multiple user interfaces as plugins (using the plugin api that is currently under development #314 #316). That way, a webui could be developed. Or perhaps it could not be a ui, but just a plugin that runs separately. A plugin to allow for an android or ios remote would probably be possible.

So, once the plugin api is finished, it should be possible to create a plugin for this, as long as someone is interested in developing it. I may develop such a thing, but no guarantees.
