### ISSUE TITLE
Issue: When viewing a local playlist with more than 50 items, only shows first 50 items.

### ISSUE THREAD

**Issue by Wildefyr** [mps-youtube/mps-youtube#328]
You can see select the songs from the playlist, i.e. using * still puts all items into the playing queue and you can see them being played. For example:

https://u.teknik.io/l7Tkdf.png
https://u.teknik.io/l7Tkdf.png

[Latest Git Version](https://u.teknik.io/GBloEq.png)

**Comment by ids1024** [comment]
Use `dump` and then `*`. That should work, but it seems the `n` and `p` commands are not working for local playlists, which should be fixed.

**Comment by Wildefyr** [comment]
Hmm, odd, on my windows 2.5 build I don't have to use dump to see the entire contents of the playlist. Probably better to use dump when you want it though.

**Comment by ids1024** [comment]
Well, how long is the playlist on question? Without dump, it plays all tracks on the screen, which could be more than 50 in a larger terminal.

**Comment by Wildefyr** [comment]
Okay, I save more than 50 items to a local playlist. When I open the playlist it only shows the first 50 items even though I can type 90 or whatever number is higher than 50 and load a track. Even when playing it only shows the first 50 tracks.

**Comment by Wildefyr** [comment]
Forgot about this issue, but seems to be fixed for me.
