### ISSUE TITLE
user command not working for a channel

### ISSUE THREAD

**Issue by mobiuscoffee** [mps-youtube/mps-youtube#330]
I'm having a small problem with `user` where on a certain channel instead of showing me the videos on the channel it gives this error:

```
Problem playing last item: too many values to unpack (expected 3)
```

I'm trying to load [this channel](https://www.youtube.com/channel/UCKNJiTmKrur10zxStf5Gztw) and looking at it now, could it be because the official name is a bit odd as `NESblog / Speed Game`?

Searching for the videos works fine so it's not a huge problem, but it's somewhat odd.

**Comment by ids1024** [comment]
I see the problem. You are quite correct, it is due to a `/` in the channel name. This should be simple enough to fix.

**Comment by mobiuscoffee** [comment]
Ah yeah that'd be a problem.

Would there be any way to have the channel come up by just doing something like `user NESblog` and leaving off the `/ Speed Game`. Or leaving off the `/` some other way?

**Comment by Jimmm** [comment]
try channel ID UCKNJiTmKrur10zxStf5Gztw,
you can get it sometimes from the URL.

Or try:
If you don't know how to get the channelID of a channel use ressource channels.list:

With this parameters to get the video ID of a playlist :

part: 'id'
forUsername: 'channel_name'

https://www.googleapis.com/youtube/v3/channels?part=id&forUsername=GEazyTV&key={YOUR_API_KEY}

 "items": [
  {

   "kind": "youtube#channel",
   "etag": "\"PSjn-HSKiX6orvNhGZvglLI2lvk/vIwM6ev74Om0AOupX26jJoEDELU\"",
   "id": "UCBkNpeyvBO2TdPGVC_PsPUA"
  }

From: http://stackoverflow.com/questions/26831919/get-all-playlist-ids-from-channel-id-youtube-api-v3
