### ISSUE TITLE
Windows Defender flags mpsyt-0.2.5.exe

### ISSUE THREAD

**Issue by cirrusUK** [mps-youtube/mps-youtube#332]
I downloaded mpsyt-0.2.5.exe from the releases page, next thing Windows Defender pipes up saying it is Zwangi browser modifier and promptly removed it. Having been a long time user of mpsyt on both windows and linux i have never had any untoward browser settings (hijacks)  so i assume its a false positive and maybe dev should let them know.
regards

**Comment by ids1024** [comment]
It seems to be an issue with py2exe: http://sourceforge.net/p/py2exe/bugs/135/
