### ISSUE TITLE
Dbus error

### ISSUE THREAD

**Issue by MauricioAlgalan** [mps-youtube/mps-youtube#337]
Today mpsyt begins with this error:

>File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Enter /search-term to search or [h]elp
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/mpris.py", line 519, in main
    mprisctl.acquire()
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/mpris.py", line 72, in acquire
    self._acquire_bus()
>   File "/usr/local/lib/python3.4/dist-packages/mps_youtube/mpris.py", line 113, in _acquire_bus
    bus=dbus.SessionBus(mainloop=DBusGMainLoop()))
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11

When play a sing starts, but after that  the player, mpv or mplayer stop, and I have to cancel the player. The next time I play a song never start. 

This hapen only in tty, xterm works fine.

Today use python enviroment (venv) to install a pip package, using 2.7, I don't now if the venv affect mpsyt in tty.

**Comment by hrnr** [comment]
‎This seems to be bug. Need to add check when starting main loop for MPRIS.                                                                                                                                                                                  ‎

**Comment by hrnr** [comment]
I have implemented the fix. Sorry for the inconvenience.

**Comment by MauricioAlgalan** [comment]
Thanks
