### ISSUE TITLE
sorting result

### ISSUE THREAD

**Issue by rachmadaniHaryono** [mps-youtube/mps-youtube#340]
can the search result be sorted either by title or time?

**Comment by ids1024** [comment]
Use `set order date` to sort by the date of a video. Sorting by title is not currently an option, but it is simple enough to implement, so I added it to commit 81d802aa546d433baa31e6ebb9ee733064eecfdd and it is now an option in the `develop` branch or the next release.

**Comment by rachmadaniHaryono** [comment]
Could you also add sort by track length?

**Comment by lol768** [comment]
I don't believe sorting by track length is possible.

![](https://i.imgur.com/BX6gyrN.png)

**Comment by ids1024** [comment]
As @lol768 said, that is not possible, because the youtube api does not provide that functionality.

**Comment by rachmadaniHaryono** [comment]
Maybe not but as per page search, I think that will be easier.

**Comment by rachmadaniHaryono** [comment]
example
 1   Lamb of God - Overlord                                          06:32
 2   オーバーロード OP 【FULLi】- Overlord Opening (Clattanoia)      03:00
 3   OverLord - E ta dish.. [Solo 2010]                              02:05
 4   OVERLORD OP - Clattanoia - OxT - Engsub (Lyrics on Screen)      01:31
 5   Overlord Op: Clattanoia (Piano) オーバーロード Op ピアノ        01:31

sorting result
4   OVERLORD OP - Clattanoia - OxT - Engsub (Lyrics on Screen)      01:31
5   Overlord Op: Clattanoia (Piano) オーバーロード Op ピアノ        01:31
3   OverLord - E ta dish.. [Solo 2010]                              02:05
2   オーバーロード OP 【FULLi】- Overlord Opening (Clattanoia)      03:00
1   Lamb of God - Overlord                                          06:32

**Comment by rachmadaniHaryono** [comment]
@lol768 and @ids1024 i will close this issue because sorting by time can be done using external program such as vim.

**Comment by duck57** [comment]
What is the vim command to sort a playlist and does it require exporting and re-importing the playlist?

**Comment by anishmittal2020** [comment]
@rachmadaniHaryono  What is the Vim command? Could you please give an example.

**Comment by rachmadaniHaryono** [comment]
`:sor r /\d\d:\d\d$/` 

ping @duck57 @anishmittal2020

**Comment by Agarwal-Nikhil** [comment]
@rachmadaniHaryono Sorry, but I am not sure how to execute this command. `mpsyt` needs a shell in which it can execute. Vim, an editor that has a bottom row where we can insert some commands. 

Then how do we execute the above command. For example if I want to sort the result of the search `mpyst \gilbert  strang`  chronologically. What should I do? Should I execute `mpyst \gilbert  strang`  in a shell and that how do we execute the vim command?

**Comment by anishmittal2020** [comment]
@rachmadaniHaryono Sorry, but I am not sure how to execute this command. mpsyt needs a shell in which it can execute. Vim, an editor that has a bottom row where we can insert some commands.

Then how do we execute the above command. For example if I want to sort the result of the search mpyst \gilbert strang chronologically. What should I do? Should I execute mpyst \gilbert strang in a shell and that how do we execute the vim command?

**Comment by rachmadaniHaryono** [comment]
i just copy the result output to vim and sort it there
