### ISSUE TITLE
Titles are not escaped when subprocess is spawned

### ISSUE THREAD

**Issue by dreadnaut** [mps-youtube/mps-youtube#341]
If a video title contains special shell characters such as `&` or `|`, these will be interpreted by the shell.

Easily reproduced with latest stable on Windows:
- search for "& some-command", for example `/"&notepad"` or `/"& cmd"`
- play any result with a title containing the special character
- a Notepad or Prompt window will open

**Comment by ids1024** [comment]
I think this is a duplicate of #321. If so, the bug is fixed in git (see commit 0b103fc).

**Comment by dreadnaut** [comment]
Indeed it is. Apologies, I searched for existing issues but only among open ones.
