### ISSUE TITLE
New error message started appearing

### ISSUE THREAD

**Issue by Atlantic777** [mps-youtube/mps-youtube#342]
Since I think yesterday I started seeing this error message quite often. I think I'm up to date. It's probably a change in the youtube API or something.

`WARNING:root:Unknown itag: 13 00:00:02`

**Comment by VdeVatman** [comment]
I'm having the same issue, but I'm running the version: `v0.2.6-dev` , so it could be normal. Which is the output of `mpsyt -v | head -n 2` for you?

**Comment by ids1024** [comment]
I can't duplicate this, though I recall seeing that message in the past. Can you pinpoint anything in particular that seems to cause it?

**Comment by VdeVatman** [comment]
@ids1024 My best guess would be that it only happens if there are weird unicode characters in the query's output (querying for users or for keywords/playlist it doesn't matter), but if you repeat the query the warning is ignored. In any case I can't figure out why this happens now and not before.

PS: I downgraded from v0.2.6-dev to v0.2.5 and it is the same.

**Comment by ids1024** [comment]
It seems the code producing that message is in pafy. I have rewritten pafy to pull in youtube_dl as a dependency instead of duplicating the effort, and that code was removed. Thus, this shouldn't be an issue with the git version of pafy.

**Comment by VdeVatman** [comment]
@ids1024 ok, I'm only guessing since I don't know how all this stuff works, but as far as I can see, youtube-dl is filling an unrecognized itag for paffy. Apparently these are the itags supported by paffy:
```
itags = {
        '5': ('320x240', 'flv', "normal", ''),
        '17': ('176x144', '3gp', "normal", ''),
        '18': ('640x360', 'mp4', "normal", ''),
        '22': ('1280x720', 'mp4', "normal", ''),
        '34': ('640x360', 'flv', "normal", ''),
        '35': ('854x480', 'flv', "normal", ''),
        '36': ('320x240', '3gp', "normal", ''),
        '37': ('1920x1080', 'mp4', "normal", ''),
        '38': ('4096x3072', 'mp4', "normal", '4:3 hi-res'),
        '43': ('640x360', 'webm', "normal", ''),
        '44': ('854x480', 'webm', "normal", ''),
        '45': ('1280x720', 'webm', "normal", ''),
        '46': ('1920x1080', 'webm', "normal", ''),
        '82': ('640x360-3D', 'mp4', "normal", ''),
        '83': ('640x480-3D', 'mp4', 'normal', ''),
        '84': ('1280x720-3D', 'mp4', "normal", ''),
        '100': ('640x360-3D', 'webm', "normal", ''),
        '102': ('1280x720-3D', 'webm', "normal", ''),
        '133': ('426x240', 'm4v', 'video', ''),
        '134': ('640x360', 'm4v', 'video', ''),
        '135': ('854x480', 'm4v', 'video', ''),
        '136': ('1280x720', 'm4v', 'video', ''),
        '137': ('1920x1080', 'm4v', 'video', ''),
        '138': ('4096x3072', 'm4v', 'video', ''),
        '139': ('48k', 'm4a', 'audio', ''),
        '140': ('128k', 'm4a', 'audio', ''),
        '141': ('256k', 'm4a', 'audio', ''),
        '160': ('256x144', 'm4v', 'video', ''),
        '167': ('640x480', 'webm', 'video', ''),
        '168': ('854x480', 'webm', 'video', ''),
        '169': ('1280x720', 'webm', 'video', ''),
        '170': ('1920x1080', 'webm', 'video', ''),
        '171': ('128k', 'ogg', 'audio', ''),
        '172': ('192k', 'ogg', 'audio', ''),
        '218': ('854x480', 'webm', 'video', 'VP8'),
        '219': ('854x480', 'webm', 'video', 'VP8'),
        '242': ('360x240', 'webm', 'video', 'VP9'),
        '243': ('480x360', 'webm', 'video', 'VP9'),
        '244': ('640x480', 'webm', 'video', 'VP9 low'),
        '245': ('640x480', 'webm', 'video', 'VP9 med'),
        '246': ('640x480', 'webm', 'video', 'VP9 high'),
        '247': ('720x480', 'webm', 'video', 'VP9'),
        '248': ('1920x1080', 'webm', 'video', 'VP9'),
        '249': ('48k', 'ogg', 'audio', 'Opus'),
        '250': ('56k', 'ogg', 'audio', 'Opus'),
        '251': ('128k', 'ogg', 'audio', 'Opus'),
        '256': ('192k', 'm4a', 'audio', '6-channel'),
        '258': ('320k', 'm4a', 'audio', '6-channel'),
        '264': ('2560x1440', 'm4v', 'video', ''),
        '266': ('3840x2160', 'm4v', 'video', 'AVC'),
        '271': ('1920x1280', 'webm', 'video', 'VP9'),
        '272': ('3414x1080', 'webm', 'video', 'VP9'),
        '278': ('256x144', 'webm', 'video', 'VP9'),
        '298': ('1280x720', 'm4v', 'video', '60fps'),
        '299': ('1920x1080', 'm4v', 'video', '60fps'),
        '302': ('1280x720', 'webm', 'video', 'VP9'),
        '303': ('1920x1080', 'webm', 'video', 'VP9'),
    }
```

And youtube-dl tries to fetch `itag: '13':(...)` for some reason, but I don't know where does that call happen.

**Comment by ids1024** [comment]
@VdeVatman I think you may have misunderstood me. The current release of pafy does not depend on youtube-dl. That is the version that has this issue. The version of pafy in git pulls in youtube-dl as a dependency, replacing much of pafy's code. One of the parts that was replaced was the code printing this warning.

Try installing pafy from the git repo. It should fix this issue.

**Comment by sees-no-colors** [comment]
@ids1024 installing from git fixed it for me, thanks :)
