### ISSUE TITLE
Keys do not work with MPV in Windows

### ISSUE THREAD

**Issue by PureTryOut** [mps-youtube/mps-youtube#345]
I downloaded mps-youtube with Pip using Python 3.4, and downloaded and extracted the newest pre-compiled MPV to the directory with mpsyt. I got the MPV binary from their official site. I'm running Windows 10 (sadly :()

Although mpsyt can play everything perfectly fine with MPV, it refuses to accept any commando's like volume up and down (9 and 0), cancel (q, I have to press Ctrl + C), and time seeking (arrow keys). MPlayer however works fine, but as it can not play every video I sometimes have to resort to MPV (which I prefer anyway). These issues however do not arise when playing a regular video or audio file with MPV itself (without mpsyt).

**Comment by ids1024** [comment]
Does mpv work fine outside of mps-youtube?

**Comment by PureTryOut** [comment]
Yes, no problems at all

**Comment by ids1024** [comment]
It seems to be working for me in my Windows 10 VM. Try using `mpv.com` as the player instead of `mpv.exe`, if that is what you were using.

**Comment by PureTryOut** [comment]
Not sure how to do that. Setting it to just mpv sets it to `mpv.exe`. Removing it (with just `mpv.com` left) outputs "mpv.exe not found". Tried setting it to `mpv.com` but then it crashes with the following:
CreateProcess: The system cannot find the file specified.
```
Traceback (most recent call last):
  File "C:\Python34\Scripts\mpsyt-script.py", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "C:\Python34\lib\site-packages\mps_youtube\main.py", line 4780, in main
    if matchfunction(k, v, userinput):
  File "C:\Python34\lib\site-packages\mps_youtube\main.py", line 4680, in matchfunction
    func(*matches)
  File "C:\Python34\lib\site-packages\mps_youtube\main.py", line 1220, in setconfig
    message = getattr(Config, key.upper()).set(val)
  File "C:\Python34\lib\site-packages\mps_youtube\main.py", line 541, in set
    checked = self.check_fn(value)
  File "C:\Python34\lib\site-packages\mps_youtube\main.py", line 662, in check_player
    g.mpv_version = get_mpv_version(player)
  File "C:\Python34\lib\site-packages\mps_youtube\main.py", line 211, in get_mpv_version
    o = subprocess.check_output([exename, "--version"]).decode()
  File "C:\Python34\lib\subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['mpv.com', '--version']' returned non-zero exit status 1
```

**Comment by ids1024** [comment]
Did you say you deleted mpv.exe? Don't; mpv.com is a wrapper around it, and requires it to be present.

**Comment by PureTryOut** [comment]
No. Like I said, I tried setting it to "mpv.com" (with mpv.exe present) but it crashed with the error I mentioned.

**Comment by ids1024** [comment]
I don't know what the issue is, but you could try running `mpv.com --version` outside of mpsyt to see if you get a useful message. To get a useful error message within mpsyt, `set playerargs --msg-level=all=status` should increase the messages it prints.

**Comment by PureTryOut** [comment]
`mpv.com --version`:
    mpv git-59d44ec (C) 2000-2015 mpv/MPlayer/mplayer2 projects
     built on Mon Aug  3 23:30:56 CEST 2015
    ffmpeg library versions:
     libavutil       54.30.100
     libavcodec      56.57.100
     libavformat     56.40.101
     libswscale      3.1.101
     libavfilter     5.32.100
     libswresample   1.2.101
     ffmpeg version: N-74264-gfb21d32

No idea what changed, but now setting it to `mpv.com` didn't crash it, and the keys work properly.
Thanks for your help, this issue is resolved.
