### ISSUE TITLE
Also, how to install `mpv`?

### ISSUE THREAD

**Issue by IonicaBizau** [mps-youtube/mps-youtube#348]
Sometimes it shows *mplayer doesn't support this stream*–or something like that–and recommends me to use `mpv`.

What is `mpv` and how to install it?

**Comment by IonicaBizau** [comment]
I tried to `sudo apt-get install mpv` on my Raspberry Pi (running Raspbian), but it cannot locate the package.

**Comment by lol768** [comment]
mpv is a movie player based on mplayer and mplayer2.

Consider looking at http://mpv.io/installation/ for more information.

**Comment by IonicaBizau** [comment]
Thanks, @lol768! :cake: I will probably need to build it from source. But btw, will it handle more videos than mplayer does?

**Comment by ids1024** [comment]
Yes, that is what it means by the message. I would also just generally recommend mpv over mplayer, as it has various miscellaneous advantages.

**Comment by sees-no-colors** [comment]
@ids1024 i tried with mpv on mac, maybe it's just me but i wasn't able to play anything at all

**Comment by sees-no-colors** [comment]
@ids1024 back to using mplayer :)

**Comment by IonicaBizau** [comment]
Thanks guys! I will try to build mpv from source and see if it's better than mplayer. :smile:

**Comment by IonicaBizau** [comment]
For posterity: I tried to build it from source but I had problems with that. Ended by doing the following:

```sh
sudo nano /etc/apt/sources.list
```

Replaced: 

```list
deb http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi
```

With

```list
deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi
```

And then:

```sh
sudo apt-get update
sudo apt-get install mpv
```

It brings a bunch of dependencies, but it's working fine. :smile:
