### ISSUE TITLE
Sorry mplayer doesn't support this stream. Use mpv or download it

### ISSUE THREAD

**Issue by dikey94** [mps-youtube/mps-youtube#350]
Just installed the newest version of mps-youtube. When I am trying to play a song I always get "Arctic Monkeys - Do I Wanna Know? (Official Video) : Sorry mplayer doesn't support this stream. Use mpv or download it[1/34>
> WARNING:root:Unknown itag: 13
".

So what i done is:
- download the newest mplayer
- download the newst mpv
- download the newst vlc
- 'set player mplayer'
- 'set player mpv'
- 'set player vlc'

Nothing works.

Is there any solution? Thanks!

**Comment by ids1024** [comment]
The unknown itag message is irrelevant and harmless, and has been fixed in the pafy git. Are you saying you get the message about mplayer not being able to play the stream even when the player is set to mpv or vlc? That would be strange. If not, do you get any message or anything?

**Comment by dikey94** [comment]
![screen](https://cloud.githubusercontent.com/assets/14232224/9870219/55b46802-5b8a-11e5-9325-1f8207cd29a1.png)
This is what I get. Or sometimes "Unknown itag: 13"

**Comment by ids1024** [comment]
Are you saying you get that message after running `set player mpv`? Obviously that wouldn't make sense, as the message is mplayer specific.

As for mplayer, what is the output of `mplayer --version` in the terminal?

**Comment by dikey94** [comment]
Yeah. Before I started mpsyt i've written "set player mpv". This is what i have: 

Arctic Monkeys - Do I Wanna Know? (Official Video) : Sorry mplayer doesn't support this stream. Use mpv or download it                                   [1/12>
> eWARNING:root:Unknown itag: 13


There is:
Unknown option on the command line: --version
Error parsing option on the command line: --version
MPlayer 1.1-4.8 (C) 2000-2012 MPlayer Team
cnt@cnt-dev:~$ 

after "mplayer --version"

Thanks!

**Comment by ids1024** [comment]
don't run `set player mpv` before starting mpsyt. Run it in mpsyt.

**Comment by dikey94** [comment]
Thanks man, this works!

**Comment by agnivade** [comment]
Hi @ids1024 , I am having the same problem with mplayer(Sorry mplayer doesn't support this stream. Use mpv or update mplayer to a newer version). Playing with vlc is fine, but I have a requirement that needs mplayer. I have seen all of the github issues here and still don't have a solution.

Can you help me out here ?

Here is all my debug output -

mpsyt --version
mpsyt version  : 0.2.6-dev 
notes       : development version
pafy version   : 0.3.74
Python version : 3.4.0 (default, Jun 19 2015, 14:20:21) 
[GCC 4.8.2]
Processor      : x86_64
Machine type   : x86_64
Architecture   : 64bit, ELF
Platform       : Linux-3.13.0-24-generic-x86_64-with-Ubuntu-14.04-trusty
sys.stdout.enc : UTF-8
default enc    : utf-8
Config dir     : /home/agniva/.config/mps-youtube
env:TERM       : xterm
env:SHELL      : /bin/bash
env:LANG       : en_US.UTF-8
env:LANGUAGE   : en_US:en

$mplayer | head -2
MPlayer 1.1-4.8 (C) 2000-2012 MPlayer Team
Usage:   mplayer [options] [url|path/]filename

I have installed latest dev branch of mpsyt, latest ubuntu distributed mplayer. But I still have the error.

**Comment by ids1024** [comment]
@agnivade That version of mplayer is too old, as the message says. You need a version newer than the last release. I suggest using mpv instead.

> EDIT: This used to work some time back. Something must have changed recently in youtube APIs or something.

Yes, this observation has already been made, and you are probably correct. The actual issue is that mplayer, until recently, did not support https. It seems youtube is requiring https on more videos.

**Comment by agnivade** [comment]
Hmm ok. Works with mpv. I guess I will leave it at that then. Thanks for the help !
