### ISSUE TITLE
[Bug] Video keep playing if terminal crashes or is closed without first quitting mps-youtube

### ISSUE THREAD

**Issue by OmgImAlexis** [mps-youtube/mps-youtube#353]
I'm not sure if anything can be done about this but I accidently force closed the wrong terminal window and was left with an hour long song playing in the background without any way of stopping it.

**Comment by ids1024** [comment]
Hm, I don't know if there is anything mpsyt can do to prevent that from happening, but you should be able to use `killall mplayer` or `killall mpv` (at least on Linux) to kill the player.

**Comment by OmgImAlexis** [comment]
Is there not a way on relaunch mps-youtube can reattach to the old process so at least it can be stopped?

**Comment by ids1024** [comment]
I can't think of any. When you closed the terminal it did kill mpsyt, but mplayer or mpv (whichever you have configured as a back-end) continued running. I don't know of any way to prevent that, though perhaps there is.
