### ISSUE TITLE
Fantastic program! - but can't see yellow text and can't see how to change it

### ISSUE THREAD

**Issue by philiprhoades** [mps-youtube/mps-youtube#357]
People,

Congratulations on a great program - I love it!  The only thing that needs fixing for me is to change yellow text to black - all the other colours are OK.  I tried setting colours false as a work around - which didn't work but ideally I would just like to change any yellow text to black ATM - I guess I will need to dig into the code?

I will keep looking . .

Thanks again - mpsyt is something I have been wanting since YT started!

Regards,

Phil.

**Comment by philiprhoades** [comment]
I worked out how to change yellow to blue . .

**Comment by ids1024** [comment]
Customizable colors may be a good feature to add.
