### ISSUE TITLE
Not retrieving all my playlists

### ISSUE THREAD

**Issue by philiprhoades** [mps-youtube/mps-youtube#358]
People,

This command:

//"philip rhoades p"

only retrieves 12 of my 30 playlists - is there a bug or am I missing something?

Thanks,
Phil.

**Comment by philiprhoades** [comment]
Hmmm . . 

userpl "philip rhoades p"

works - but to me the "//" command should have worked too?

Thanks.

**Comment by ids1024** [comment]
Perhaps it should get all the results, but it seems this is on youtube's end, not mpsyt.
