### ISSUE TITLE
[Bug] mps-youtube freezes when switching connectivity during playback

### ISSUE THREAD

**Issue by Lesik** [mps-youtube/mps-youtube#359]
If a track is being played, and the host computer switches from LAN to WLAN (or the other way around), mps-youtube freezes and does not respond to any commands. Killing it with `Ctrl + C` fucks up the whole terminal window.

**Comment by ids1024** [comment]
This is probably an issue with the player you have set as a backend (either mpv or mplayer).

**Comment by Lesik** [comment]
@ids1024 Which player is optimally recommended for mps-youtube?

**Comment by ids1024** [comment]
Mpv is generally better.

**Comment by Lesik** [comment]
I am currently using `mpv`. I am running `mps-youtube` 0.2.2.

**Comment by ids1024** [comment]
That mpsyt version is out of date, and a lot of the functionality is broken due to youtube removing the api mpsyt used to use. But that is probably not the cause of this.

**Comment by ids1024** [comment]
I'm not currently seeing this behavior, and the player seems to be terminating fine. Do you still have this problem with the latest release? If so, what operating system are you using?

**Comment by Lesik** [comment]
I am running `community/mps-youtube 0.2.5-2`, which isn't the latest version but it seems like switching LAN/WLAN works now.

Thank you for your work.
