### ISSUE TITLE
[Request] Don't save numbers and hotkeys in the mpsyt search history.

### ISSUE THREAD

**Issue by GijsTimmers** [mps-youtube/mps-youtube#360]
Current situation:

```
$ cat ~/.config/mps-youtube/input_history
/mauro picotto proximus
r1
/barthezz on the move
1
q
/then came you
1
/pursuit of happiness
1
2
q
```

Entries like `1`, `2`, `r1`, `q` are used to indicate what track to play. They end up in the search history (<kbd>Ctrl</kbd> + <kbd>r</kbd>), which makes it harder to find out what tracks I looked up in the past.

Request: don't save these numbers and hotkeys, or create a special command like `history` (currently still available) to show the relevant search history instead.

**Comment by kkrolczyk** [comment]
It could be implemented for example like this:
https://github.com/mps-youtube/mps-youtube/commit/61a6ef173ade1445ecd09041516c050c064fa391
yet, it appears that mpsyt's Config.\<item\>.get in main.py gets default value instead of such that was previously set in config.

**Comment by lol768** [comment]
:+1: to this

**Comment by ids1024** [comment]
> yet, it appears that mpsyt's Config.<item>.get in main.py gets default value instead of such that was previously set in config. 

What? I don't think that can be the case. If it were, none of the settings would do anything. What gives you that impression?

**Comment by kkrolczyk** [comment]
>> yet, it appears that mpsyt's Config..get in main.py gets default value instead of such that was previously set in config.

> What? I don't think that can be the case. If it were, none of the settings would do anything. What gives you that impression?

@ids1024, here is how i had it checked:

0. # this steps are shown in config_test.sh with my output
1. cloned mps-yt to brand new directory,  cd that directory
2. removed old config dir ~/.config/mps-youtube
3. git 'apply'-ied patch history_patch.patch (could have also pulled my fork and switch to branch history_fix, but i wanted to make sure that all's done properly)
4. launched new_directory/mpsyt 
5. used set to check current setting, and next set to change it to searches_only.
6. verified that setting persists ie, it is displayed as being set to proper value in next mpsyt runs
7. verified that code path `elif Config.SAVE_HISTORY.get == "searches_only":` is never taken, always `if Config.SAVE_HISTORY.get == "all":` is executed. Changed config.py default value to searches_only and code path `elif Config.SAVE_HISTORY.get == "searches_only":` was taken. also, take a look at even simplier patch to show this:

8. prepared even simpler test:

 - first, checkout previous patch, ie go back to clean develop branch:
 - `git checkout  mps_youtube/config.py mps_youtube/helptext.py mps_youtube/main.py`
 - `git apply config_test.patch # see diff below`
 - do not remove previous settings. Run mps and check that searches_only is still set to "searches_only" - app should quit with code 99 ( check exit code with `$ echo $?` )
 - comment out return in init_readline - and mpsyt quits with code 100 (assuming "all" as default value as it is in this patch). 

```diff
diff --git a/mps_youtube/config.py b/mps_youtube/config.py
index 3fca9ac..9d2ca8c 100644
--- a/mps_youtube/config.py
+++ b/mps_youtube/config.py
@@ -296,6 +296,8 @@ class _Config(object):
             ConfigItem("ddir", get_default_ddir(), check_fn=check_ddir),
             ConfigItem("overwrite", True),
             ConfigItem("show_video", False),
+            ConfigItem("save_history", "all",
+                allowed_values=["all", "searches_only", "none", ""]),
             ConfigItem("search_music", True),
             ConfigItem("window_pos", "", check_fn=check_win_pos,
                 require_known_player=True),
diff --git a/mps_youtube/main.py b/mps_youtube/main.py
index 181650a..eadcf54 100644
--- a/mps_youtube/main.py
+++ b/mps_youtube/main.py
@@ -383,6 +383,14 @@ command: ENCODER_PATH -i IN -codec:a wmav2 -q:a 0 OUT.EXT"""
 
 def init_readline():
     """ Enable readline for input history. """
+    if Config.SAVE_HISTORY.get == "all":
+        return
+        sys.exit(100)
+    elif Config.SAVE_HISTORY.get == "searches_only":
+        sys.exit(99)
+    else:
+        sys.exit(98)

```

Unfortunately, Github does not allow to attach *.patch files so anyone wanting to check them out needs to strip .txt or adjust above commands accordingly.

[config_test.patch.txt](https://github.com/mps-youtube/mps-youtube/files/31921/config_test.patch.txt)
[config_test.sh.txt](https://github.com/mps-youtube/mps-youtube/files/31920/config_test.sh.txt)
[history.patch.txt](https://github.com/mps-youtube/mps-youtube/files/31922/history.patch.txt)

So, maybe i've done something wrong here, but cant seem to find my mistake.

**Comment by ids1024** [comment]
@kkrolczyk Oh I see. You haven't done anything wrong, it's just that `init_transcode()` is run before the config file is loaded. This is not really necessary, so I changed that in commit 6b1bf1f1d4866f6ade8dc0839fa188bef8195e89. Now it should be possible to get it working.

**Comment by ids1024** [comment]
I'm thinking this might be better implemented by a `history` command, rather than hacking the readline saving code. I'm not sure...

You could also use something like `grep -a ^/ ~/.config/mps-youtube/input_history` to filter the input history.

**Comment by GijsTimmers** [comment]
`history` command implemented. Thank you!
