### ISSUE TITLE
Create playlist from a txt file

### ISSUE THREAD

**Issue by Atlantic777** [mps-youtube/mps-youtube#361]
Hi!

I just managed to add my first feature to mps-youtube. Here's the usecase:

- I have list of songs copied from web into a file or I just enter a list of songs into a file manually.
- I want mpsyt to read that list, search yt and add them to current playlist

At the moment, it's still work in progress and status is "it works for me". Here are some constraints:

- One song per line
- Songs have to be prepended with numbers, like this: `128. some artist - some song`. Numeration will be striped
- No empty lines allowed
- The first match from results list will be used

This feature can be started with `fetch` command, followed by a file path to file containing list of songs. Limit for first n entries can be added, too. Example command:

```
fetch /tmp/songlist.txt 15
```

Code is here: https://github.com/Atlantic777/mps-youtube/commit/dbe78f47ac00e76fc3bcaa7833ea145ff1c20802

You know that it's working something when there is log output after each matched song.

I'm asking you for comments and suggestions. Please, test it, make it crash and share problematic examples. I would like to hear if this usecase is interesting to someone else. It works for me, but I'll try to make it work for you, too.

Here are some things on the *todo* list:
- Appropriate name for this command
- Better striping rule is needed, but I have to think about that a bit more.
- Some kind of song matcher should be used, too. In example. if song length is 60 minutes that's probably a miss. Maybe that filter can be skipped if entry contains word "album"  or something.
- Whole playlist compilation process takes a bit long. Maybe there is a way to trigger multiple search requests in parallel.

Please, share your thoughts on this. Feedback is priceless.

Thanks! :)

**Comment by hrnr** [comment]
According to that this one would be also nice #112

**Comment by Atlantic777** [comment]
Well, I find #112 interesting, too. I'm willing to try to implement it. Let's continue conversation there and be free to contact me on IRC.

**Comment by ids1024** [comment]
#90 is somewhat related.

**Comment by ids1024** [comment]
Implemented in #391
