### ISSUE TITLE
Is it possible to retrieve Youtube private playlists?

### ISSUE THREAD

**Issue by srvanrell** [mps-youtube/mps-youtube#365]
Just wondering, I don't know if this feature should exists at mps-youtube.
Remove this issue (which is not) if this is not the place to ask questions.

Thanks in advance

**Comment by ids1024** [comment]
Well, this would require supporting logging in to youtube, right? If that is implemented for other reasons, certainly this should be added too.

**Comment by srvanrell** [comment]
Other reason may be that YouTube's history would know what have you been listening.
