### ISSUE TITLE
Navigation keys are not working (windows)

### ISSUE THREAD

**Issue by vnckppl** [mps-youtube/mps-youtube#367]
I installed mpsyt for Windows from the binary releases (mpsyt-0.2.5-pafy-0.4.0.exe) and mpv from http://mpv.srsfckn.biz.

The navigation keys (skip (shift + </>), pause (spacebar), and return (q)) are not working when I am playing songs from the terminal window. They do work when from the mpv window (when I show_video is set to True). 

Is there a way to enable these keys in the terminal in windows?

Thanks

**Comment by Wildefyr** [comment]
Are you in powershell or command prompt?

**Comment by vnckppl** [comment]
I am using the binaries. I believe they invoke the command prompt by default (?)

**Comment by lorenzomaieru** [comment]
mpv.exe has some issues with mps, try using mpv.com instead
`set player mpv.com`

**Comment by vnckppl** [comment]
Just tried this out and it worked perfectly. Thank you!
