### ISSUE TITLE
[Feature request] use at TV app

### ISSUE THREAD

**Issue by gtataranni** [mps-youtube/mps-youtube#369]
It would be nice if mpsyt could be used as "TV app" on the computer, so one can send video to play from the android YouTube app

**Comment by gtataranni** [comment]
(Obviously this is a Feature request)

**Comment by lorenzomaieru** [comment]
This would be pretty awesome, but is it even possible? I mean, making it play nice with Youtube's App. Or would this require a custom app?

**Comment by gtataranni** [comment]
It works in browsers from YouTube.com/tv so I guess it's a cookies game.
But I haven't investigated on that

Giovanni Tataranni
Il 30/ott/2015 19:48, "Lorenzo Maieru" <notifications@github.com> ha
scritto:

**Comment by ids1024** [comment]
If there is an api for it, then it should be possible, though some changes to how mpsyt works would be needed.
