### ISSUE TITLE
ERROR: Signature extraction failed: Traceback (most recent call last):

### ISSUE THREAD

**Issue by lakelord** [mps-youtube/mps-youtube#376]
I'm getting this error.....
I've already upgraded mps-youtube, youtube-dl, mplayer....nothing seems to work

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ids1024** [comment]
Do you have the same problem calling youtube-dl directly (which I expect would be the case)? If so, this is probably an issue with youtube-dl, and not mpsyt.

**Comment by ids1024** [comment]
Looks like it is: rg3/youtube-dl#7413

**Comment by yan12125** [comment]
FYI: I managed to fix it in youtube-dl. Please post an issue on youtube-dl if something still goes wrong.

**Comment by lol768** [comment]
I don't think a new version of youtube-dl is released yet, so in the meantime I did. Once done, mps-youtube worked as normally.

```
git clone git@github.com:rg3/youtube-dl.git
cd youtube-dl
make
sudo make install
sudo python3 setup.py install
```

**Comment by yan12125** [comment]
Well a new version (2015.11.10) is released 10 minutes ago.

**Comment by lakelord** [comment]
Works perfectly !!
I appreciate your concern.
I'm no dev....but if you ever need dermatologic council....mail me please.

Thanks man

**Comment by ids1024** [comment]
Another argument in favor of youtube-dl. They have already fixed the issue, while the pafy 0.3.x branch also seems to be broken. Anyone know how to fix it by any chance?

**Comment by kaptoxic** [comment]
Just to confirm that the new version of youtube-dl solved the issue for me.

**Comment by srvanrell** [comment]
Just now I get this same error. Updating mps-youtube was not a solution.
I've solved the problem by removing youtube-dl with apt-get (on ubuntu 14.04) and reinstalling it with pip3 (pip2 didn't work either)

    sudo apt-get remove -y youtube-dl
    sudo pip3 install -U youtube-dl

**Comment by gconsidine** [comment]
Had the same issue and `sudo pip3 install -U youtube-dl` worked for me.  Thanks! :+1:

**Comment by kaptoxic** [comment]
Just to confirm that the error reappeared, but installing the new version of youtube-dl (through aur repo in Arch Linux) solved the issue again.

**Comment by lakelord** [comment]
Olá, mps-youtube/mps-yout.

Gostaria que você fizesse parte da minha rede do LinkedIn para compartilhar atualizações e manter contato.

- Marcelo

Confirme que você conhece Marcelo: https://www.linkedin.com/e/v2?e=0-iidcplq1-9d&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=vYQhoL0O&invitationId=6084024261402517504








Você recebeu um convite de conexão. O LinkedIn utiliza seu endereço de e-mail para fazer sugestões a nossos usuários em recursos como Pessoas que talvez você conheça. Clique aqui para cancelar a inscrição: https://www.linkedin.com/e/v2?e=0-iidcplq1-9d&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGxDk9nKhO1WgAAAVG7L75UPqE4htET5mWnP5T6QsnS6oh1pEjV6nD8D6R_2iaoCkSXzQS3pHA1eqSPLMZuMAZXL8Soo4kE_27JouJA6gSghq9t4vXY5hA3QZlfl4Gsg5T9Xrrz7J7u7bH-gava6hY2fNIzM4B3mMLIQb5bo-3lrebcP2Jrt9M77WycYyWgTVZV&eid=0-iidcplq1-9d


Este e-mail foi enviado para reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iidcplq1-9d&a=customerServiceUrl&ek=invite_guest

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by lakelord** [comment]
Marcelo Ave would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-y9d369-iizpdkom-q9&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=vYQhoL0O&invitationID=6084024261402517504

View Marcelo Ave&#39;s profile: https://www.linkedin.com/e/v2?e=-y9d369-iizpdkom-q9&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=vYQhoL0O&invitationID=6084024261402517504





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-y9d369-iizpdkom-q9&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-y9d369-iizpdkom-q9&loid=AQF7GOWUQB_PFQAAAVINcG-5Nu3PyiNpK3FkPOflX3L50dTsHVXJaAxw4shhAtEFYTt8qmx5M0PUrbTF-lVORs2ZRjD_RJHqTqcL6TzjID9SufzB3z8yCx_RKP-WZpxbNgsbIm5VV3k7hqJa-gDmcIhTCRzJSLrhjwB0YIXH9c_3eGgyJZpSxGUpFRQHrcJP3CsN

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-y9d369-iizpdkom-q9&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by lakelord** [comment]
Marcelo Ave would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-y9d369-ij08rq19-qg&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=vYQhoL0O&invitationID=6084024261402517504

View Marcelo Ave&#39;s profile: https://www.linkedin.com/e/v2?e=-y9d369-ij08rq19-qg&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=vYQhoL0O&invitationID=6084024261402517504





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-y9d369-ij08rq19-qg&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-y9d369-ij08rq19-qg&loid=AQGhS11zM7T_OgAAAVIOfgMhxrMuAlHRGHGfNiKSPQuIzgfjBC87Msc6x81DJlkGtHzjxRFZTNkPxh25KbC-Wm7funzo4FO56A5SljaQNWDw0J72LWUr-l73HvkbuhWxrWXbqlkK6z0xvEInBB4BLnyiOh5m21SA-vebyfq3fltb3dWwdZLsAAjnnfY76D6OLx00

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-y9d369-ij08rq19-qg&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by JonasXPX** [comment]
So, update with `pip install -U youtube-dl` to fix it

**Comment by lakelord** [comment]
I have an issue
 I have configured my  ~/.config/mps-youtube/transcode file as such:

# transcoding presets for mps-youtube
# VERSION 0

# change ENCODER_PATH to the path of ffmpeg / avconv or leave it as auto
# to let mps-youtube attempt to find ffmpeg or avconv
ENCODER_PATH: usr/bin/ffmpeg

# Delete original file after encoding it
# Set to False to keep the original downloaded file
DELETE_ORIGINAL: True

# ENCODING PRESETS

# Encode ogg or m4a to mp3 256k
name: MP3 256k
extension: mp3
valid for: ogg,m4a,webm
command: ENCODER_PATH -i IN -codec:a libmp3lame -b:a 256k OUT.EXT




AND yet....mps-youtube cannot convert webm files to mp3. I'm sure this is
not an issue with ffmpeg......
Can you guys give me a hint ???

Thanks

Marcelo Ave

**Comment by lakelord** [comment]
Hahaha...never mind....I saw now I was not reading the WHOLE file.

**Comment by KevinMcCready** [comment]
ERROR: Signature extraction failed: Traceback (most recent call last):
I purged and reinstalled and still get the error as of now. Version table:
 *** 2016.02.22-1 500

**Comment by ids1024** [comment]
> 2016.02.22-1

That is a rather old version of youtube-dl by now, and probably broken (YouTube changes frequently). You need to upgrade.

**Comment by KevinMcCready** [comment]
Thanks Ian. I try to stick to the repos. I might wait a bit and see if Mint updates it. Meantime, is there another app to do the same?

**Comment by yan12125** [comment]
It's not recommended to use youtube-dl provided in repos, especially Ubuntu and derived distros. Those packages are never updated within a distro version.

mps-youtube should reject too old youtube-dl.
