### ISSUE TITLE
1dbus error and cannot open input file error

### ISSUE THREAD

**Issue by inet-pwnZ** [mps-youtube/mps-youtube#382]
Windows 7, Cygwin, Mintty with xterm256colors and zsh shell
I'm on newst mpsyt version ( 2.5.0 )
I'm on newst windows mpv release

mpsyt on start dbus error :
![](http://i.imgur.com/GNeexfz.png) 
same error as [#337](https://github.com/mps-youtube/mps-youtube/issues/337)

Input file error :
![](http://i.imgur.com/BcAHEls.png)

i can play songs buy i can't use input typs as displayed like lowering volume 9 and 0
it works on mpv standalone though

**Comment by ids1024** [comment]
@hrnr It looks like we need wider error handling in the mpris code.

> i can play songs buy i can't use input typs as displayed like lowering volume 9 and 0
it works on mpv standalone though

This seems to be a separate issue. Does using `set player mpv.com` fix this?

**Comment by inet-pwnZ** [comment]
No, I tryed that before after looking through the issues

**Comment by hrnr** [comment]
@hrnr It looks like we need wider error handling in the mpris code.I will take a look. I have never seen that exception type before.

**Comment by hrnr** [comment]
this has been already fixed in #338. Please close this issue.
