### ISSUE TITLE
dapl keeps responding "Bad syntax"

### ISSUE THREAD

**Issue by srph** [mps-youtube/mps-youtube#387]
```bash
mpsyt
dapl https://www.youtube.com/watch?v=5m8O_Pp6oH4&list=RD5m8O_Pp6oH4
```

Not sure what I'm doing wrong in here. Can anybody point me to the right direction?

**Comment by ids1024** [comment]
What is the output of `mpsyt --version`? It seems to be working for me.

**Comment by ids1024** [comment]
Or, on second thought, I am actually running the git version rather than the last release. The regex for matching playlists was changed in a9fbe156ddcd6622b435cf7cec2f8f0e366e7642 and 0788f9837af6e58e33a2498cd3f0a535ef2c68bf, so try the git version.

**Comment by srph** [comment]
```
mpsyt version  : 0.2.5
   notes       : released 1 June 2015
pafy version   : 0.4.2
Python version : 3.5.0 (default, Sep 23 2015, 04:41:38)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]
Processor      : i386
Machine type   : x86_64
Architecture   : 64bit,
Platform       : Darwin-15.0.0-x86_64-i386-64bit
sys.stdout.enc : UTF-8
default enc    : utf-8
Config dir     : /Users/srph/.config/mps-youtube
env:TERM       : xterm-256color
env:SHELL      : /bin/bash
```

Alright, I'll give it a try.

**Comment by srph** [comment]
Nice! Thanks.
