### ISSUE TITLE
Please add Chromecast/Chromecast audio support

### ISSUE THREAD

**Issue by erkiha** [mps-youtube/mps-youtube#398]
Please add Chromecast/Chromecast audio support. Would be nice to be able to send music to my speakers which are connected to Chromecast audio or to Android TV which is also able to play Chromecast strem

**Comment by GijsTimmers** [comment]
I know that this is not _exactly_ what you're looking for, but you might find it interesting: [castnow](https://github.com/xat/castnow)

**Comment by lol768** [comment]
@GijsTimmers Would `set player castnow` work?

**Comment by ids1024** [comment]
@GijsTimmers That should be helpful. I don't have the time now (finals) but when I do, I'll look at the code for castnow.

**Comment by erkiha** [comment]
There are also python project for this, maybe its possible to make use of this:
https://pypi.python.org/pypi/PyChromecast

**Comment by gipfeli** [comment]
@lol768 Just tested with your suggestion, but only got the youtube logo on screen. If you can specify streaming the MP4 file, I think it will work perfectly.
