### ISSUE TITLE
mps-youtube can't search anything

### ISSUE THREAD

**Issue by rick9791** [mps-youtube/mps-youtube#401]
I always get this message when I try to search:

# Found nothing for pink floyd

**Comment by ids1024** [comment]
What is the output of `mpsyt --version`? You probably need to update it.

**Comment by rick9791** [comment]
0.01.46

**Comment by ids1024** [comment]
That release is broken, due to changes on youtube. Use the latest release.

**Comment by rick9791** [comment]
apparently pip3 was getting an error while installing or updating mps-youtube: 

Installing collected packages: mps-youtube, pafy, youtube-dl
*** Error compiling '/tmp/pip-build-wpphtzcf/mps-youtube/mps_youtube/content.py'...
  File "/tmp/pip-build-wpphtzcf/mps-youtube/mps_youtube/content.py", line 58
    
    ^
SyntaxError: unexpected EOF while parsing

Successfully installed mps-youtube pafy youtube-dl
Cleaning up...

didn't want to bother with it so I downloaded the repository and ran the script from there, now it's working.

**Comment by ids1024** [comment]
Oh, that file wasn't suppose to end up in the distribution. It should be fixed now.

Use `pip3 install --no-cache-dir mps-youtube` and it should install fine.

**Comment by rick9791** [comment]
--no-cache-dir isn't a command on pip3

**Comment by ids1024** [comment]
In that case you are running an older version of pip3 than me.

Does it work without that argument?

**Comment by rick9791** [comment]
yeah it does, thanks

**Comment by ids1024** [comment]
If it is working now, you can close the issue.
