### ISSUE TITLE
Is it normal that mpsyoutube plays music in low quality?

### ISSUE THREAD

**Issue by zunjae** [mps-youtube/mps-youtube#403]
Every song I play plays in 50k webm (61kbps bitrate http://i.imgur.com/hDzFaWU.png)
while youtube-dl -F shows m4a at around 255kbps bitrate http://i.imgur.com/kbYbUaA.png)

if necessary, here is my config: http://i.imgur.com/SVkD5rv.png

**Comment by ids1024** [comment]
Are you running the latest version?

**Comment by ids1024** [comment]
Closing, since it should be fixed already. Reopen if it is not.
