### ISSUE TITLE
mps-youtube and VPNs

### ISSUE THREAD

**Issue by esn89** [mps-youtube/mps-youtube#404]
Possible to route mps-youtube via openvpn?

I'm located in a country that blocks quite a bulk of the music that I search up and recently I installed openvpn and connected to a vpn that is located back in my home country (where I know that music I am used to listening to, work).
With the openvpn up and running my mps-youtube still doesn't seem to be able to play videos and says that the country that I am in doesn't allow it.

Is there a unique way or a workaround to get mps-youtube to work with a vpn?

**Comment by lol768** [comment]
mps-youtube works okay with my OpenVPN profile active. I can search and play videos. The VPN server is located in the UK.

**Comment by esn89** [comment]
did you have to do any settings in the VPN?

At the moment, I just did `sudo service openvpn start' on the whole system, but that doesn't seem to work.  Do you do the same?

**Comment by lol768** [comment]
No, my steps to set-up the VPN are:

* `sudo openvpn ~/file.ovpn`
* Enter username
* Enter password
* Wait whilst connection is established
* Start mps-youtube

**Comment by esn89** [comment]
hmm, that's the exact same thing i do, except my mps-youtube is still not behaving like it should.

did you have to make any changes to mpsyt?

**Comment by snow3461** [comment]
sorry if i'm mistaken, but from my knowledge,

    sudo service openvpn start

is starting the openvpn daemon, a.k.a the server, by default, whereas

    sudo openvpn ~/file.ovpn

launch openvpn in client mode and initiate connection to your openvpn server of choice (configured in the .ovpn file).

Did you check your IP address, does it match your home country?

**Comment by lol768** [comment]
> did you have to make any changes to mpsyt?

No.

@snow3461 is correct. Check `curl http://httpbin.org/ip` *after* starting the VPN and compare it to your normal IP address. If the result is the same, there's an issue with your VPN.
