### ISSUE TITLE
'sw' command broken

### ISSUE THREAD

**Issue by gitsper** [mps-youtube/mps-youtube#407]
On the develop branch I noticed that swapping playlist items crashes the program since the `Playlist` class doesn't support item assignment.  I plan to fix this by adding a `__setitem__(...)` to the class in `playlist.py` as follows:

<pre>
  <code class="python">
def __setitem__(self, position, item):
        self.songs[position] = item
  </code>
</pre>

Is this an adequate solution?

**Comment by ids1024** [comment]
Oops, I guess I broke that. Fixed.
