### ISSUE TITLE
[Request] Create an option not to make mpsyt show up in the MPRIS menu every time.

### ISSUE THREAD

**Issue by GijsTimmers** [mps-youtube/mps-youtube#408]
Hi,

I for one don't really like `mpsyt` sitting in the Ubuntu Sound Menu. Usually, when I don't like players showing up there, I disable them by typing:

```
$ gsettings set com.canonical.indicator.sound interested-media-players "['list', 'of', 'desired', 'music', 'players']"
```

But for some reason, `mps-youtube doesn't 'respect' this. When I start mps-youtube again, it will show up in the Ubuntu Sound Menu again.

Request: make it an option.

**Comment by hrnr** [comment]
Hi,

This sounds reasonable to me. But using gnome settings is imho too complex, since we don't use it for anything else.

Would it be ok for your needs, if this was implemented as option inside mpsyt?

I could look at it next week.

**Comment by GijsTimmers** [comment]
Yes, sure. Doesn't even need to be in the settings. A True/False switch in
a file would be fine for me, too.

Op zo 10 jan. 2016 13:17 schreef Jiri Horner <notifications@github.com>:

**Comment by ids1024** [comment]
It is strange; I would expect gnome handles this without needing specific code in the client, so I don't know why it would be a problem.

@GijsTimmers Does adding `mps-youtube` to `blacklisted-media-players` work? I don't have Gnome installed, so I can't test it.

**Comment by GijsTimmers** [comment]
I didn't know about that option. I just added `'mps-youtube.desktop'` to `blacklisted-media-players` and removed it from `interested-media-players`. Then, I rebooted, and mps-youtube was gone from the panel. But after playing a video with `mps-youtube`, it added itself to the menu again.

Currently, `blacklisted-media-players` still contains `'mps-youtube.desktop'`. But it also added itself to `interested-media-players`. So  `interested-media-players` seems to override whatever's in `blacklisted-media-players`.

**Comment by ids1024** [comment]
Hm, odd, because I believe it is supposed to be the other way around: `blacklisted-media-players` overrides `interested-media-players`.

**Comment by hrnr** [comment]
I think the problem here might be that we have different bus name each run.  we put `org.mpris.MediaPlayer2.' + IDENTITY + '.instance' + str(os.getpid())` there.

It then thinks of us as a new player and add association for our desktop file everywhere. And by default new associations are visible.

You may try modify above line and check of it still overides your config on every run.

**Comment by ids1024** [comment]
@hrnr Hm, maybe, but if I recall correctly, the mpris2 documentation specifically said to do that if the program can have several simultaneous instances. So it shouldn't cause any problem...
