### ISSUE TITLE
very different results from mps and web

### ISSUE THREAD

**Issue by khoroshyy** [mps-youtube/mps-youtube#409]
Hi,
If i search in mpsyt: mailx command line 
I get 2 hits, which are very far from what I need.
If I repeat it in web interface I have correct result.
And in general searches from mpsyt are much worse than from web interface.

Any comments?

**Comment by ids1024** [comment]
By default mpsyt only searches the music category. Use `set search_music False` to change that.

**Comment by khoroshyy** [comment]
Thanks, works perfectly.
