### ISSUE TITLE
LICENSE, CHANGELOG, and README installed in wrong location

### ISSUE THREAD

**Issue by kyrias** [mps-youtube/mps-youtube#412]
d5084c79ff4964f970e527b55d8955dac012419b causes the `LICENSE`, `CHANGELOG`, and `README.rst` files to be installed to the to `/usr/LICENSE` et.c. with `setup.py install`.

**Comment by ids1024** [comment]
Oops, that clearly is wrong.

So, I guess it would be best to put those files in `/usr/share/mps-youtube`? I'll have to see what that ends up doing on windows systems as well...

**Comment by kyrias** [comment]
That's generally where they go on Linux systems, yeah.
