### ISSUE TITLE
crash when using user command in the latest version upgraded with pip3

### ISSUE THREAD

**Issue by jiang-qian** [mps-youtube/mps-youtube#413]
mps-youtube is a great program! Thank you for providing such a useful service to youtubers who dislike ads!

However, after upgrading to the latest version of mps-youtube, pafy and youtube-dl via pip3, mps-youtube predictably crash: search for a term, for example snl. Then do "u 1" to search for the videos uploaded by user of the 1st entry.

I'm running ubuntu 14.04 64-bit. The crash error messages are:

Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.6', 'console_scripts', 'mpsyt')()
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 3695, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 3644, in matchfunction
    func(*matches)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2991, in user_more
    usersearch_id('/'.join([user, channel_id, '']), 0, True)
TypeError: usersearch_id() takes 1 positional argument but 3 were given

**Comment by jiang-qian** [comment]
I just downloaded the latest zip from the website and it seems to have fixed this.

**Comment by ids1024** [comment]
By the "latest zip from the website" do you mean a snapshot of the develop branch?

**Comment by jiang-qian** [comment]
Yes, I downloaded it from the github front page so I assume it is the
developmental snapshot.
https://github.com/mps-youtube/mps-youtube

**Comment by MaxPleaner** [comment]
out of curiosity is there a reason this fix isn't pushed to the pip repo?

**Comment by ids1024** [comment]
@MaxPleaner Just because a new version hasn't been released yet (it would be good to do a release).
