### ISSUE TITLE
a lot of songs not playing..

### ISSUE THREAD

**Issue by dimitrieh** [mps-youtube/mps-youtube#416]
getting the following:

it just not plays the song/skips it

or 

Exception in thread Thread-19:; 00:00:00 [0%]   [>                                                                                                                                                      ]
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(_self._args, *_self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/mps_youtube/main.py", line 2480, in _preload
    g.streams[ytid], audio=False)
  File "/usr/local/lib/python3.5/site-packages/mps_youtube/streams.py", line 115, in select
    ret = streams[q]
TypeError: list indices must be integers or slices, not dict

what would the the error?

**Comment by ids1024** [comment]
Sorry for the late response. What video are you getting this behavior on?

**Comment by ids1024** [comment]
I think I found the problem, and a solution: https://github.com/mps-youtube/mps-youtube/commit/d0dd2767dc76a43dfd4fd76605519b069d231ea8

**Comment by strages** [comment]
Nice thanks

More video's are playing correctly I believe now.

however the following video doesn't

playurl https://www.youtube.com/watch?v=-OWN1jSLPFo

**Comment by ids1024** [comment]
That video seems to work for me. What error do you get?

**Comment by strages** [comment]
mmh strange, now I am wondering if I am on the correct version. if i do

`[sudo] pip3 install mps-youtube --upgrade`

are those fixes included or do i need to compile myself?


btw i do not get an error, it doesn't play, then just does asif it has
played all the songs in the playlist, this case 1 song

On Sun, Jan 31, 2016 at 9:03 PM Ian D. Scott <notifications@github.com>
wrote:

> That video seems to work for me. What error do you get?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mps-youtube/mps-youtube/issues/416#issuecomment-177597843>
> .
>
-- 
--

*Dimitrie Hoekstra, UI & Interaction Designer*
dhesign.com  | dimitriehoekstra@gmail.com | LinkedIn
<https://www.linkedin.com/in/dimitrieh> | Twitter
<https://twitter.com/strages33/>

**Comment by ids1024** [comment]
The fix hasn't been released yet.

Use `sudo pip3 install --upgrade https://github.com/mps-youtube/mps-youtube/archive/develop.zip` to install the git version.

**Comment by strages** [comment]
updated with that command, same result though...

**Comment by strages** [comment]
can i produce a log of what happens?

**Comment by ids1024** [comment]
Are you using mpv or mplayer? If it is mpv, you can try using `set playerargs --msg-level=all=status` to get debugging information.

**Comment by o175** [comment]
The first part of this problem is still here after the fix. ~50% of songs are not playable with mplayer.
[video](https://player.vimeo.com/video/160430516)
mplayer version: 2.0-728-g2c378c7-4build1    (i386)
If player is set to mpv everything is working.
How could I help you to solve this problem? I like mplayer and it would be nice if I could use it.

**Comment by linuxbandit** [comment]
I am having issues also, playing just the audio.

Searching for a song, on selection of the video, the content is fetched but then it returns directly to the result list

**Comment by ids1024** [comment]
@linuxbandit What player are you using? What is the full output of `mpsyt --version`?

**Comment by linuxbandit** [comment]
$ mpsyt --version

mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.1 (youtube-dl backend)
youtube-dl version : 2016.08.01
Python version     : 3.5.2 (default, Jul 28 2016, 21:28:00)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
Processor          : i386
Machine type       : x86_64
Architecture       : 64bit,
Platform           : Darwin-15.6.0-x86_64-i386-64bit
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /Users/fbe/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_IE.UTF-8

(styling sucked, so no markdown)

**Comment by ids1024** [comment]
The versions there look up-to-date...

@linuxbandit What player are you using (the supported ones are mpv and mplayer)?

**Comment by linuxbandit** [comment]
Pardon me, I have left that info out.. I have mplayer installed, no mpv is present.
If useful at all, I installed python3 and pip3 with brew on a mac, not sure if mplayer was already there (mac n00b here) or came with brew/pip

**Comment by ids1024** [comment]
You might want to try using mpv instead. It is generally more reliable.

**Comment by linuxbandit** [comment]
sorry I forgot to thank you!
