### ISSUE TITLE
Adding -w, -f or -a results in 'Bad syntax'.

### ISSUE THREAD

**Issue by Wildefyr** [mps-youtube/mps-youtube#420]
Seems to be caused by 904408b6504771ae594cef55c086fef1a7b63e6e, reverting to a commit previously and there is no issue.

**Comment by ids1024** [comment]
Fixed in d9fcda2814170f1fcb2c819a88770c49919c8f8b.

**Comment by Wildefyr** [comment]
Confirmed fixed!
