### ISSUE TITLE
Broken video playback???

### ISSUE THREAD

**Issue by sotlampr** [mps-youtube/mps-youtube#421]
Using the latest mps-youtube with the latest youtube-dl,
config: all defaults, set_video True

When trying to play any video it gives the following error:

      File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 2166, in _preload
          stream = streams.select(streams.get(song), audio=not video, m4a_ok=m4a)
      File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 99, in select
          streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
      File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 99, in <listcomp>
         streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
      File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 83, in okres
          return int(x['quality'].split("x")[1]) <= maxres

    IndexError: list index out of range

In [streams.py L99](https://github.com/mps-youtube/mps-youtube/blob/develop/mps_youtube/streams.py#L99) when using the okres to test the resolution it gets passed an audio resolution (ex. '92k'), so '92k'.split('x')[1] returns the error above.

Does this have to do with changes in youtube? I noticed that downloading any video requires muxing with audio. Is it safe to guess that youtube changed the way of delivering content and you're catching up?

Thanks,
S.

**Comment by ids1024** [comment]
This is not happening for me.

What version of pafy do you have?

**Comment by sotlampr** [comment]
pafy==0.4.3-1
I need to say also that downloading works.

**Comment by ids1024** [comment]
I still can't reproduce this, on Archlinux with the same mpsyt and pafy versions.

Are you sure this is happening for all videos, and not only some? I can't think of any reason for this to happen...

**Comment by sotlampr** [comment]
Issue solved by itself, I don't know why but for a couple of days all ''normal'' videos were missing. Seems ok now.
Thanks!
