### ISSUE TITLE
Disabling 'instance pid' in the name (dbus/mpris)?

### ISSUE THREAD

**Issue by spcmd** [mps-youtube/mps-youtube#426]
Is there a way to remove the _instance_+_pid_ string from the name (dbus)? Or disable this feature with a setting or a command line option?

So instead of _mps-youtube.instance5410_ it would be only _mps-youtube_

Reason: I'd like to control the player with key bindings or a script, but the name always changes, so it makes difficult to target mps-youtube via dbus. I don't run multiple instances, so I don't need the unique identifier.

**Comment by hrnr** [comment]
You can edit it out it under `mps_youtube/mpris.py`. However I think it is not necessary, you can probably do much better with some dbus scripting.

Would 

```
dbus-send --session           \
  --dest=org.freedesktop.DBus \
  --type=method_call          \
  --print-reply=literal       \
  /org/freedesktop/DBus       \
  org.freedesktop.DBus.ListNames |
  tr ' ' '\n' |
  grep 'org.mpris.MediaPlayer2.mps-youtube' | 
  head -n 1
```

work for you?

You might also find useful [mprisctl](https://gist.github.com/hrnr/43d926875577f6c3fd70) and [playerctl](https://github.com/acrisci/playerctl)

Cheers,
Jiri

**Comment by spcmd** [comment]
**hrnr**: it's working, thank you! Even so I think the instance naming should be optional. I believe editing the mpris.py would be a temporary solution anyway because after an update it would be the default again. That's why I suggested a setting or a command line option for this.

But I'm okay with this dbus command, thanks again!

**Comment by hrnr** [comment]
I'd like to clarify why we are adding PID to bus name. It's nothing mps-youtube has invented by itself. It's recommended by [mpris specification](http://specifications.freedesktop.org/mpris-spec/latest/).

IMHO we don't need to take any action here.

**Comment by spcmd** [comment]
Okay, I understand now. No problem, I'll use that dbus command.
