### ISSUE TITLE
listIndex error out of range on 'normal' videos with bitrate based quality instead of HxW format

### ISSUE THREAD

**Issue by fprintf** [mps-youtube/mps-youtube#427]
streams.py tries to split the quality returned by 'x'. This fails with exceptions if the quality is something like '128k' which is quite common for the 'normal' type videos that are mp4 based (they're rated by bitrate instead of aspect ratio/dimensions)

This breaks 'maxres' and getq() tests in streams.py for checking the max resolution and the width fetching for sorting.

This requires a different setting for max bitrate as well as max resolution. So you need to add a 'max bitrate' setting and test that value when a 'k' is found in the quality. For now I have patched my own copy of mpsyt with that idea.

**Comment by ids1024** [comment]
Is this the same issue as https://github.com/mps-youtube/mps-youtube/issues/422? If so, it was a bug in pafy and is fixed in pafy git.

**Comment by fprintf** [comment]
Yes  it seems to be the same issue. Thanks
