### ISSUE TITLE
Mps youtube doesn't handle network outages

### ISSUE THREAD

**Issue by agnivade** [mps-youtube/mps-youtube#429]
Hi,

First of all, just wanted to say thanks for the awesome work on this tool ! I have built my own app (https://github.com/agnivade/youremote) on top of this and it works beautifully.

I noticed that if internet gets disconnected and then gets reconnected after some time, the song doesn't resume playing. I know the youtube player also doesn't handle re-connectivity, but just wanted to know if there is something that can be done about this.

**Comment by ids1024** [comment]
I think the issue here is with mpv/mplayer rather than mpsyt.
