### ISSUE TITLE
Possible to download FullHd with the sound?

### ISSUE THREAD

**Issue by vitaliy1919** [mps-youtube/mps-youtube#431]
I am trying to download a video in 4k quality. There are possibilities, that I can choose, in the image.
![image](https://cloud.githubusercontent.com/assets/14332049/12923220/8f39873c-cf5d-11e5-9324-251ade58f952.png)
It seems that I can’t download FullHD video with sound. Are there any options to do that?

**Comment by ids1024** [comment]
Select the video only stream, and it should ask you about muxing in audio.

**Comment by vitaliy1919** [comment]
When I choose the video only stream, it will begin to download without any questions.

**Comment by ids1024** [comment]
That should be fixed in git.
