### ISSUE TITLE
[Feature Request] Repeat X time

### ISSUE THREAD

**Issue by Sandlayth** [mps-youtube/mps-youtube#437]
Add an optionnal option to repeat in order to repeat X time a song.
Example : I want to repeat 3 times the first video, twice the second, and 5 the 20th one.
I just type:
``repeat 1[3] 2[2] 20[5]``
 instead of 
`` repeat 1 1 1 2 2 20 20 20 20 20``

**Comment by ids1024** [comment]
This has been implemented in #490.
