### ISSUE TITLE
Search results more than one same item 

### ISSUE THREAD

**Issue by spvkgn** [mps-youtube/mps-youtube#440]
Looks like a bug.  mpsyt+pafy from develop branch.

![-mpsyt](https://cloud.githubusercontent.com/assets/4147135/13194716/0022c28e-d7be-11e5-8d7e-cb9373e153db.png)

```
mpsyt version  : 0.2.6
   notes       : released 1 January 2016
pafy version   : 0.4.3
Python version : 3.2.3 (default, Jun 18 2015, 21:46:42) 
[GCC 4.6.3]
Processor      : i686
Machine type   : i686
Architecture   : 32bit, ELF
Platform       : Linux-3.13.0-77-generic-i686-with-LinuxMint-13-maya
sys.stdout.enc : UTF-8
default enc    : utf-8
Config dir     : /home/pavel/.config/mps-youtube
env:TERM       : screen-256color
env:SHELL      : /bin/bash
env:LANG       : ru_RU.UTF-8
--
```

**Comment by ids1024** [comment]
Could you post a plain text version of the search term so I can try to duplicate the bug?

**Comment by spvkgn** [comment]
> михалков ельцин 1996

**Comment by ids1024** [comment]
It doesn't seem to be happening for me...

Does this happen for all searches, or just some? Does running the `clearcache` command change anything?

**Comment by spvkgn** [comment]
Clearing cache doesn't. This occurs with many searches, for instance this search results of 4 items  displayed more than one as well:

![mpsyt](https://cloud.githubusercontent.com/assets/4147135/13201156/7f80dfba-d887-11e5-97f2-e368ce6fa02a.png)
