### ISSUE TITLE
Listing videos from specified uploader issue

### ISSUE THREAD

**Issue by spvkgn** [mps-youtube/mps-youtube#441]
With `user 112Ukraine` mpsyt should be listed videos from [this](https://www.youtube.com/user/112Ukraine) uploader.
Instead of this mpsyt shows videos from [other](https://www.youtube.com/channel/UC-l6fZMH7JLumIR-9o7xrQg) channel.
Can anyone confirm this?

**Comment by ids1024** [comment]
I get the same behavior. This is odd.
