### ISSUE TITLE
[Feature] Auto-numbering items when download a playlist

### ISSUE THREAD

**Issue by n2i** [mps-youtube/mps-youtube#446]
What about new feature that help to add a prefix to file name with the customize auto-numbering pattern, such as 01 then 02 and so on, the predefined lenght of digits.

Ex:
- 01 - Video abc.mp4
- 02 - Video def.mp4

**Comment by Vrihub** [comment]
+1 for this! :)

Moreover, also considering #450, I'm wondering if there is a way to leverage on the existing `youtube-dl` code, which allows great flexibility in customizing the downloaded filename format. 

I'm sorry I don't know the mpsyt internals and I am not so fluent in python, but maybe you could "embed" youtube-dl as described at https://github.com/rg3/youtube-dl/#embedding-youtube-dl
Is this feasible?
