### ISSUE TITLE
Problem with using mps-youtube as a frontend to an mpv control script.

### ISSUE THREAD

**Issue by Wildefyr** [mps-youtube/mps-youtube#449]
Hey, I've written an [mpc-like](https://github.com/wildefyr/mpvc) control script for use with mpv. It uses mpv's `--input-unix-socket` to send commands to an mpv instance started with it. I've so far attempted putting `--input-unix-socket` into playerargs but this seems to have no effect at all. 

The other option I have tried is setting player to my script `mpvc` and playerargs to `add` which adds the the arg given by mps-youtube (a really long URL, given by google's API). The issue with this is that mps-youtube or the API fails to send me a URL at all in most videos I have tried it on. This is especially annoying as mpv can take a normal youtube URL and play it just fine.

A solution to either one would be a dream as I could use mps-youtube purely as a frontend to adding tracks, then closing it completely while keeping the mpv instance it starts running.

**Comment by ids1024** [comment]
The problem with the first method is that mpsyt uses `--input-unix-socket` itself.

Your second solution sounds better, but I don't quite understand what problem you are having with it.

**Comment by Wildefyr** [comment]
[mps-youtube just fails to add the track](http://wildefyr.net/media/mps-yt.mp4)

**Comment by ids1024** [comment]
I don't know. Is it specific videos that consistently don't work? Is it working fine when you have the player set to `mpv` instead of your script?

**Comment by Wildefyr** [comment]
Yes, specific videos will work fine, but the majority do not. Using mpv as the only arg works consistently.

**Comment by ids1024** [comment]
Oh, if the script has mpv in its name, mpsyt may be treating it as through it was mpv, and giving it some undesired arguments. You could see if it behaves differently if the script is given a different name. If it is not that, then I don't know what...

**Comment by Wildefyr** [comment]
No luck there. Somewhere in mpsyt or the google API it won't provide the URL to the external script.

**Comment by ids1024** [comment]
Well, it can't be the google API, since it is passing the url just fine if mpv is used as a player.

What happens if you replace the script with one that just writes the url to a file? If that works, it may be an issue with your script.
