### ISSUE TITLE
Playback time formatting issue

### ISSUE THREAD

**Issue by spvkgn** [mps-youtube/mps-youtube#452]
Playback time from 60 up to 99 minutes still shows in minutes instead of next hour with minutes at 00.

![1](https://cloud.githubusercontent.com/assets/4147135/13524521/7eefcc2e-e21d-11e5-8066-15515c063d1a.png)

This looks like a bug.

**Comment by ids1024** [comment]
It appears to be intentional: https://github.com/mps-youtube/mps-youtube/blob/6b002d567a64e1559fd6adcf2e168c3648e32b20/mps_youtube/main.py#L369

I'm not quite sure why...
