### ISSUE TITLE
ffmpeg httpproxy not in whitelist

### ISSUE THREAD

**Issue by srvanrell** [mps-youtube/mps-youtube#457]
I get the following with some songs

`[ffmpeg] httpproxy: Protocol not on whitelist 'http,https,tls,rtp,tcp,udp,crypto'!`
`[stream] Failed to open https://VERY_LONG_URL`

Is there any way to add httpproxy to the whitelist? or do you know any workaround?

**Comment by ids1024** [comment]
This is not something mps-youtube can control; that is the player (mpv/mplayer) and ffmpeg.

**Comment by congni** [comment]
Do you solve？i have same problem

**Comment by ids1024** [comment]
@congni What operating system/disto are you running?
