### ISSUE TITLE
Playlist error

### ISSUE THREAD

**Issue by VexillePC** [mps-youtube/mps-youtube#459]
Hey! I have a little problem. 
If i wanna play my playlist, i get this image. Can anybody help to me?
[https://p1.picsto.re/3SsWV.png](https://p1.picsto.re/3SsWV.png)

**Comment by ids1024** [comment]
Duplicate of  #444. It should be fixed by using the latest pafy version, with the youtube-dl backend (enabled by default if youtube-dl is installed).

**Comment by VexillePC** [comment]
I'm using the latest pafy version :(

**Comment by ids1024** [comment]
Do you have youtube-dl installed?

**Comment by VexillePC** [comment]
youtube-dl? where can i find it?

**Comment by ids1024** [comment]
`pip install youtube_dl`

**Comment by VexillePC** [comment]
I do something wrong?
[https://p1.picsto.re/iAQCg.png](https://p1.picsto.re/iAQCg.png)

**Comment by ids1024** [comment]
I don't quite understand what you did. Did you install `youtube_dl` with pip?

**Comment by VexillePC** [comment]
oh i installed with windows terminal (cmd)

**Comment by ids1024** [comment]
You shouldn't be trying to execute `backend_youtube_dl` as a script. It is not one.

You need to run the command `pip install youtube_dl` in the terminal, or otherwise install the module.

**Comment by VexillePC** [comment]
I give up
I'm stupid for that. :-/
