### ISSUE TITLE
Pyperclip support broke - Attribute not found.

### ISSUE THREAD

**Issue by orbea** [mps-youtube/mps-youtube#461]
I tried to copy a youtube link to the clipboard with pyperclip in mps-youtube and found the feature stopped working. Maybe something youtube changed?

os: Slackware64-current

mps-youtube-3d86b5b_2016.03.12_develop-x86_64-1_git
pafy-c8f3ba2_2016.03.13_develop-x86_64-1_git
pyperclip-1.5.26-x86_64-1_SBo
youtube-dl-2016.03.14-x86_64-1_SBo
```
> x 1
https://youtube.com/watch?v=ofwaYtDvdOI
Error - couldn't copy to clipboard.
Attribute not found.
```

**Comment by ids1024** [comment]
I get the same behavior. Commenting out the error catching code results in this:

> AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183

`gobject` is imported in pyperclip and the `from gi.repository import GObject` line is in mpsyt's `mpris.py`. Now to figure out how to solve this...

**Comment by ids1024** [comment]
Fixed in dbd0a983f461dc9e70e96f2d0df1e0d00fe75653.

**Comment by orbea** [comment]
Thanks! I can confirm this fixed it for me too.

**Comment by iainrs** [comment]
I'm running Linux Mint 18 xfce with python 2.7 and have installed pyperclip 1.5.27.
when running 
`pyperclip.copy(text)`
I get the attribute error as described above.
Is there a later version to download ?

**Comment by orbea** [comment]
My guess is that you need to update your mps-youtube.

I can confirm its still working for me with.
`mps-youtube-2017.04.14_48787b1_develop-x86_64-1_git`
`pyperclip-1.5.27-x86_64-1_SBo`
