### ISSUE TITLE
mpv playback controls do not work 

### ISSUE THREAD

**Issue by Hoenn** [mps-youtube/mps-youtube#465]
I'm getting started with mps-youtube today with windows 8.1 command prompt and I can't seem to get any functioning keys aside from Ctrl-C when using `set player mpv` and playing a track (no video). A similar issue #345  was closed but I don't have any success when running `set player mpv.com` as is discussed in #345 , I get the error `Player application mpv.com not found` . ( I've tried using mplayer as well but even using the newest version I still get the error `Sorry mplayer doesn't support this stream...`)

here is my mpsyt --version output:
mpsyt version  : 0.2.6
   notes       : released 1 January 2016
pafy version   : 0.4.3
Python version : 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)]
Processor      : AMD64 Family 18 Model 1 Stepping 0, AuthenticAMD
Machine type   : AMD64
Architecture   : 32bit, WindowsPE
Platform       : Windows-8-6.2.9200
sys.stdout.enc : cp1252
default enc    : utf-8
Config dir     : C:\Users\Evan\AppData\Roaming\mps-youtube

Here is mpv --version
mpv 0.15.0-git-2a8bbee (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Mon Jan 18 14:52:12 CET 2016
ffmpeg library versions:
   libavutil       55.13.100
   libavcodec      57.22.100
   libavformat     57.21.101
   libswscale      4.0.100
   libavfilter     6.25.100
   libswresample   2.0.101
ffmpeg version: N-77911-g9cdc23e

**Comment by ids1024** [comment]
How did you install mpv? There should be an `mpv.com` file included in the download.

**Comment by Hoenn** [comment]
It was in the download, didn't realize it was MS-DOS application. I'll try the command again when I get back on my pc

**Comment by Hoenn** [comment]
Yep, after figuring out which file was mpv.com and moving that to my Scripts folder I was able to set it properly. That's what I get for not having file extensions visible! Thank you.
