### ISSUE TITLE
Select default audio format + quality in config | Feature request

### ISSUE THREAD

**Issue by nishanthkarthik** [mps-youtube/mps-youtube#466]
Currently, `mpsyt` opens `webm` for some links and `m4a` for others. Can we have an option in set option to select default format and quality?

It would be wonderful when this happens :)

**Comment by ids1024** [comment]
Selecting the format has been requested before: #71 
It's shouldn't be hard to implement... feel free to implement it and send a PR.

As for quality, you can set the maximum resolution for video playback with `set max_res`. For audio it just uses the highest bitrate. I suppose a `max_bitrate` setting could be added too... Though it seems much less useful that `max_res`.

**Comment by nishanthkarthik** [comment]
Thanks @ids1024 
This is my first contribution to a large scale open source project :)
