### ISSUE TITLE
Why not use WEBM audio-only OGG 128K?

### ISSUE THREAD

**Issue by edouard-lopez** [mps-youtube/mps-youtube#476]
I'm listening to [Chopin - Variations on "Là ci darem la mano" from Mozart's Don Giovanni](https://www.youtube.com/watch?v=8dbGJJrshoU) using mps-youtube and I see it's using a `m4a`+`256Kb` stream source:

```
8dbGJJrshoU; m4a 256k; 33 Mb; 00:00:08 [1%]   
```
### Smaller source

However using [YouTube Video and Audio Downloader](https://addons.mozilla.org/en-US/firefox/addon/youtube-video-and-audio-dow/) addons I can see there is a –twice– smaller source file (bottom right).

![smaller file source](http://pix.toile-libre.org/upload/original/1461320861.png)
### Settings

Here is my `mps-youtube` config:

```
  Key                 Value
  order             : relevance
  user_order        :
  max_res           : 240p
  player            : mpv
  playerargs        :
  encoder           : 0 [None]
  notifier          :
  checkupdate       : True
  show_mplayer_keys : True
  fullscreen        : False
  show_status       : True
  columns           : rating date category
  ddir              : /home/elopez/Downloads/mps
  overwrite         : True
  show_video        : False
  search_music      : True
  window_pos        :
  window_size       :
  download_command  :
```
#### MPSYT

```
$ mpsyt --version
mpsyt version  : 0.2.6
   notes       : released 1 January 2016
pafy version   : 0.4.3
Python version : 3.4.3+ (default, Oct 14 2015, 16:03:50)
[GCC 5.2.1 20151010]
Processor      : x86_64
Machine type   : x86_64
Architecture   : 64bit, ELF
Platform       : Linux-4.2.0-35-generic-x86_64-with-Ubuntu-15.10-wily
sys.stdout.enc : UTF-8
default enc    : utf-8
Config dir     : /home/elopez/.config/mps-youtube
env:TERM       : screen-256color
env:SHELL      : /usr/bin/fish
env:LANG       : en_US.UTF-8
env:LANGUAGE   : en_US
```
#### OS

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily
```
### Question

As I only use `mps-youtube` to listen to audio, how can I config it to fetch smaller audio file? As it sometime strains the Internet connection I share.

**Comment by ids1024** [comment]
The reason is that it chooses the highest bitrate audio. There probably should be a way to change that, I suppose.

**Comment by lightningleaf** [comment]
A broadening of the suggestion: when showing all the versions of a video (and its audio), allow the user to choose whether to download or to stream.
