### ISSUE TITLE
How do i auto play [music/video] from the playlist

### ISSUE THREAD

**Issue by sanjay555** [mps-youtube/mps-youtube#484]
for playing music from playlist i am using --> 1-28 
but problem is after one song i have quite my VLC then it will play next song

**Comment by BlitzKraft** [comment]
Select media > Quit at the end of playlist. That quits automatically after each song. 

I use mplayer, this is the default behavior for it. I doubt anything can be done from the mps-youtube, since it needs support multiple players.

**Comment by ids1024** [comment]
It might be possible to implement this for mplayer/mpv using the fifo/IPC. I don't know if it is really possible for vlc...

The problem is that it takes time to retrieve all the video urls, so for a long playlist you would not want to load them all at the beginning.

**Comment by p-hash** [comment]
I'd rather requested simulation of youtube autoplay feature by playing first of related after finishing current one

**Comment by ids1024** [comment]
@p-hash You mean something like #230?
