### ISSUE TITLE
no progress bar with mpv

### ISSUE THREAD

**Issue by srvanrell** [mps-youtube/mps-youtube#485]
The progress bar is not shown when mpv player is used.
The version of mpv that I'm using is:
```
mpv git-bda1110 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sat Apr 30 02:41:02 UTC 2016
ffmpeg library versions:
   libavutil       55.23.100
   libavcodec      57.38.100
   libavformat     57.34.103
   libswscale      4.1.100
   libavfilter     6.44.100
   libswresample   2.0.101
ffmpeg version: N-79691-g66dd21d
```

**Comment by srvanrell** [comment]
BTW, I've changed to mpv because mplayer was not working on a lot of videos.

**Comment by ids1024** [comment]
This is a known issue, fixed in git in commit https://github.com/mps-youtube/mps-youtube/commit/7c2470f1eea4089014f38f451277623999c01c14.

It is due to the latest version of mpv changing the name of a command line argument.

**Comment by srvanrell** [comment]
OK, close this if you want. I hope to get the fix soon.

**Comment by srvanrell** [comment]
When will be available a new release that includes this fix?
