### ISSUE TITLE
Add --no-ytdl to default playerargs for mpv

### ISSUE THREAD

**Issue by flocke** [mps-youtube/mps-youtube#492]
For the last few weeks I had the problem that it took a really long time (30s - 2m) to start a video playback from mpsyt. Today I realized that this has something to do with the youtube-dl support in mpv.

I assume that mpsyt passes a URL for the video to mpv which can be played directly but instead is intercepted by the youtube-dl hook in mpv which causes some kind of trouble.

Just adding `--no-ytdl` to the playerargs in the settings fixed this for me, so it should probably be there by default.

**Comment by ids1024** [comment]
This seems like a good idea. One issue is that just adding the flag may break mpv versions before youtube-dl was supported (I'm not sure when that was added) but it is easy enough to add a check for that.

**Comment by ids1024** [comment]
9152509e820c2d822f5de643b264d73e07b2b7a3 should fix this.

**Comment by flocke** [comment]
Works fine for me now, thanks.
But I couldn't test for a mpv version without youtube-dl support.

**Comment by flocke** [comment]
Should I close this one even without testing it with a mpv version without youtube-dl support?
