### ISSUE TITLE
mpsyt plays very few results: silently returns to search

### ISSUE THREAD

**Issue by marc1uk** [mps-youtube/mps-youtube#493]
Using the latest github version 0.2.6 of mpsyt, and the latest MPlayer (SVN-r37871-snapshot-4.9.2, just downloaded both afresh), when trying to play files mpsyt most often simply thinks about it for a moment (the line gets highlighted).. then decides not to, and returns to the search results. 
Trying it with mpv gives slightly worse results (it can't even play the files mplayer can). Using 'mpv --version' gives 
```
libav library versions:
   libavutil       53.3.0
   libavcodec      55.34.1
   libavformat     55.12.0
   libswscale      2.1.2
   libavfilter     4.2.0
   libavresample   1.1.0
```
mpv is marginally more verbose printing for a short while a cycle of
```
getting content length
sbLidhFIL 640X480; 4MB (which flashes up *very* breifly)
error retrying
```
then after doing this a few times, returns to the search results.
Incidentally after this has happened keyboard input no longer appears on the terminal, but is nonetheless still registered - so i can enter commands, but blind. this persists even after mpsyt is exited, so i have to close the terminal. 

I've tried mpsyt --debug, but there's no /tmp/mpsyt.log file generated.

system is mint debian xfce.

**Comment by marc1uk** [comment]
I could add that sometimes with mplayer mps does print
```
fetching item...
adoSIhd466O; 4MB
```
where the first line may be displayed for a second or so, and again the second flashes very briefly. 

As an example of files that don't work; search for 'hardkandy standstill', then attempting to play 'all' will work it's way through them all, and play 2 results: "Out of the City - Hardkandy Mix", and "Palmer singing the National Anthem". Everything else fails.

**Comment by ids1024** [comment]
I'm not sure what the problem is...

Do you have the latest version of pafy installed?

**Comment by marc1uk** [comment]
Hi ids1024, thanks for helping. I had python-pafy 3.62-1 installed. I tried installing python3-pafy 3.80-1, but it hasn't made a difference.

**Comment by ids1024** [comment]
@marc1uk What is the full output of `mpsyt --version`?

**Comment by marc1uk** [comment]
$ mpsyt --version
mpsyt version      : 0.2.6
   notes           : released 1 January 2016
pafy version       : 0.5.1 (youtube-dl backend)
youtube-dl version : 2016.05.30.2
Python version     : 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-3.2.0-4-amd64-x86_64-with-LinuxMint-1-debian
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/marc/.config/mps-youtube
env:TERM           : xterm
env:SHELL          : /bin/bash
env:LANG           : en_GB.UTF-8

**Comment by ids1024** [comment]
You could try updating youtube-dl.

**Comment by marc1uk** [comment]
Just downloaded the latest version. No change.

**Comment by ids1024** [comment]
I don't know then. Does just using youtube-dl with the same videos work?

**Comment by cjekel** [comment]
I'm getting the same issue on a Mac, and a similar issue on a Windows computer.
 
OS X 10.6.8:
`MPlayer 1.3.0-4.2.1 (C) 2000-2016 MPlayer Team`
```
mpsyt version  : 0.2.6
   notes       : released 1 January 2016
pafy version   : 0.5.1
Python version : 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
Processor      : i386
Machine type   : i386
Architecture   : 64bit, 
Platform       : Darwin-10.8.0-i386-64bit
sys.stdout.enc : UTF-8
default enc    : utf-8
Config dir     : /Users/demo/.config/mps-youtube
env:TERM       : xterm-color
env:SHELL      : /bin/bash
env:LANG       : en_US.UTF-8
```
```
$ youtube-dl --version
2016.06.19.1
```

Windows:
`MPlayer sherpya-r37853+g6d7f566-5.3.1 (C) 2000-2016 MPlayer Team`
```
mpsyt version  : 0.2.6
   notes       : released 1 January 2016
pafy version   : 0.5.1
Python version : 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600
32 bit (Intel)]
Processor      : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
Machine type   : AMD64
Architecture   : 32bit, WindowsPE
Platform       : Windows-7-6.1.7601-SP1
sys.stdout.enc : cp437
default enc    : utf-8
Config dir     : C:\Users\demo\AppData\Roaming\mps-youtub
```
```
> youtube-dl --version
2016.06.19.1
```

However on Windows I don't get a silent error for the videos. Instead I get something that looks like
```
DJ Snake - Middle ft. Bipolar Sunshine : Sorry mplayer doesn't support this stre
am. Use mpv or update mplayer to a newer version
```
So on Windows If I switch to MPV it solves the issue. However I don't think there is a supported MPV for 10.6.8. I can confirm that the same videos that play on the Mac also play on the Windows computer. The videos that don't play give the silent error on Mac, and give the *sorry mplayer doesn't support...* error on Windows. 

Why does it state that mplayer does not support this stream? If I download the video, mplayer plays it fine on both operating systems. Is it possible that this is related?

I can confirm that youtube-dl works fine on both systems, and I can download videos with mpsyt on both systems.

**Comment by ids1024** [comment]
@cjekel Mpv is the recomended player. But it looks like you are right that it won't run on OS X 10.6.8. Is everything working fine with vlc now?

**Comment by cjekel** [comment]
mpsyt is working fine with vlc on OS X 10.6.8, and working with mpv on my Windows build. 

I suspect @marc1uk issue is related to errors playing https videos as I experienced similar described behavior. 

@marc1uk
Attempt to play a youtube video that doesn't work on mpsyt with one of the players you have installed mpv/mplayer/vlc. 

This can be done using youtube-dl. You can try this with mpv as well by replacing mplayer with mpv in the following line.
`$ youtube-dl -q -o- https://www.youtube.com/watch?v=IvPT2QuCIOA | mplayer -cache 8192  -`

With my version of mplayer, I would get an error stating something along the lines that https connections weren't supported.

**Comment by marc1uk** [comment]
Thanks for doing a lot of work on this cjekel, unfortunately i've been pretty busy and kept seeing there were things to try, but didn't have the time to do so. 
You're right, i was lacking https support. Trying to update ffmpeg from synaptic didn't work - in the end I downloaded and built from source, specifying --enable-openssl, and then had to re-configure and recompile mpv. mpv now plays yotube videos just given their url, and mpsyt is now working successfully with it too. :) Thanks for your guidance.
I also, mainly for completion's sake, tried to get mplayer working, but am still stuck here. trying to rebuild mplayer from source, i see it seems ot be using an internal ffmpeg version, rather than my system one. I'm not sure how to pass the --enable-openssl switch to that when compiling mplayer. As such mplayer complains about lack of https support. :|
