### ISSUE TITLE
Failed to load one specific playlist

### ISSUE THREAD

**Issue by flocke** [mps-youtube/mps-youtube#494]
I just ran into a playlist that mps-youtube just refuses to load for some reasons, while all other playlists work fine. Here is the link: https://www.youtube.com/playlist?list=PLmkgfnfw3UYaiu5vmHoPLSF89-yz5-fIY

When I run mpsyt with the `--debug` flag this error shows up:
```
Traceback (most recent call last):
  File "/usr/x86_64-pc-linux-gnu/lib/python3.5/site-packages/mps_youtube/main.py", line 64, in matchfunction
    func(*matches)
  File "/usr/x86_64-pc-linux-gnu/lib/python3.5/site-packages/mps_youtube/commands/songlist.py", line 87, in plist
    ytpl = pafy.get_playlist2(parturl)
  File "/usr/x86_64-pc-linux-gnu/lib/python3.5/site-packages/pafy/playlist.py", line 228, in get_playlist2
    return Playlist(playlist_url, basic, gdata, size, callback)
  File "/usr/x86_64-pc-linux-gnu/lib/python3.5/site-packages/pafy/playlist.py", line 145, in __init__
    pl = allinfo['items'][0]
IndexError: list index out of range
```

mps-youtube version: `git`
pafy version: `git`
youtube-dl version: `2016.6.3`
python: `3.5.1`

**Comment by ids1024** [comment]
Hm, it seem to work fine for me. Try installing https://github.com/mps-youtube/pafy/tree/debug494 and running it again, posting the output.

**Comment by flocke** [comment]
```
{'pageInfo': {'totalResults': 0, 'resultsPerPage': 5}, 'etag': '"0Fu6lI6VPLdRMlQU3wwNcowdAUs/zJL80hJ0IwMo5wddECFapC8I6Q4"', 'kind': 'youtube#playlistListResponse', 'items': []}
```

**Comment by flocke** [comment]
`youtube-dl -s https://www.youtube.com/playlist?list=PLmkgfnfw3UYaiu5vmHoPLSF89-yz5-fIY` seems to work, it simulates downloading all 126 videos of the playlist.

**Comment by ids1024** [comment]
This should be fixed in https://github.com/mps-youtube/mps-youtube/commit/e6cd6dc2753bd89c95ae2698726d5f13eb1181e1.

**Comment by flocke** [comment]
Yes, with your latest commit it works fine for me, thanks a lot :)
