### ISSUE TITLE
this came out when searching (inline, like this: mpsyt /QUERY)

### ISSUE THREAD

**Issue by burgerkalif** [mps-youtube/mps-youtube#502]
Search results for altered dominant backing track       [1/25>

> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.5/threading.py", line 862, in run
>     self._target(_self._args, *_self._kwargs)
>   File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 2480, in _preload
>     g.streams[ytid], audio=False)
>   File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 115, in select
>     ret = streams[q]
> TypeError: list indices must be integers or slices, not dict

**Comment by ids1024** [comment]
I think this is fixed in git. You can try using `pip install -U https://github.com/mps-youtube/mps-youtube/archive/develop.zip` to install the develop branch, and see if it works.
