### ISSUE TITLE
mpsyt crashes after update to 0.2.7

### ISSUE THREAD

**Issue by vnckppl** [mps-youtube/mps-youtube#503]
I just updated mpsyt and youtube-dl on OSX 10.10.5:

16:02:35 ~ ► sudo -H pip3 install mps-youtube -U
Password:
Collecting mps-youtube
  Downloading mps_youtube-0.2.7-py3-none-any.whl (93kB)
    100% |████████████████████████████████| 102kB 2.7MB/s 
Requirement already up-to-date: pafy!=0.4.0,!=0.4.1,!=0.4.2,>=0.3.82 in /usr/local/lib/python3.5/site-packages (from mps-youtube)
Installing collected packages: mps-youtube
  Found existing installation: mps-youtube 0.2.6
    Uninstalling mps-youtube-0.2.6:
      Successfully uninstalled mps-youtube-0.2.6
Successfully installed mps-youtube-0.2.7
16:03:01 ~ ► sudo -H pip3 install youtube-dl -U
Collecting youtube-dl
  Downloading youtube_dl-2016.6.27-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 738kB/s 
Installing collected packages: youtube-dl
  Found existing installation: youtube-dl 2016.6.23.1
    Uninstalling youtube-dl-2016.6.23.1:
      Successfully uninstalled youtube-dl-2016.6.23.1
Successfully installed youtube-dl-2016.6.27

Now when I start mpsyt, it crashes with the following error:

Enter /search-term to search or [h]elp                                                                               
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/mps_youtube/playlists.py", line 23, in load
    g.userpl = pickle.load(plf)
AttributeError: Can't get attribute 'Playlist' on <module 'mps_youtube.main' from '/usr/local/lib/python3.5/site-packages/mps_youtube/main.py'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/usr/local/lib/python3.5/site-packages/mps_youtube/main.py", line 116, in main
    playlists.load()
  File "/usr/local/lib/python3.5/site-packages/mps_youtube/playlists.py", line 39, in load
    g.userpl = pickle.load(plf)
AttributeError: Can't get attribute 'Playlist' on <module 'mps_youtube.main' from '/usr/local/lib/python3.5/site-packages/mps_youtube/main.py'>

Any suggestions?

**Comment by ids1024** [comment]
> AttributeError: Can't get attribute 'Playlist' on

It looks like some words are missing. Are you sure this is the complete error message?

**Comment by vnckppl** [comment]
You are right, part of the message was not in my post. Here is the full error message:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/mps_youtube/playlists.py", line 23, in load
    g.userpl = pickle.load(plf)
AttributeError: Can't get attribute 'Playlist' on <module 'mps_youtube.main' from '/usr/local/lib/python3.5/site-packages/mps_youtube/main.py'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/usr/local/lib/python3.5/site-packages/mps_youtube/main.py", line 116, in main
    playlists.load()
  File "/usr/local/lib/python3.5/site-packages/mps_youtube/playlists.py", line 39, in load
    g.userpl = pickle.load(plf)
AttributeError: Can't get attribute 'Playlist' on <module 'mps_youtube.main' from '/usr/local/lib/python3.5/site-packages/mps_youtube/main.py'>

**Comment by ids1024** [comment]
Commit 401539e3e62e761a8b237fda76d008f3c430745a should fix this.

Try installing from the develop branch with `sudo pip3 install -U https://github.com/mps-youtube/mps-youtube/archive/develop.zip` to test if it fixes the problem for you.

**Comment by vnckppl** [comment]
Yes, that did work. Thank you!
