### ISSUE TITLE
Seeking help in troubleshooting mangled playlist search view

### ISSUE THREAD

**Issue by v1kn** [mps-youtube/mps-youtube#514]
~~I am certain this is not a bug in mps-youtube, but~~ I would like to request some help in figuring out what may be the cause of a mangled playlist search view that is observable only on my main laptop. In short:  
- [this](http://imgur.com/a/i3PNO) is how it looks. several top entries are cut off, I have to scroll to see them, and the last row _count_ is misplaced on the second line near the beginning. the view within a playlist when I choose one, is correct. The song search view is also correct.  
- mps-youtube is version 0.2.7.1, mpv is 0.18.1, distribution is Xubuntu 16.04.1
- the error does not occur on fresh install xubuntu 16.04.1 tested in virtualbox. only my laptop os.
- While I use tmux, the error is observable outside of tmux session
- its observable with stock bashrc
- its observable regardless of terminal app used (terminator, xfce4-terminal), or font size

I am at the point I have no idea what settings I can check or change, to fix it.
I would really appreciate any suggestion as to what can cause this behavior.

**Comment by ids1024** [comment]
What locale does your system use?

**Comment by v1kn** [comment]
ah, clever :) 
Youre right. While my system language is en_US, I use japanese regional formats for dates. This produces additional kanji for after year month and day and apparently messes up everything behind it. 

I have switched to english US regional formats and this fixes it, but is it somehow fixable for other regional formats?

**Comment by ids1024** [comment]
It should be possible to fix, but may not be trivial. The code for rendering tables like that in mpsyt is a mess and needs to be rewritten, That should be done as part of #423, but what that PR aims to achieve is rather complicated and I haven't been working on it recently, so I don't know when that may be done.

If you don't mind modifying the code, you should be able to hack the `generate_playlist_display()` function in `content.py` to give more space for the date.

**Comment by v1kn** [comment]
I see.  
That's fine. I mean, if it can be fixed when You get to rewrite pertinent parts of mpsyt, then it will be great. For the time being, this is not a critical bug, and I can work around it.

Thanks
