### ISSUE TITLE
Add --no-textart flag

### ISSUE THREAD

**Issue by stormdragon2976** [mps-youtube/mps-youtube#515]
I am blind, and use a screen reader. when I start mps-youtube I get a ton of underscore, dash, and other characters read. I'm guessing it is some sort of textart. Can you add a flag to skip all that stuff? it's not a huge deal, just would be nice to be able to open the app without a ton of chatter from my reader lol.

**Comment by Gongreg** [comment]
Hello,
I've made a pull request to add command --no-textart at the beggining of program.
I am no python developer, but code is well written and easy to look at. So I hope that everything will pass.
