### ISSUE TITLE
Use mpv by default to avoid mplayer error because of no https support

### ISSUE THREAD

**Issue by sucotronic** [mps-youtube/mps-youtube#518]
I discovered this great tool, and after installing in my mac I found that most songs don't play, so after modifying the code to output the command (the logging feature produces a nonsense file in osx), I 've seen that mplayer doesn't support https uris (or at least the version provided by brew).

I'll be better (imho) to recommend the use of mpv, that supports sll, and use it by default.

**Comment by ids1024** [comment]
I think mpv is the default, if it is installed. Otherwise it defaults to mplayer.

**Comment by sucotronic** [comment]
What about displaying some kind of message to a user when mplayer fails to play a https stream?

**Comment by ids1024** [comment]
There already is a message that should display:

https://github.com/mps-youtube/mps-youtube/blob/develop/mps_youtube/player.py#L243

**Comment by sucotronic** [comment]
I see you're detecting the ssl support based on mplayer>1.1, but in my case (osx) I have mplayer 1.3 but ffmpeg complains about not openssl support:

```
$ mplayer https://dts.podtrac.com/redirect.mp3/dovetail.prxu.org/serial/d7f03a15-be26-4634-8884-5fadd404ad75/serial-s01-e01.mp3
MPlayer 1.3.0-4.2.1 (C) 2000-2016 MPlayer Team
Can't init Apple Remote.

Playing https://dts.podtrac.com/redirect.mp3/dovetail.prxu.org/serial/d7f03a15-be26-4634-8884-5fadd404ad75/serial-s01-e01.mp3.
libavformat version 57.25.100 (internal)
https protocol not found, recompile FFmpeg with openssl, gnutls,
or securetransport enabled.
Failed to open https://dts.podtrac.com/redirect.mp3/dovetail.prxu.org/serial/d7f03a15-be26-4634-8884-5fadd404ad75/serial-s01-e01.mp3.


Exiting... (End of file)
```

It seems that mplayer uses its own ffmpeg library, statically linked, so it would be better to know if that ffmpeg library "inside" mplayer supports ssl. Other way would be to grep the output of the command to detect the "https protocol not found" string.

**Comment by ids1024** [comment]
> Other way would be to grep the output of the command to detect the "https protocol not found" string.

That is probably the most reliable method...
