### ISSUE TITLE
1080p video support?

### ISSUE THREAD

**Issue by jiang-qian** [mps-youtube/mps-youtube#520]
As I understand, the 1080p video playing need DASH support. However, the experimental branch of mys-youtube with dash hasn't been updated for about a year. Furthermore, when I tried it, it throws a "connection error" then retry in a loop.

So my question is, is there a way right now, even if it is experimental, to play youtube video in 1080p resolution? If so, what are the versions of the software I need (e.g. mpv, youtube-dl and mps-youtube itself) and what are the parameters I need to set?

I could just play it in the browser, but then I need to buy youtube RED to skip ads... Thanks in advance!

**Comment by ids1024** [comment]
The dash branch is a trivial hack, and it should be easy to update it.

Alternately you could just use `mpv --ytdl-format=bestvideo+bestaudio $YOUTUBE_VIDEO_URL` outside of mpsyt, which is just what the dash branch does.

**Comment by jiang-qian** [comment]
Thanks for the quick response! I know it's not your issue, but when I put in mpv --ytdl-format it complains about invalid option. Is this a very recent version of mpv?

**Comment by ids1024** [comment]
I think the functionality has been in mpv for a while.

**Comment by jiang-qian** [comment]
Cool. I've updated my mpv and it now works! Thanks a lot!
