### ISSUE TITLE
doesn't playback on raspberry pi

### ISSUE THREAD

**Issue by nicosandller** [mps-youtube/mps-youtube#521]
I've got raspbian weezy, managed to successfully install mps-youtube, but I can't seem to get any video or audio playback when using it. 

no logs show up. Any clues on what might be happening?

**Comment by ids1024** [comment]
Are you using mpv or mplayer? If you are using mplayer, try installing mpv and running `set player mpv` in mpsyt.

**Comment by nicosandller** [comment]
omg I forgot to set the player. Ended up setting `set player omxplayer` and it works like a charm :) 

perhaps include an exception when player is not set?

**Comment by ids1024** [comment]
Do you have mplayer or mpv installed? If you have either, it would be automatically set (with mpv favored if both are installed).

I think it does print an error otherwise...

**Comment by nicosandller** [comment]
that's true, I've got mplayer. But it didn't work. omxplayer works perfect.

**Comment by NathanielJS1541** [comment]
For me, neither mpv or mplayer work on a Raspberry Pi model 3B+ but omxplayer does. Not sure what the issue is with mpv and mplayer.
