### ISSUE TITLE
How to get back to playlist search results?

### ISSUE THREAD

**Issue by Vrihub** [mps-youtube/mps-youtube#523]
Steps to reproduce:
- Do a playlist search: //stuff
- From the playlist search results screen, select an item
- Enjoy :)
- Now, how can I go back to the search results screen?

The only way I found is to navigate the command history and re-run the playlist search command.

Maybe there should be a shortcut key to go back to the results screen without re-running the actual search

**Comment by dkvasnicka** [comment]
Why was this closed? Was something done to implement this or was there some solution already or was it just closed as "Won't Fix"? The absence of any notion of "going back" seems really weird to me.
