### ISSUE TITLE
unable to play music

### ISSUE THREAD

**Issue by Dauth** [mps-youtube/mps-youtube#525]
I am unable to play anything.

In the debug mode this is the message

Filename is too long, can not load file or directory specific config files  
Playing: https://r1---sn-npo7zn7k.googlevideo.com/videoplayback?sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&requiressl=yes&source=youtube&id=o-AOCyJNNK-sqbOD-drJOnaRN3H5bQT9keqMP7TUs9H0J7&pl=21&ms=au&mt=1472708568&mv=m&mm=31&ip=203.142.21.232&mn=sn-npo7zn7k&ipbits=0&itag=17&initcwndbps=438750&mime=video%2F3gpp&key=yt6&ei=BsHHV7X2K8rkogPU74iYCg&upn=DK4OjiIhInY&expire=1472730470&dur=234.242&lmt=1394298480649543&sver=3&nh=IgpwcjAyLnNpbjAzKgkxMjcuMC4wLjE&signature=B516B3C9BA73793997A511384E0B5F992C60C2DA.8F0CCDA54D504D5A8A9DEBC1D83F1F02FEADE55C&ratebypass=yes
[cache] Cache size set to 320 KiB
Cache fill: 20.62% (67584 bytes)  
Detected file format: QuickTime / MOV (libavformat)
Clip info:
 major_brand: 3gp6
 minor_version: 256
 compatible_brands: isom3gp6
 creation_time: 2014-03-07 17:07:58
[stream] Video     --vid=1 (mpeg4)
[stream] Audio (+) --aid=1 --alang=und (aac)
Video: no video
Selected audio codec: AAC (Advanced Audio Coding) [lavc:aac]
[ao/alsa] Format floatp is not supported by hardware, trying default.
AO: [alsa] 48000Hz stereo 2ch s16
--suRGfAaju4; 3gp 176x144; 2 Mb; 00:00:00 [0%]   [>

**Comment by ids1024** [comment]
I'm not really sure what the problem is. Exactly what is the issue? The output you posted includes a progress bar; does it stay at zero, continue normally (but without producing sound) or just stop? Also, what is the full output of `mpsyt --version`?

**Comment by Dauth** [comment]
It just shows "error:retrying"

mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.2 (youtube-dl backend)
youtube-dl version : 2016.08.31
Python version     : 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/tester/.config/mps-youtube
env:TERM           : screen-256color
env:SHELL          : /usr/bin/zsh
env:LANG           : en_SG.UTF-8

**Comment by ids1024** [comment]
Are you using mplayer or mpv? If it's mplayer, try installing mpv and running `set player mpv` in mpsyt.
