### ISSUE TITLE
Can stream but can not download?

### ISSUE THREAD

**Issue by johnwmail** [mps-youtube/mps-youtube#527]
I can stream/watch video/music with mpv, but can not download, the error message like this

Problem playing last item: [Errno 13] Permission denied: '/home/user/mps/Hakan Salman.webm'

I am 100% sure /home/user/mps/ is writable by me, I want to know how to debug?

rm -rf /home/user/.config/mps-youtube still can not download

set ddir /tmp still can not download

My system is debian/amd64/sid (mps-youtube: 0.2.7.1 and python3.5)

Thanks.

**Comment by ids1024** [comment]
Do you get any errors if you run `touch "/home/user/mps/Hakan Salman.webm"` in a terminal?

(I am assuming `user` is substituted with your actual username. If not, that would also cause this issue.)

**Comment by johnwmail** [comment]
I can create zero file with touch "/home/user/mps/Hakan Salman.webm" without any error.

Yes, "user" is username, type whoami will return user.

**Comment by ids1024** [comment]
I don't know what would cause this issue then...

**Comment by johnwmail** [comment]
I can confirm, some format can download, some format can not

I can download with opus format
But can not download with mp4 webm 3gp ..etc

Any idea why with that ? 
Thanks.

**Comment by ids1024** [comment]
Do you have any files in the download directory already?

**Comment by johnwmail** [comment]
No, the download directory is empty.

**Comment by ids1024** [comment]
> one thing I want to know, if mps-youtube need exec any tool to download some format
(because need convert it or any reason), like m4, webm, 3gp ???

Oh yes; under certain circumstances it will call ffmpeg.

**Comment by johnwmail** [comment]
Sorry to say that!

I find out the problem is my system config (apparmor rules denied),
not the mps-youtube bug.

Thank all.
