### ISSUE TITLE
Replace youtube_dl by youtube-dl in README.md

### ISSUE THREAD

**Issue by user3141592** [mps-youtube/mps-youtube#536]

**Comment by ids1024** [comment]
As far as I am aware, this makes no difference, and `pip3 install youtube-dl` is equivalent to `pip3 install youtube_dl`.

**Comment by boddhissattva** [comment]
The difference is that `apt-.get install youtube_download` leads to `Unable to locate package` whereas `apt-get install youtube-download` is fine.
