### ISSUE TITLE
"rm" command not works properly.

### ISSUE THREAD

**Issue by antoniovandre** [mps-youtube/mps-youtube#539]
It removes a item from a playlist, but, when I restart mpsyt, the item continues on the playlist...

**Comment by ids1024** [comment]
You need to save the playlist for the change to take effect.

**Comment by antoniovandre** [comment]
I open the playlist, remove some itens, and command "save <playlist>", but only displayed itens on the current page are saved; all the itens of the other pages (say 2/3 and 3/3) are deleted from the playlist...

**Comment by ids1024** [comment]
A current limitation of mps-youtube is that commands are based on the contents of the current page instead of all pages. Use the `dump` command before `save` to get the desired behavior.

This is not really desirable, and is fixed in #423, but that is incomplete and not really functional yet.
