### ISSUE TITLE
Add (all) items to existing playlist

### ISSUE THREAD

**Issue by therimalaya** [mps-youtube/mps-youtube#544]
This is a enhancement request. Please add a feature to add items to the existing playlist without removing items inside it. I also want to add all the items in a playlist. `add * <playlist>` is not working. This `all(*)`feature is also not working with audio download. as `da *`.

**Comment by ids1024** [comment]
Hm, I didn't even know the `add` command takes a playlist argument...

You can do something like this:

    open playlist
    /something
    add *
    vp
    dump
    save playlist

The dump command is needed only if the playlist doesn't fit on a page, since commands like `add` work on individual pages (this is hopefully going to change in the future).
