### ISSUE TITLE
Playback Error... youtube-dl 

### ISSUE THREAD

**Issue by vdias** [mps-youtube/mps-youtube#546]
ERROR: hYY-a0_Bb9Y: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Using the last windows version...

**Comment by PorscheLauren** [comment]
Just get your own google api key..,
