### ISSUE TITLE
gobject should be listed as a dependency

### ISSUE THREAD

**Issue by kyrias** [mps-youtube/mps-youtube#547]

**Comment by ids1024** [comment]
It is supposed to be an optional dependency (for mpris2 support); 942cfed76baa484a08ff58549f3d1032db37d9cb fixes that.

This had broken since I had moved the import (it was interfering with another dependency).

**Comment by kyrias** [comment]
Awesome, though it would still be nice to have a list of optional dependencies too, since it's currently not documented.

**Comment by ids1024** [comment]
Agreed; 2ee76048855ed5e09533403de21afb39e4f16bac adds a mention of it to the README
