### ISSUE TITLE
where are the playlist saved ?

### ISSUE THREAD

**Issue by icf20** [mps-youtube/mps-youtube#550]
i did try to move a playlist from a PC to another and i dint find the location where mpsyt saves the files i did try to just copy playlist_v2 but no succes so far  

also how should i run this via cmd i am kinda new to windows 

```
mpsyt --version
'mpsyt' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by ids1024** [comment]
`playlist_v2` is the file that the playlists are stored in. It should be possible to move it from one computer to another; I haven't really tried.

**Comment by Johnstone-Tech** [comment]
What format is the playlist_v2 using? I wanted to remove a few tracks from a playlist and was surprised it wasn't in plain text.

**Comment by ids1024** [comment]
@Johnstone-Tech It's the binary format created by Python's `pickle` module, which is a binary representation of Python's types.

More specifically, it contains a pickled dictionary of playlist names to `Playlist` instances, which in turn contain `Video` instances (though are classes defined in `mps_youtube/playlist.py`.

See #112 for a script to dump the format as text, and for the plans for moving to a plain text format (I should probably just make that change; I haven't been working on mpsyt lately).

**Comment by nikisix** [comment]
Plain text plz if it's not too much trouble
