### ISSUE TITLE
bad syntax if da/dv items are not numerically sorted

### ISSUE THREAD

**Issue by Vrihub** [mps-youtube/mps-youtube#554]
When I want to download some items, mpsyt throws a "bad syntax" error if the items after a da or dv command are not sorted numerically. 

Let's say I want to download videos # 1, 3 and 11 in a search results list:

`da 1,3,11` works fine

`da 11,1,3` causes the "bad syntax" error

**Comment by Vrihub** [comment]
I've been using the program since a long time now, and actually this bug seems to happen quite randomly; in my previous message I believed that "unsorted" item lists always failed, but this is not the case; sometimes they work, just like "sorted" lists, sometimes they don't.

I tried to run `mpsyt --debug`, but when the `bad syntax` error occurs, nothing is logged to the log file.

How to reproduce:
- search for `/dr strangelove`
- try to download two "unsorted" items: `dv 20 6`

I guess your result list could be different from mine, the two items above correspond to:
20: "Peter Sellers doing accents and talking Dr. Strangelove on NBC's Today Show interview (1980)"
6: "Inside the Making of Dr. Strangelove"

**Comment by ids1024** [comment]
https://github.com/mps-youtube/mps-youtube/commit/11765660293f356878bc7fb8fbbc5f88582a4d20 hopefully fixes this.

**Comment by Vrihub** [comment]
> 1176566 hopefully fixes this.

I'm afraid it doesn't, and it even causes more errors.

Anyway I had a closer look (me lazy!): and since a regex is involved, it doesn't really know anything about "sorting" of numerical values, it's a matter of the number of digits allowed; it seems the problem is that the original regex didn't allow 2-or-more digit values followed by single-digit values.

So I would change line 127 in `commands/download.py` like that:

    
    Index: mps_youtube/commands/download.py
    ===================================================================
    --- mps_youtube.orig/commands/download.py
    +++ mps_youtube/commands/download.py
    @@ -124,7 +124,7 @@ def download(dltype, num):
         g.content = content.generate_songlist_display()


    -@command(r'(da|dv)\s+((?:\d+\s\d+|-\d|\d+-|\d,)(?:[\d\s,-]*))')
    +@command(r'(da|dv)\s+((?:\d+\s\d+|-\d+|\d+-|\d+,)(?:[\d\s,-]*))')
     def down_many(dltype, choice, subdir=None):
         """ Download multiple items. """
         choice = util.parse_multi(choice)


i.e.: I just added the "+" qualifier to the \d terms that were missing it.

I've tested it, it fixes the problem, and it doesn't seem to have obvious drawbacks. Do you agree?

**Comment by Vrihub** [comment]
Ping. Or should I make a PR for my proposed fix?

**Comment by ids1024** [comment]
You can submit a PR; these long regexs are hard to understand, but that looks correct, so if it seems to work it should be fine.
