### ISSUE TITLE
Tests have side effects

### ISSUE THREAD

**Issue by lheckemann** [mps-youtube/mps-youtube#556]
Running the tests results in importing `paths.py`, which calls `os.makedirs(mps_confdir, exist_ok=True)`. This means that the tests:
- are conditional on the environment (I discovered this because of running the tests as a user with no existing home directory)
- make permanent changes to the system they are running on

both of which should not be the case.

**Comment by ids1024** [comment]
Good point. I suppose the unit tests should create a temporary directory to use for configuration, instead of using the normal one in the user's home directory.

Mpsyt is also going to need far more tests before they can really be of much use.

**Comment by lheckemann** [comment]
They shouldn't really need to create a directory at all...

**Comment by ids1024** [comment]
For the current tests, yes. More elaborate unit tests might though.

**Comment by lheckemann** [comment]
Unit tests shouldn't have side effects or interact with anything other than the code that's being tested, otherwise they're not unit tests. They're not meant to test `os.path.mkdirs` and should be able to run with no ability to modify the filesystem at all.

**Comment by ids1024** [comment]
Testing the downloading functionality would require writing a file to a temporary location.

**Comment by lheckemann** [comment]
Testing downloads is out of the scope of unit testing, as it necessarily has side effects (network communication is a side effect), relies on external resources, and makes many assumptions about the environment (internet connection that allows access to youtube, availability of a video (both that it hasn't been deleted yet and that it's available in the country being tested in), availability of soft dependencies, ability to write to file system, etc). It's the sort of thing that cannot be reliably tested by simple code, instead needing either a comprehensive integration test or (much simpler and more appropriate in this case) manual testing. This is *not* the sort of thing that can be tested as a unit, as it depends on too many external factors.

**Comment by ids1024** [comment]
Ah yes, fair enough; I suppose that would be an integration test rather than a unit test.

**Comment by lheckemann** [comment]
One that should be performed manually rather than programmatically, at that, because such arbitrary things as the country the code is running in can affect it.
