### ISSUE TITLE
Suggested Feature: Kodi Support

### ISSUE THREAD

**Issue by diskotechjam** [mps-youtube/mps-youtube#558]
One of my main uses for mpsyt is sending videos and audio to my kodi box connected to my stereo/tv. Currently, I use idok to accomplish this, but there are some set backs. For example, rather than handling playlists correctly, idok will just send the items one right after another, there's no ability to pause/play/skip items within mpsyt, and sending the item to another kodi box involves editing the config file. Ultimately, it would be really useful if mpsyt had built in support for kodi, including the ability to pause/play/skip items in a similar way that mpsyt interacts with mpv.

**Comment by BlitzKraft** [comment]
I love the idea. I second that. I use kodi too and it would be useful to be able to control kodi from the terminal.

**Comment by ids1024** [comment]
I don't really use Kodi, but I can see how that would be useful. I don't think the solution involves any change to mpsyt though.

What you need is a command line player that sends the video to Kodi then persists, receiving input from the keyboard to play/pause/etc. So essentially a cli Kodi client that behaves like mpv/mplayer.

You could then use said program with mpsyt exactly as you are using idok now.

**Comment by BlitzKraft** [comment]
I found [castnow](https://github.com/xat/castnow) (command line application), at the moment, for chromecast. There is a workaround for sending youtube videos using youtube-dl to download it and send it. This of course, drains the battery on the phone. 

Kore (remote for kodi - on mobile devices) adds a sharing option - "Play on Kodi". In the youtube app (on the mobile devices) > The three dots next to the video > Share > Play on Kodi. 

I am not familiar with the kodi api, but it seems that there is a way to request it to load a video just by sending it the URL. I just started looking through the documentation for kodi, and it has a python api too. From what I understand so far, I think it should be possible to write a function that accomplishes this feature.

**Comment by flocke** [comment]
@diskotechjam Is there a reason why you use mpsyt to stream to Kodi instead of just using the official Kodi Youtube plugin?

**Comment by diskotechjam** [comment]
@flocke There are a few reasons. I find it far more convenient to browse youtube through mpsyt than through the slightly clunky kodi ui. I enjoy being able to send easily play audio only streams, I have all of my searches bookmarked for mpsyt so I don't need to worry about managing a youtube account or signing in on kodi, and I always have my latop out anyways mpsyt is my absolute favorite way to use youtube, so if I have the choice I use it.

**Comment by flocke** [comment]
If you mainly use it to listen to audio I can recommend pulseaudio-dlna (https://github.com/masmu/pulseaudio-dlna), at least until mps-youtube gets support for Kodi. With this you can add your Kodi box as an audio sink in pulseaudio and use it for output.
Of course it's not that easy for videos ...
