### ISSUE TITLE
Text and Colors not displayed correctly in Windows10

### ISSUE THREAD

**Issue by clarking** [mps-youtube/mps-youtube#559]
i got a fresh install of mpsyt on python 3.5.2 in Windows 10 Pro and text is not colored but instead got random chars that not allow to select any option
![mpsyt](https://cloud.githubusercontent.com/assets/8283993/19986970/018decba-a1d6-11e6-8a05-990a62618c39.png)

**Comment by ids1024** [comment]
Try installing `colorama` with `pip`.

**Comment by clarking** [comment]
it worked, thank you!
