### ISSUE TITLE
Seek not working when used within Emacs terminal mode

### ISSUE THREAD

**Issue by bangar1991** [mps-youtube/mps-youtube#560]
I recently discovered mps-youtube, and really loving it! I can understand if using mps-youtube inside an Emacs terminal session (i.e. M-x term inside Emacs and run mpsyt) may not be supported. Even so, all the playback controls are working fine in this setting, except seeking, which is a major pain.

Since I have configured mps-youtube to use mpv, so I modified the mpv keybindings for seek to say '.' and ',', and I can confirm that they work with mpv in the same terminal session within Emacs but without mps-youtube. When I use the same inside mps-youtube, they do nothing. Which is weird since I thought that mps-youtube was only relaying these keystrokes to whatever player it is configured to work with.

Anyway, thanks for making such an awesome piece of software!

**Comment by ids1024** [comment]
Odd.

> Which is weird since I thought that mps-youtube was only relaying these keystrokes to whatever player it is configured to work with.

Yes, that's pretty much how it works, so I don't know why this would happen.
