### ISSUE TITLE
Play local music

### ISSUE THREAD

**Issue by Fandekasp** [mps-youtube/mps-youtube#562]
Hi, new mpsyt user, and loving it!

I have a question regarding downloaded music. How can I create a playlist from it?
Here are the steps I followed:

    //arthur rubinstein chopin
    da 1

I can see the files downloaded in `Downloads/mps/` (not all, it got interrupted after the 77th audio file for some reason), but I have no clue how to tell mpsyt to play these downloaded files instead of restreaming them from youtube.
I was under the assumption that a playlist would automatically be created for that download, but that isn't the case.

Please recommend me the best way to create playlists from local files, thanks in advance!

**Comment by BlitzKraft** [comment]
Using mpsyt for playing local files seems counter intuitive. Try using any of mplayer, mpd, vlc etc., for that.

**Comment by Fandekasp** [comment]
I see. Thanks for the quick reply
