### ISSUE TITLE
Stopping music stream rather than using 'q' command 

### ISSUE THREAD

**Issue by KEINOS** [mps-youtube/mps-youtube#568]
Are there any commands or ways to stop multiple threads of mpsyt sound-only-stream running at once?

I'm using mpsyt on RasPi(Raspbian) as a music streaming player in our office. And works great.

I know, from SSH, using 'q' command or 'ctl+c' will end mpsyt run, and stop the current music playing.

But since I'm the only SSH user in my office, I made a simple PHP program that calls .sh file that streams sound-only youtube clip using mpsyt, so anyone could request the music to play.

The problem is, while playing a song, if another one requests a song, it plays on top of each other.
So I want to stop the current play or kill all the streams before playing the new one.

What would be the best way to stop current play, rather than quitting the app (using 'q' cmd)?

**Comment by tinydynamite00** [comment]
@KEINOS, you can pause the player by sending <code>spacebar</code>, 0x20 to the terminal. This will only pause the video/audio stream while sending a carriage return, <code>enter</code>, 0x0D after the space escapes the audio/video player without forcing an exit from the current session the way ^D, ^C do.

**Comment by KEINOS** [comment]
@tinydynamite00, thank you for the reply!

Sending `spacebar` then `enter`, 0x20->0x0D, might be the breakthrough.
Though, I use the following command from PHP using `exec`, which works from the terminal too, so to play it background.
`mpsyt .more than words, 1, q > /dev/null < /dev/null &`
So, how do I send those two ASCII codes, if I'm not in interactive mode?

**Comment by lol768** [comment]
Couldn't you create a FIFO and use `mpsyt ... < namedpipe` and append to it from within PHP?

**Comment by ids1024** [comment]
Mpsyt supports the mpris2 API, and can be controlled with an mpris2 client such as playerctl.

**Comment by KEINOS** [comment]
@lol768: thanks for the info.

I tried as you suggested, using FIFO, and it played a song but it didn't accept any syntax until the song ends.
So, very interesting approach but having the same problem, it was. Can't stop the music.

Here're the steps I took.

**In the terminal A via SSH:**
 ```
cd $HOME
mkfifo test
/usr/local/bin/mpsyt < test
```
**In the terminal B via SSH:**
```
cd $HOME
cat >> test
.more than words
1   <-- here starts playing the 1st song of the search results
    <-- here, spacebar then enter keys were sent but didn't pause (†)
p   <-- here, 'p' key + enter sent but didn't pause either (†)
.new kids on the block    <-- After the song ended it starts accepting the syntax again
2   <-- here, starts the 2nd song of the search results
q   <-- While playing a song doesn't accept (†)
q   <-- After the song end, 'q' syntax works and closes mpsyt
```
(†) these key inputs were ignored.

Also, I tried the following in **Terminal A** but didn't stop nor pause either...
```
sudo ./mpsyt .new kids on the block,1 < test
```

Did it work in your environment? Any ideas?

One thing that I noticed was that playing a long song via PHP ( via web browser ), and if I try the above 2-terminal-test meantime, the PHP side song pauses, maybe mutes, after 1 or 2 minutes later. And it starts again if I quit the test's mpsyt.

PS: Anyways, using named pipe was quite fun!!! Thanks!

**Comment by tinydynamite00** [comment]
>    <--> here, spacebar then enter keys> were sent but didn't pause (†)
>p   <--> here, 'p' key + enter sent but> didn't pause either (†)
@KEINOS Sorry, can't tell from your code: Are you using <code>echo -e</code> to send the escape sequences to the terminal?

**Comment by KEINOS** [comment]
@ids1024
> Mpsyt supports the mpris2 API and can be controlled with an mpris2 client such as playerctl.

I'm humbled by the guru's remark!

Since I didn't know about "mpris", I googled some and found the issue #191. And yes, it seems very much what I want. Especially the web-based client.

I tried to install *playerctl* first, into my Raspbian@RasPi3, but I haven't able to run it.
It seems that I have to configure and learn many things...
What is the simplest way to send API commands to mpsyt directly through the shell?

Another question, if I run an invoked command like below
`mpsyt .more than words, 1, q > /dev/null < /dev/null &`
I get a result like
`[0] 1909`
What are these 4 digits? PID?
Because `pkill 1909` won't stop, and I have to run  `pkill omxplayer` 3 times to kill all the processes. But it's not a smart way to stop them.

What I want is simple, something like
```
pi@raspberrypi:~ $ mpsyt .mc hammer, 1, q > /dev/null < /dev/null &
[1] 2146
pi@raspberrypi:~ $ <here do anything while playing>
pi@raspberrypi:~ $ mpsyt stop all   <-- ideal syntax
pi@raspberrypi:~ $ mpsyt .adele, 1, q > /dev/null < /dev/null &
pi@raspberrypi:~ $ <here do anything while playing>
```
Though, I'm appreciatively exploring how to use `mpris`.
`mpsyt` is fun! and thanks from Japan!

**Comment by KEINOS** [comment]
@tinydynamite00

> Are you using echo -e to send the escape sequences to the terminal?

No, just pressing `spacebar` then `enter` while using `cat`.
Echo! I haven't that in my mind. So I tried using with `echo` like below but didn't pause.
Do you know how to **stop** rather than pausing?

**In the terminal A via SSH:**
```
pi@raspberrypi:~ $ cd $HOME
pi@raspberrypi:~ $ mkfifo test   <-- removed in advance if test already exists
pi@raspberrypi:~ $ /usr/local/bin/mpsyt < test
```
**In the terminal B via SSH:**
```
pi@raspberrypi:~ $ cd $HOME
pi@raspberrypi:~ $ echo -e ".spice girls" >> test
pi@raspberrypi:~ $  echo -e "1" >> test   <-- here starts playing the 1st song of the search results
pi@raspberrypi:~ $  echo -e " " >> test    <-- doesn't pause
pi@raspberrypi:~ $  echo -e " \n" >> test    <-- doesn't pause
pi@raspberrypi:~ $  echo -e "p" >> test    <-- doesn't pause
```

**Comment by tinydynamite00** [comment]
@KEINOS The <code>-e </code> tells shell not to ignore an escape sequence and to treat it as one. Have you tried double escaping and sending ASCII sequences to the terminal? For example, try running:
<code>echo -e \\x20\\x0A\ playlist</code>

If this produces the desired effect, 'q' [Code 0x71] stops the player and returns to the playlist. In theory, [Code 0x0A] 'Enter' would work in this context as well.

**Comment by KEINOS** [comment]
@tinydynamite00:
> Have you tried double escaping and sending ASCII sequences to the terminal?

Ahh, you're right, I had to. Though, I tried like below, with double escaping, but didn't work...

**In the terminal B via SSH:**
```
pi@raspberrypi:~ $ cd $HOME
pi@raspberrypi:~ $ echo -e ".spice girls" >> test
pi@raspberrypi:~ $ echo -e \\x31 >> test        <-- 0x31 = 1 sent. Here works OK. Starts playing the 1st song of the search results.
pi@raspberrypi:~ $ echo -e \\x20\\x0a\ >> test  <-- Doesn't pause.
pi@raspberrypi:~ $ echo -e \\x20\\x0a >> test   <-- Doesn't pause.
pi@raspberrypi:~ $ echo -e \\x20\\x0d >> test   <-- Doesn't pause.
pi@raspberrypi:~ $ echo -e \\x20 >> test        <-- Doesn't pause.
```
Hmm... still, while playing a song, it seems that *mpsyt* is not accepting any commands even via FIFO.

I'm going to keep find the solution, but as a transitional approach, I added these two lines to force stop the current playing song.
```
sudo pkill -f mpsyt
sudo pkill -f omxplayer
```
I don't like it, though...

**Comment by ids1024** [comment]
Oh, I see why `playerctl` didn't work. Mpsyt only starts the mpris interface when using mpv or mplayer (it doesn't know how to control any other kind of player).

You could try `playerctl` again, but using mpv instead of omxplayer. Mpv has a backend for hardware decoding on the Raspberry Pi, so it should work reasonably well.

**Comment by tinydynamite00** [comment]
I'm having a somewhat similar issue controlling mpv - Android 7.0. I can't get it to accept any arguments after piping it through mpsyt or launching it from a bash function. IMHO, this all has very little or none to do with mpsyt.

**Comment by ids1024** [comment]
@tinydynamite00 if stdin or stdout (as of mpv-player/mpv@a037f7b) is not a terminal, mpv does not read commands from stdin.

**Comment by tinydynamite00** [comment]
@ids1024 Thanks! Classic user error. The commit you cite makes perfect sense. :)

**Comment by KEINOS** [comment]
@ids1024,
> You could try `playerctl` again, but using mpv instead of omxplayer. 

I switched to `mpv` from `omxplayer` though `playerctl` still not working. But I'm sure it's my environment dependent problem. Still working and studying.

By the way, I just published the PHP script wich I use to play in our office.
It's very simple but enough just to play and stop songs.
https://github.com/KEINOS/tiny-php-youtube-player

I named "Tiny PHP Youtube Player for MPSYT" taken from both @ids1024 and @tinydynamite00, if I may.

**Comment by ids1024** [comment]
@KEINOS You shouldn't cite me as the author of mpsyt; @np1 originally created it and most of the code was written by him.

**Comment by KEINOS** [comment]
@ids1024,
Oh, really?! My apologies. I'll fix it asap.

**Comment by KEINOS** [comment]
@ids1024
I fixed it. So, how about now? OK?
https://github.com/KEINOS/tiny-php-youtube-player

**Comment by ids1024** [comment]
That works.

**Comment by hrnr** [comment]
Hi, just revisiting all the issues mentioning MPRIS. I think this one can be closed as resolved.

**Comment by KEINOS** [comment]
Indeed! Sorry that I left this half-done. 🙇

**Comment by Vaishnavikumara** [comment]
Hi , I tried using playerctl to control mps-youtube which is triggered by a voice command . But playerctl is displaying "no players found". Please help @KEINOS @ids1024

**Comment by ritiek** [comment]
@Vaishnavikumara Are you using one of mpris supported players like mpv with mpsyt? If so, could you see whether or not playerctl works with Spotify GUI?
