### ISSUE TITLE
Song playback using mplayer cut short

### ISSUE THREAD

**Issue by patraulea** [mps-youtube/mps-youtube#569]
Just installed mpsyt 0.2.7.1 and youtube_dl 2016.12.18 via pip3 on an ubuntu-16.04. 

Searched and started playing a few playlists and each song playback is cut short after 1-3 min of playback , and playback continues to the next song. Using mpv as the player solves the issue. 

If I seek forward through the file towards and then let the song play towards the end, all is fine, playback is not interrupted.

Tried with mplayer 1.2.1 (standard ubuntu deb) and mpv 0.14.0 from ubuntu as well (ffmpeg 2.8.10-0ubuntu0.16.04.1).

**Comment by ids1024** [comment]
I would generally recommend mpv over mplayer. This is probably a bug in mplayer, and nothing to do with mpsyt specifically.

**Comment by patraulea** [comment]
So far so good, I only heard a single song cut short by mpv in a week and it may have been a download issue. Closing issue, thanks.
