### ISSUE TITLE
Keyboard shortcuts after installation?

### ISSUE THREAD

**Issue by orschiro** [mps-youtube/mps-youtube#575]
Dear all, 

I installed mps using pip on Ubuntu 16.10.

I expected my media hotkeys (e.g. Fn+F11) to work but they don't.

What do I have to do to control mps through my global hotkeys?

Yours,

-Robert

**Comment by ids1024** [comment]
I am assuming you are using Unity (the default desktop environment in Ubuntu). Did the installation create the file `/usr/share/applications/mps-youtube.desktop` (it should have)? Do you have the Python bindings for `dbus` and `gobject` installed?

**Comment by orschiro** [comment]
Thank you for your help!

Yes to all your questions.

I will further investigate this issue myself.

**Comment by ids1024** [comment]
That's odd then. I use Arch Linux, but the media menu integration has worked under Ubuntu for other people. The `.desktop` file was added specifically for Unity.

Anyway, this feature uses the mpris2 API that is implemented in the `mpris.py` file.

**Comment by orschiro** [comment]
Thank you for your useful information! 

I will see what I can do with it.

**Comment by orschiro** [comment]
Just to reference this. 

I came to use your script [1] and it serves me well to have keyboard hotkey support. 

Thank you! :-)

[1] https://gist.github.com/hrnr/43d926875577f6c3fd70
