### ISSUE TITLE
Unintitilized variable on finally block

### ISSUE THREAD

**Issue by xspager** [mps-youtube/mps-youtube#576]
Inside the *finally* block, line https://github.com/mps-youtube/mps-youtube/blob/develop/mps_youtube/player.py#L445 the variable **p** is undeclared, I suggest declaring it on https://github.com/mps-youtube/mps-youtube/blob/develop/mps_youtube/player.py#L364 as None. (sorry I'm to lazy to send a PR 😞 )

**Comment by ids1024** [comment]
Good point. Did you trigger this exception in some way (and if so, how?) or were you just looking at the code?

**Comment by xspager** [comment]
I triggered it, hard to replicate, I never managed to but happened enough to be annoying, I'm using omxplayer as the player on a RPi2, something to do with a combination of CTRL-C + "q" (to stop the player). Sorry took long for me to answer :(
