### ISSUE TITLE
unknown url type, can't play url or id

### ISSUE THREAD

**Issue by kudumi** [mps-youtube/mps-youtube#591]
I am getting the following error with both url and id: Mac OS (installed requirements with home-brew)

unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'

**Comment by ids1024** [comment]
Did you install youtube-dl? Does `mpsyt --version` show that it is using the youtube-dl backend?

**Comment by kudumi** [comment]
$ mpsyt --version
WARNING:root:pafy: youtube-dl not found; falling back to internal backend. This is not as well maintained as the youtube-dl backend. To hide this message, set the environmental variable PAFY_BACKEND to "internal".
mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.3.1 (internal backend)
Python version     : 3.6.0 (default, Feb  9 2017, 13:22:05) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
Processor          : i386
Machine type       : x86_64
Architecture       : 64bit, 
Platform           : Darwin-16.1.0-x86_64-i386-64bit
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /Users/username/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8

**Comment by kudumi** [comment]
$ which youtube-dl
/usr/local/bin/youtube-dl

**Comment by kudumi** [comment]
I didn't install youtube-dl along with mpsyt (I am having it for long time), how can I fix this? thanks

**Comment by ids1024** [comment]
If possible, install youtube-dl with pip3. Mpsyt calls it as a library, rather than calling the script.

**Comment by kudumi** [comment]
thanks, that solved the issue
