### ISSUE TITLE
(Option to) disable changing terminal window title

### ISSUE THREAD

**Issue by mtijink** [mps-youtube/mps-youtube#600]
I set my shell to create useful terminal titles, so it is annoying for me that MPS-youtube changes the title. I get that the default is useful for most people, but I use MPRIS for getting the song information, so that is not needed for me.

Could you add an option to disable changing the terminal window title?

**Comment by ids1024** [comment]
Hm, someone previously wanted this, and created a PR, but it was't merged because there was a better solution in their use-case: #498

I guess this can be added.

**Comment by ids1024** [comment]
I've merged that PR.

**Comment by mtijink** [comment]
Thanks!
