### ISSUE TITLE
mpsyt: command not found.

### ISSUE THREAD

**Issue by liutauras** [mps-youtube/mps-youtube#602]
I have installed older version of mpsyt from Ubuntu repo. And then installed new one with pip. Version remained old. I removed old mpsyt from Ubuntu packages. Repeated first steps on: https://github.com/np1/mps-youtube#installation

-bash: bash: /usr/bin/mpsyt: no file exists

pip install shows:
Successfully installed mps-youtube-0.2.7.1 pafy-0.5.3.1
Ubuntu 16.04

**Comment by wildefyr** [comment]
Installing mpsyt via pip on my system, its path is /usr/local/bin/mpsyt. Ensure /usr/local/bin is added your $PATH by typing `echo $PATH` in your shell.

**Comment by liutauras** [comment]
Thanks for idea for searching paths! **Solved!**

I found my mpsyt by **bash: locate mpsyt** in /home/USERNAME/.local/bin/mpsyt
So i added it to my path in ~/.bashrc file like this: 
**export PATH=$PATH:/home/USERNAME/.local/bin/**
