### ISSUE TITLE
Problem with sudo pip3 install dbus pygobject

### ISSUE THREAD

**Issue by orschiro** [mps-youtube/mps-youtube#604]
Dear all, 

I followed the installation instructions and performed the following command on Ubuntu 16.10:

    $  sudo pip3 install dbus pygobject

However, it results in the following error:

```
Collecting dbus
  Could not find a version that satisfies the requirement dbus (from versions: )
No matching distribution found for dbus
```

Any ideas what is happening here?

**Comment by orschiro** [comment]
Does the package have to be `dbus-python` instead of `dbus` maybe?

**Comment by ids1024** [comment]
> Does the package have to be dbus-python instead of dbus maybe?

It looks like you're right. That's a strange way to name the package... does it work after you install it that way?

**Comment by orschiro** [comment]
Dear Ian,

Yes, it dit work after installing `dbus-python`. :-)

**Comment by ids1024** [comment]
Thanks for pointing this out; I've updated the README accordingly.
