### ISSUE TITLE
Refactor player.py to be class based

### ISSUE THREAD

**Issue by ids1024** [mps-youtube/mps-youtube#610]
There should be a `Player` class, with `Mpv` and `Mplayer` sub-classes. This is cleaner and should help allow the addition of new back-ends, like  mpd (#168) or chromecast (#398 #607).

**Comment by georgeaueb13** [comment]
Hello, I am George Metaxopoulos!We had contacted you via email recently and you told us that we could do the refactoring as part of our semester project with another student(@panosgt7)Do you mind assigning it to us?
@ids1024

**Comment by catafest** [comment]
can you help me with this ?

https://github.com/mps-youtube/mps-youtube/issues/611

2017-03-31 14:34 GMT+03:00 georgeaueb13 <notifications@github.com>:

**Comment by ids1024** [comment]
@georgeaueb13 @panosgt7 It seems GitHub doesn't allow assigning an issue to someone who isn't a collaborator / member of the organization (which is annoying), but consider yourselves assigned.

**Comment by ata2001** [comment]
@georgeaueb13 Hi! Are you still working on this?

**Comment by georgeaueb13** [comment]
@ata2001 Hello! We got caught up with some university work the past few weeks. Starting tomorrow we will keep on working on the project and we hope to have everything done by the end of the month!

**Comment by ata2001** [comment]
@georgeaueb13 Thanks for the reply! Good luck!

**Comment by vn-ki** [comment]
This is closed in #753
