### ISSUE TITLE
Accomodate white terminal backgrounds

### ISSUE THREAD

**Issue by tmerr** [mps-youtube/mps-youtube#613]
mpsyt's help text is written in yellow which is unreadable if you have a white terminal bg. I solved this problem for myself by editing the installed c.py, but I know once I upgrade this change will be overwritten. Is there any interest in accomodating white terminal backgrounds?

Some possible solutions:
* automatically change the bg color to black (and default fg color to white) while mpsyt is running
* adjust the color scheme to never use yellow
* allow the user to disable colors
* offer a light color scheme

**Comment by ids1024** [comment]
Yeah, it's probably best to handle this in some way, but I don't know what would be best. Are the colors alright except for the yellow, or could they still use some improvement?

**Comment by ata2001** [comment]
I think support for colorschemes would be the best.

There would be one for dark and one for white bg by default, but the users could create custom ones. (for example: solarized)

**Comment by tmerr** [comment]
@ids1024 The other colors seem readable enough. It could be better by eliminating green, but I personally don't care so much: Just switching yellow to something else would make me a happy user. Maybe others can chime in if they have stronger feelings.

**Comment by LittleWhite-tb** [comment]
I have looked at this problem, since I had it myself. I ended by changing the colors used by my terminal emulator (was mate-terminal). I thought this was a better way to fix it, since even `ls` could use some colours that I could not distinguish (green). Same for nano.

**Comment by tmerr** [comment]
@LittleWhite-tb Yeah, I did some digging and it looks like there are many ways to work around this that don't involve editing mpsyt. For example even if you like white backgrounds you could change how standard yellow and green are displayed to make them legible http://unix.stackexchange.com/a/19221. Even easier, you can special case mpsyt to run with a black bg by adding a line to your .bashrc. If you use xterm like me:

`alias mpsyt='xterm -fg white -bg black -e mpsyt &'`

Closing since I am more than happy with this solution. I'd rather standardize on the same background as everyone else than add a layer of indirection to mpsyt to support color schemes, or degrade other users' experiences by eliminating colors that inconvenience me :)
