### ISSUE TITLE
Format of debug log file

### ISSUE THREAD

**Issue by Vrihub** [mps-youtube/mps-youtube#617]
I've run mpsyt with the `--debug` option, but all I get in the `/tmp/mpsyt.log` file is a bunch of lines like:

    DEBUG:root:<generator object dbg.<locals>.<genexpr> at 0x7fec1ac7f048>
    ...

Is this intended behaviour? Or maybe I need to install some python modules to have a more human-friendly output format?

**Comment by ids1024** [comment]
Oh, it looks like I broke logging at some point. Thanks for pointing this out.

48787b189d83299a7489b4e19119974e0dac4b24 fixes itt.
