### ISSUE TITLE
mpsyt should reset comments current page when switching to comments of another video

### ISSUE THREAD

**Issue by Vrihub** [mps-youtube/mps-youtube#625]
How to reproduce:

1. See comments for a video with multiple comment pages, e.g. `c 1`
1. Press `n` some times to see next comment pages
1. See comments for another video that has **less** comment pages, e.g. `c 3`

Expected result: get the first page of comments for video 3

Actual result: a blank screen; but if you press `p` several times, you finally get comments for video 3.

It seems that mpsyt remembers the current comment page from video 1, and displays the same comment page for video 3, but since this has less comments, you get a blank page.

**Comment by Vrihub** [comment]
BTW maybe fixing this bug would also help fixing #522

**Comment by ids1024** [comment]
8c38fc74ee7d37adff2231bacc31a694eedee8a5 should fix this.

**Comment by Vrihub** [comment]
> 8c38fc7 should fix this.

Yes, thanks a lot.
