### ISSUE TITLE
[Feature request] Add filter by duration to select long (duration) videos

### ISSUE THREAD

**Issue by sebma** [mps-youtube/mps-youtube#629]
Hi,

First let me congratulate you for your great tool.

I was searching for a SMTube replacement for MacOSX and I found your software 👍 

Can you add the possibility to select long (duration) videos in search results ?

**Comment by jas32096** [comment]
This feature already exists on the development branch

**Comment by jas32096** [comment]
`-d long`

**Comment by sebma** [comment]
Coming in next release 0.2.8 I suppose ?

Approximately when do you think you will release it ?

**Comment by jas32096** [comment]
I'm just a contributor on the repo, so it's not up to me to decide. In the meantime, you can just point pip at the repo.

`pip3 install --upgrade git+https://github.com/mps-youtube/mps-youtube.git`

**Comment by sebma** [comment]
Do you have the equivalent command with `brew` ?

**Comment by jas32096** [comment]
There isn't one

**Comment by sebma** [comment]
Ok.

Thanks a lot for your help.

As I much as I don't like using pip upgrade (I've had issues with package dependencies because unnecessary packages were upgraded in the process), I'll try and use it.

**Comment by eMPee584** [comment]
> `-d long`

And where do I actually put these search arguments? there's not a single usage example to be found..
I tried and `/zimmz -d long` seems to not make a difference neither `search -d long zimmz` :thinking:

**Comment by jas32096** [comment]
@eMPee584 The new maintainer removed the feature two years ago https://github.com/mps-youtube/yewtube/blame/0c1e39d51f5d4c6e1bea25b72c00900aab991e37/mps_youtube/commands/search.py#L299

**Comment by iamtalhaasghar** [comment]
Sorry guys if i broke anything. If i have removed it most probably it would be due to the reason that filtering video by duration can't be done without youtube api. Lets add it again if that's not the case.
