### ISSUE TITLE
stop mpsyt when chrome plays something

### ISSUE THREAD

**Issue by nurulmac11** [mps-youtube/mps-youtube#632]
I am trying to code this since a couple of days. Firstly, Pulseaudio (python pulsectl library) give me an info of whether chrome plays something or not but when google chrome stopped playing, pulseaudio retrieves this info too late, about 10 secs. So, i decided to jump google chrome extensions. I wrote a extension with chrome.tabs library. It stores of info whether there is any tab is playing sound or not in sqlite3 db. (~/.config/google-chrome/Default/Local Storage/extension -key) But when i tried to check this with python sqlite lib, as expected, python give me an error that sqlite db is locked, when chrome is changing the value.
So I blocked at this point. As far as I know I can't create any file with chrome extension. If I could, I would check if there is a file that indicate chrome plays something(produced with my extension) with python.
Is there something else to do this ?

**Comment by ids1024** [comment]
Interesting question. I'm not sure what the best way to do this would be since I'm not really familiar with chrome extensions, but this may be helpful: https://developer.chrome.com/extensions/nativeMessaging

**Comment by ids1024** [comment]
Oh, and I don't know how you are implementing the Python part, but I recommend using the mpris2 API; that way it can be separate from mpsyt and will also work with other mpris2-compatible media players.

**Comment by nurulmac11** [comment]
thanks, I will check that lib. Yes, I am using kinda mpris with dbus. [Here is my python code.
](https://gist.github.com/nurulmac11/b6c0035ceaf17bb1a43fdf8d0e65b4e1)

**Comment by nurulmac11** [comment]
I think i solved this problem in a very fancy way  :D I set up an [django server with python.](https://gist.github.com/nurulmac11/b6c0035ceaf17bb1a43fdf8d0e65b4e1). then a[ chrome extension ](https://gist.github.com/nurulmac11/33b5fc2ff7151a2ac544e87489adde71) that triggers django every play or stop.
