### ISSUE TITLE
Error when playing songs

### ISSUE THREAD

**Issue by kodemaan** [mps-youtube/mps-youtube#636]
When I try and play a song I get the following error message:
```youtube_dl.utils.ExtractorError: Unsupported JS expression \'oE["do"](a,67)\'; please report issue on https://yt-dl.org/bug```
Here's a screen-capture of the issue. 
https://asciinema.org/a/4ep0w61uw3ka9uhc5slywuc9o

If this is a youtube-dl bug then I can post there too but this was working this morning and now it's not so I thought it might be some youtube change or similar

**Comment by Razesdark** [comment]
Hi. This is indeed a bug with the `youtube-dl` library. However, it was patched a few hours ago.

You can most likely fix this problem by upgrading it through pip, by running `pip install -U youtube-dl`

**Comment by kodemaan** [comment]
Running that worked, thanks
