### ISSUE TITLE
Requesting up to date Windows Build

### ISSUE THREAD

**Issue by jbfleury56** [mps-youtube/mps-youtube#637]
Hi, I would like to know if it was possible to make a more up to date .exe standalone based on the develop branch. I would also be very interested in some in-depth documentation on how to compile mps-yt into a standalone .exe myself so I could keep it up-to-date on my system.
Thanks a lot for your awesome software!

**Comment by ewwink** [comment]
download python < 3.4 then run command
```
cd mpsyt-dir
pip install py2exe
python setup.py install
python setup.py py2exe
```

**Comment by jbfleury56** [comment]
thanks a bunch, will try that!
