### ISSUE TITLE
Python bad interpreter

### ISSUE THREAD

**Issue by justijndepover** [mps-youtube/mps-youtube#641]
OS: macOS Sierra 10.12.5

I recently did a brew update and since then i cannot open mpsyt.
Whenever I try i get the following error:
```sh
zsh: /usr/local/bin/mpsyt: bad interpreter: /usr/local/opt/python3/bin/python3.5: no such file or directory
```

If i do `python --version` i get `Python 2.7.10`.
If i do `python3 --version` i get `Python 3.6.1`.

`which python` gave me `/usr/bin/python`

I'm not an expert with all the brew packages and so on but I think i have installed multiple versions of python.

`usr/bin` contains a python file.
`usr/local/bin` contains a `python` symlink, a `python2` symlink, a `python2.7` symlink, a `python3` symlink, a `python3.6` symlink, and a `python 3.6m` symlink.

obviously 3.5 is missing here. So if i install that one the program would work again. But do i need to have all these versions of python? Can't i just keep the latest version?

**Comment by Razesdark** [comment]
Hi, I don't run OS X so I can't check this bug out myself. Python2 and 3 are not fully compatible so having both a v2 and v3 might be needed depending on what software relies on it.

AFAIK, 3.5 and 3.6 are the same so you could probably link your python3.6 from /usr/local/bin, using `ln -s /usr/local/bin/python3.6 /usr/local/opt/python3/bin/python3.5` (might need to be sudoed)

**Comment by justijndepover** [comment]
Thanks for the reply! But why is my system trying to use 3.5? I don't see it explicitly set in the source code.

**Comment by ids1024** [comment]
How did you install mpsyt? You can try reinstalling it.

**Comment by justijndepover** [comment]
I installed it like this: 
```
[sudo] pip3 install mps-youtube
```

I also tried to create the symlink that @Razesdark suggested. If i run `mpsyt` now i get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 7, in <module>
    from mps_youtube import main
ModuleNotFoundError: No module named 'mps_youtube'
```

**Comment by justijndepover** [comment]
Allright this is getting messy.
I uninstalled mpsyt by removing the file in `/usr/local/bin`. Then if i try to reinstall it pip says: 

```sh
Collecting mpsyt
  Could not find a version that satisfies the requirement mpsyt (from versions: )
No matching distribution found for mpsyt
```

**Comment by ids1024** [comment]
It should be `pip3 install mps-youtube`

**Comment by Razesdark** [comment]
The package is called mps-youtube, not mpsyt

**Comment by justijndepover** [comment]
Oops my bad!

Now it works so thank you!
