### ISSUE TITLE
ssl cert error due to sshutle proxyish thing

### ISSUE THREAD

**Issue by SlightlyCyborg** [mps-youtube/mps-youtube#643]
Hello. I am getting an SSL cert error because I am using sshuttle to transparently proxy all traffic through a server (which has 2 network cards, with one able to connect to a wan). Is there a way to deactivate the checking of SSL certs?

**Comment by ids1024** [comment]
You probably would have to patch mps-youtube, using something like this: https://stackoverflow.com/questions/33770129/how-do-i-disable-the-ssl-check-in-python-3-x

**Comment by SlightlyCyborg** [comment]
Ok.
