### ISSUE TITLE
[Bug] Can't play videos on Mac

### ISSUE THREAD

**Issue by piotryordanov** [mps-youtube/mps-youtube#644]
Hello, I'm on mac.

I installed mpsyt, youtube-dl and mpv using pip3. 
I can succesfully download videos, but I can't play them. When I do, the screen flashes and sends me back to the search result page.

Any idea what else I can do to debug?
Thanks!

**Comment by Razesdark** [comment]
You can run `mpsyt --debug` to get more debug information.

**Comment by piotryordanov** [comment]
I did, and it doesn't really show any error message.
<img width="1280" alt="screen shot 2017-06-08 at 5 29 57 pm" src="https://user-images.githubusercontent.com/753950/26924446-1f32c50c-4c70-11e7-92da-17f1f2a1b6e7.png">

**Comment by Razesdark** [comment]
Which player have you set? Could you post your mpsyt version information, that pops up when you start mpsyt in debug mode?

**Comment by piotryordanov** [comment]
Ok, so it looks like when I set player as `mplayer` then the bug happens. Do I need to install mplayer via pip3?

When I set it to `mpv` everything works fine, but I only get audio. Am i supposed to be able to see the video or audio only?

**Comment by piotryordanov** [comment]
Nevermind, I figured out how to play videos with `set show_video true` from the FAQ. (Would be nice to have that on the README page :))

Is there a way to retried the latest video based on release date? For example, on youtube.com I can filter videos from last week only.

**Comment by Razesdark** [comment]
I don't run OSX so I can't tell you where to download mplayer, I assume it's on homebrew.

You can use the argument `--after YYYY-MM-DD` format to search for movies released after a certain date. You can also use `set order date` to order results by date

**Comment by piotryordanov** [comment]
Well, it looks like the problem is from mplayer. I'll just stick to `mpv`. 

Thx for the sorting tip and for the great repo :)

**Comment by piotryordanov** [comment]
Btw, is there a way to `set order date` but then display videos with `views > 1,000` (or any other number) ?

**Comment by Razesdark** [comment]
Sorry, but at the moment there are no options in the youtube api for searching based on number of views and doing it client side.

**Comment by piotryordanov** [comment]
No worries!
