### ISSUE TITLE
mpsyt crash with latest develop branch

### ISSUE THREAD

**Issue by uNouss** [mps-youtube/mps-youtube#651]
hello i update mps-youtube to last develop version branch and now it dosnt work and i have this issue https://asciinema.org/a/bmwpg8laebtn4c10qyi9ic9g7

**Comment by ids1024** [comment]
https://github.com/mps-youtube/mps-youtube/commit/e10030b336e15a774dc83c9f603a6bbfc41cf64d should fix this.

**Comment by uNouss** [comment]
yes, thank you ^^
