### ISSUE TITLE
Syntax error, using Windows standalone

### ISSUE THREAD

**Issue by GHExplorer** [mps-youtube/mps-youtube#661]
Hi,

When I run the standalone Windows version and type help, no problem.  But when I type in a command, like basic or search, it returns 

  'Bad syntax.  Enter h for help

![helpscreen_20170724](https://user-images.githubusercontent.com/4349455/28523700-99e3fe3e-704b-11e7-9335-77f58ec2cf5d.jpg)
![typebasic_beforeenter_20170724](https://user-images.githubusercontent.com/4349455/28523712-a5bc2ca4-704b-11e7-90fb-545ec850f82f.jpg)
![after_typingbasic_and_pressing_enter](https://user-images.githubusercontent.com/4349455/28523722-ab50f500-704b-11e7-8514-c60e6ebe29bf.jpg)

Should I be downloading some supporting library or dlls?

**Comment by ritiek** [comment]
It says:
> Enter help \<topic\> for specific help:

You need to type, for example:
`help basic`, `help search`, etc.

**Comment by GHExplorer** [comment]
Got it, thanks ritiek.
