### ISSUE TITLE
mpsyt crash with some search

### ISSUE THREAD

**Issue by uNouss** [mps-youtube/mps-youtube#665]
hey, mpsyt crash if i try to search some song 
here how to reproduce this issue https://asciinema.org/a/yQtVhb55iVWXp4U98pB0M0irq

**Comment by ritiek** [comment]
Duplicate of #663. This should be fixed on the `develop` branch (#664). Can you confirm?

**Comment by uNouss** [comment]
the `develop` branch fix this issue for me. thank you, sorry for the duplicate
