### ISSUE TITLE
History extraction

### ISSUE THREAD

**Issue by sigismund** [mps-youtube/mps-youtube#667]
Is there anyway for me to extract (and later download) all history without manually browsing through all pages?

**Comment by kraetzin** [comment]
There isn't an in-app way to do it, but you can unpickle the `play_history` file and wrangle it into a human readable one. Something (hacky) like this would work:
```python
import pickle
history = pickle.load(open('play_history', 'rb'))['history']
with open('human_history.txt', 'w') as f:                                     
    for song in history.songs:
        f.write("%s %s\n" % (song.ytid, song.title))
```
This would write the Youtube ID and song title of every song in your history to `human_history.txt`.

I may have a go at implementing a proper `history export` function for mpsyt if I get time.

**Comment by sigismund** [comment]
Thank you for this snippet. I really appreciate it.
