### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by JPRuehmann** [mps-youtube/mps-youtube#670]
If I try to update mpsyt i get the following error.
updating setuptools not worked
sudo -H pip install https://github.com/mps-youtube/pafy/archive/develop.zip https://github.com/mps-youtube/mps-youtube/archive/develop.zip not working either
sudo apt remove python-pip no help
pip3 check mps-youtube No broken requirements found.
```
sudo -H pip3 install mps-youtube --upgrade                                                                                                                       Collecting mps-youtube
  Using cached mps-youtube-0.2.7.1.tar.gz
    Complete output from command python setup.py egg_info:
    Mps-youtube requires python 3.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-yMIFaV/mps-youtube/
```
what can I do to make it work?
thanks,

**Comment by ritiek** [comment]
It seems like `pip3` is invoking `python 2`. What is the output of `pip3 -V`?

**Comment by JPRuehmann** [comment]
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

**Comment by JPRuehmann** [comment]
python3 -m pip install did the Trick
