### ISSUE TITLE
Problem playing album tracks

### ISSUE THREAD

**Issue by mhoffstang** [mps-youtube/mps-youtube#672]
I just searched an album, it got matched nicely and it displays all the tracks. If I want to play one of them, I just get the following error:

Problem playing last item: [Errno 2] No such file or directory

**Comment by ritiek** [comment]
I just tried it. It plays the album songs okay for me but if I `KeyboardInterrupt` while the song plays, it gives me an error message:

> Problem playing last item: [Errno 2] No such file or directory: 'tset'

However, everything works as expected.

Is this the problem you are talking about?

**Comment by mhoffstang** [comment]
not exactly, I can't start playing a song. I just let it search for the album and then type the number of the song I want to play and get the error message. 
I tried another album and now it works

**Comment by ritiek** [comment]
Just for the note, this problem occurs when you delete the location you ran `mpsyt` from.
