### ISSUE TITLE
KeyboardInterrupt: No such file or directory: 'tset'

### ISSUE THREAD

**Issue by ritiek** [mps-youtube/mps-youtube#673]
When using `mpsyt` on Android with Termux, sending `KeyboardInterrupt` when a song is playing gives:

> Problem playing last item: [Errno 2] No such file or directory 'tset'

However, everything works as expected. Problem is just this annoying string of error shown every time.

**Specs:**

mps-youtube on git develop
Python 3.6.2
OnePlus 2 (android 6.0.1)

**Comment by ids1024** [comment]
The `tset` command seems to be part of ncurses, so it's not surprising an android system wouldn't have it.

It is easy enough to get it to just not run that command on a system without it, but I think that likely will cause problems...

**Comment by ritiek** [comment]
Thanks for letting me know that. `apt-get install ncurses-utils` fixed it for me.
