### ISSUE TITLE
Volume default at 50%

### ISSUE THREAD

**Issue by demogorgonz** [mps-youtube/mps-youtube#676]
Hello,

Volume default reset to 50% on every song change.

How could i set it to higher percentage ?

**Comment by ids1024** [comment]
Mpsyt uses `mplayer` or `mpv` as a backend; you should be able to set this in their configuration files, or in mpsyt by setting `playerargs`.

For example, `set playerargs --volume=75` works for me, with mpv as a backend.

**Comment by demogorgonz** [comment]
Thank you! :+1:
