### ISSUE TITLE
Playback stops randomly

### ISSUE THREAD

**Issue by notmike-5** [mps-youtube/mps-youtube#692]
I checked other issues and saw that audio playback was stopping after 2mins or so. I am having similar issue, however I often get beyond 2mins (even up to 75% of a song) before the file stops playing. mpsyt does not crash.

As it seemed old packages may have been at fault in previous issues, I have run `pip/pip3 install mps-youtube` and ensured that mpv is installed. This has not resolved the issue.

**Comment by ritiek** [comment]
Did you set the player to mpv using `set player mpv` in `mpsyt`? Also make sure your `youtube-dl` is up to date.

If still no luck, does the playback stop with the below command as well?

```
$ mpv --no-video https://link/to/freezing/youtube/video
```

(You can get the YT link for a song by running `i <number>` before starting the playback in `mpsyt`)

**Comment by notmike-5** [comment]
Setting the player to mpv with `set player mpv` resolved the issue! Thank you!
