### ISSUE TITLE
Media Keys not working on i3wm using playerctl

### ISSUE THREAD

**Issue by Drakota** [mps-youtube/mps-youtube#700]
Hey guys, I've looked over at #303 and I'm using playerctl with the same i3 config has the guy in the issue, but I still get `Connection to player failed: No players found` when trying to pause with mpv open with a video, what am I missing?

**Comment by ids1024** [comment]
You need the Python dbus and gobject libraries for mpris2 support. Perhaps that's the issue?

**Comment by Drakota** [comment]
I have `python2-dbus`, `python-gobject` installed, can you point me to the exact packages needed for mpris2 support? Because there are tons of them.

**Comment by ids1024** [comment]
Mpsyt uses Python 3; so `python-dbus` and `python-gobject` should do.

**Comment by Drakota** [comment]
Installing `python-dbus` did the trick, thanks!

**Comment by amacfie** [comment]
> Mpsyt uses Python 3; so `python-dbus` and `python-gobject` should do.

Should those be installed automatically with mps-youtube?
