### ISSUE TITLE
Play the next song if currently is forbidden

### ISSUE THREAD

**Issue by pararang** [mps-youtube/mps-youtube#724]
Hi,
I often got the `HTTP Error 403: Forbidden` while playing a song from a playlist search result. I am used to playing all the song from the playlist and once a song got forbidden error the playlist will stop. Can we make it if play all mode and one of the song is forbidden then it is will automatically play the next song in the playlist?

**Comment by ritiek** [comment]
I'd want this to work for other errors as well that includes `video removed by author`, `video no longer available due to copyright claim`, etc.
