### ISSUE TITLE
Play all does not play music on other pages

### ISSUE THREAD

**Issue by ritiek** [mps-youtube/mps-youtube#726]
If we are in a playlist consisting of multiple pages. The command `all` or `*` plays all the songs from the current page and ignores songs on the pages. There should be way to play every song in the playlist irrespective of current active page number.

**Comment by kraetzin** [comment]
This is already possible. If you use the `dump` command with the playlist open,  `all` or `*` will play all the pages.

**Comment by ritiek** [comment]
Thanks, it works indeed! Didn't know about the `dump` command until now.
