### ISSUE TITLE
What is the difference between `view` and `open` commands?

### ISSUE THREAD

**Issue by ritiek** [mps-youtube/mps-youtube#735]
I took a look at the code in here

https://github.com/mps-youtube/mps-youtube/blob/8cf7c7313b494852b10f0f5cd13fdf5307150a3c/mps_youtube/commands/local_playlist.py#L121-L142

It looks like that it makes the tracks in a playlist *active* when using `open`, but I can do everything with `view` as well, play tracks, save playlist, etc.

Is there supposed to be a difference between them or is this an unexpected behavior?

**Comment by ids1024** [comment]
Yes, this seems to be a bug.

**Comment by ids1024** [comment]
Oh, actually I think this is the intended behaviour; specifically, commands like `vp` return to the one that has been 'opened'. It's not really a feature I use... Sorry for the confusion.

I guess mpsyt has several commands that don't have very obvious behaviour...

**Comment by ritiek** [comment]
I am not sure if `vp` and `view` intend the same behavior. But if this is really the case and they have no difference between them, should we just use `if action in ("open", "view")` and merge their code below?

https://github.com/mps-youtube/mps-youtube/blob/8cf7c7313b494852b10f0f5cd13fdf5307150a3c/mps_youtube/commands/local_playlist.py#L127-L146

By the way, I am not sure how `g.last_opened` in above code works. It gets replaced when `paginate()` is called without doing any thing useful, I guess?

https://github.com/mps-youtube/mps-youtube/blob/8cf7c7313b494852b10f0f5cd13fdf5307150a3c/mps_youtube/commands/songlist.py#L67-L71

> It's not really a feature I use... Sorry for the confusion.

It's no problem. I don't use it much either but was curious to reach out the lesser used areas and found this issue. :smile:

**Comment by Razesdark** [comment]
I tested it earlier and it looks like it works as intended now.

try opening a playlist with `open n`, then view another with `view m`, by using the `vp` command, I was taken back to the *n* playlist.

**Comment by ritiek** [comment]
Oh yeah, I get it now. 

Works as expected for me now as well, thanks for clarification @Razesdark.
