### ISSUE TITLE
Feature Request: Introduce song/playlist repeat functionality

### ISSUE THREAD

**Issue by anjannath** [mps-youtube/mps-youtube#751]
## Issue / Suggestion

VLC/mps players support repeat functionality, __mpsyt__ should have an option/key in the TUI for that.
 I mostly use __mps__ since i only use it to listen to songs, it's kind of my spotify replacement.

**Comment by vn-ki** [comment]
Use `repeat <song_number>` and `repeat all`(in the case of playlists). Please close this issue.

**Comment by anjannath** [comment]
Thanks @vn-ki :) closing this, BTW where is this documented?

**Comment by vn-ki** [comment]
I don't think it's documented anywhere. I have played around the player code in mpsyt. That's how I discovered this option.
