### ISSUE TITLE
GNOME displaying playback twice (mps and mpv)

### ISSUE THREAD

**Issue by orschiro** [mps-youtube/mps-youtube#780]
Hey guys, 

I have set my player to mpv. Now GNOME does display two entries for the playback. 

One for mps and one for mpv. Do you have any ideas how to hide one of the two?

Ideally the one without the thumbnail and the cryptic file name. :-)

Adding some screenshots. Tested with mpsyt 2.7.1 on Fedora 27.

Thanks!

![image](https://user-images.githubusercontent.com/170947/36253521-16913476-1248-11e8-9801-142cc1b231b8.png)

![image](https://user-images.githubusercontent.com/170947/36253535-1bd91a70-1248-11e8-816a-4b5e9306eb72.png)

**Comment by hrnr** [comment]
From mps-youtube side you should be able to disable mpris with `set mpris 0`. You need to have the latest version. Unfortunately that is the version with thumbnail, title etc.

For mpv I don't know, but as far as I know MPRIS is not supported by mpv out of the box. You probably have either lua plugin or mpv-mpris c plugin installed for mpv.

**Comment by orschiro** [comment]
> For mpv I don't know, but as far as I know MPRIS is not supported by mpv out of the box. You probably have either lua plugin or mpv-mpris c plugin installed for mpv.

Great catch! Thanks for reminding me. I installed this: https://github.com/hoyon/mpv-mpris#install

Let me do some more testing...

**Comment by orschiro** [comment]
Disabling the mpv mpris plugin worked. Thanks so much for the good hint!

![image](https://user-images.githubusercontent.com/170947/36268470-d6dd5984-1276-11e8-8945-5c670ea9405e.png)
