### ISSUE TITLE
Tab completion for commands

### ISSUE THREAD

**Issue by ZaxonXP** [mps-youtube/mps-youtube#783]
It would be nice if mps-youtube could allow to expand the commands when TAB key is pressed. 

## Suggestion
As Linux user I am famillar with the tab expansion, which is a nice feature. This feature is somehow missing in mps-youtube and it would be usefull. 

For instance 
`set pl<TAB>`
should display
`set player`
pressing <TAB> second time should display
`set playerargs`

## Your Environment
mpsyt 0.2.8
Android 6.0.1 (CM13)
mpv

**Comment by orschiro** [comment]
Coming from #786, are we talking about the same autocompletion here? 

My suggestion was autocompletion for mpsyt itself, like commands like `mpsyt playurl`.

This is about autocompletion inside mpsyt itself.

Does it make a difference?

**Comment by vn-ki** [comment]
If we are implementing one, why not implement both. ^_^

**Comment by orschiro** [comment]
Haha sure, just wasn't sure if we were talking about the same issue here but good to know we do. ;-)

**Comment by vn-ki** [comment]
@orschiro You should reopen your other issue. I just googled and the implementation of one is totally different than the other.

So it's better to have separate issues. Sorry for making you close your issue.

**Comment by orschiro** [comment]
Cool, thanks for implementing the tab completion! :-)
