### ISSUE TITLE
Terminal garbled output when using mpsyt playurl

### ISSUE THREAD

**Issue by orschiro** [mps-youtube/mps-youtube#784]
Hey guys, 

Not sure if there is anything we can do about it but when you use mpsyt playurl on GNOME Terminal, it doesn't properly update/refresh the displayed content and at some point it's just a bit of an inline garble.

Tried capturing this with the following GIF. Has anyone else had similar problems?

Thanks!

![peek 2018-02-21 12-55](https://user-images.githubusercontent.com/170947/36478875-ccc2e358-1706-11e8-86ea-415a2e8fc61a.gif)

**Comment by Razesdark** [comment]
I'm just going to close this, as it looks like it was related to the other referenced issue.

If you still have this issue, just let me know and I'll open it again.
