### ISSUE TITLE
Can't play music

### ISSUE THREAD

**Issue by floowsnaake** [mps-youtube/mps-youtube#792]
hi

so anytime i try do a /search and i press like 1 to play it it shows that it its playing for like 2 seconds then it stops and goes back to the selection screen again.

picture: 
https://ibb.co/cuYL0x

mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2018.02.22
Python version     : 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-4.10.0-38-generic-x86_64-with-LinuxMint-18.3-sylvia
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/snow/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8
env:LANGUAGE       : en_US

**Comment by ritiek** [comment]
Maybe related to #752?

**Comment by Vrihub** [comment]
> Maybe related to #752?

I'd say yes. I've also experienced this problem after updating to 0.2.8.
The patch mentioned here https://github.com/mps-youtube/mps-youtube/issues/752#issuecomment-368243826 fixed the problem for me (linux, python 3.5.3)
