### ISSUE TITLE
Songs constantly going to next one

### ISSUE THREAD

**Issue by VonKavalier** [mps-youtube/mps-youtube#808]
## Issue / Suggestion
Since the last update, 90% of the musics I wanna listen just don't start, without error message and pass to the next one until eventually one finally starts.
I reset the config to default but it didn't change anything.

## Your Environment
mpsyt version      : 0.2.8
notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2018.02.11
Python version     : 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-4.13.0-36-generic-x86_64-with-Zorin-12-xenial
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/dnd-von/.config/mps-youtube
env:TERM           : xterm
env:SHELL          : /usr/bin/zsh
env:LANG           : en_US.UTF-8
env:LANGUAGE       : en_US

I use mpv 0.14.0 as player.

It worked perfectly before the update

**Comment by rosenb0rg** [comment]
I'm having the same issue

**Comment by VonKavalier** [comment]
Here's a temporary fix, which is going with previous version.

`sudo pip3 uninstall mps-youtube #First you need to uninstall it`
`sudo pip3 install mps-youtube==0.2.7 #And then reinstall it by specifying previous version`

**Comment by vn-ki** [comment]
Please provide logs.

**Comment by flotisable** [comment]
I have the same problem that some youtube music can not play.
but solved by updating python to 3.6.
maybe there are some code can not work in older version of python?

**Comment by vn-ki** [comment]
Probably related to #752 then. 

@ids1024 You should probably push that commit to master and make a new release.

**Comment by vn-ki** [comment]
Probably related to #752 then. 

@ids1024 You should probably push that commit to master and make a new release.  Ref: https://github.com/mps-youtube/mps-youtube/commit/d0a3eee3962596dd3ef1f26d7b5f2f2ed812f6a4

**Comment by Razesdark** [comment]
Closing since it looks like this has been resolved
