### ISSUE TITLE
Shuffle mode

### ISSUE THREAD

**Issue by ariSunz** [mps-youtube/mps-youtube#809]
Something that would be perfect for frequent playlists is a shuffle mode so it doesn't feel exactly the same every time you open it, with the order of the videos appearing scrambled.

For example, when you open a playlist and `dump` it, there could be a similar `shuffle-dump` command to randomly scramble the order of the videos in the playlist.

Currently running 0.2.8 from pip, sorry if something like this is already in place here on git.

**Comment by vn-ki** [comment]
Use `shuffle all`

**Comment by ariSunz** [comment]
Damn, I should've looked better. Sorry and thank you.

**Comment by vn-ki** [comment]
Please close this if your issue has been resolved! ^_^
