### ISSUE TITLE
[request] image support!!!!

### ISSUE THREAD

**Issue by pirate486743186** [mps-youtube/mps-youtube#817]
This is not a joke.
You CAN have images directly INSIDE the terminal.
In the Linux world any way....
Yes, in simple tty...
The programs wright directly in the video frame buffer (no X).
Apparently, not all terminals can do this.

examples:
text based web browser w3m
how wikipedia looks like in it with images(yes, it's in the terminal)
https://upload.wikimedia.org/wikipedia/commons/6/62/W3m-wikipedia.png
In ubuntu (linux) you need to install
sudo apt install w3m w3m-img

there's also an image viewer "fbi"
and also a pdf viewer fbgs
mplayer can do it like this in my system
(it wants you to be in the video group blablabla, just use sudo)
sudo mplayer -vo fbdev2 $video

and certainly others....

**Comment by ritiek** [comment]
You should be able to set default arguments for your player in mpsyt.

For mplayer:
```
> set playerargs -vo fbdev2
```

For mpv:
```
> set playerargs -vo drm
```

This should be it I guess but I think you might have to use sudo to launch mpsyt for video to work properly.

**Comment by pirate486743186** [comment]
-_- i was so unclear?

yes yes, i know about the players and the set option....
like i said , you need to be in the video group, to avoid using sudo.....

I'm saying, you can have images directly inside the terminal (not all terminals can do that, the tty can)
Just install "w3m w3m-img" to see what i mean
here's wikipedia in w3m with images
https://upload.wikimedia.org/wikipedia/commons/6/62/W3m-wikipedia.png

**Comment by ReekyMarko** [comment]
You are a bit unclear what you want. You are only saying that you can "have images directly inside the terminal". Do you want thumbnail support or something else?

**Comment by thomasgroch** [comment]
Adoraria ver uma integração de images no termial, existem diversas CLI's que podem view images from the terminal. 👍 

Poderia ser configuravel
`config set render [viu](https://github.com/atanunq/viu)`
