### ISSUE TITLE
Installation problems mpsyt not found

### ISSUE THREAD

**Issue by amodeo12** [mps-youtube/mps-youtube#818]
Hi everyone,

After installing mps-youtube in RPi with Raspbian Jessie following the instructions (with pip3) I try to execute it and I get the error:

-bash: mpsyt: command not found

I have also installed youtube-dl and tried to include the path /usr/local/bin in $PATH (not sure if I did it correctly though). I have reinstalled several times, in some of them I didn't get the error, but it didn't start anyway, just prompted for a while and when I interrupted with Ctrl+C I got some library error related with youtube-dl.

Just ask if you any other information. Thank you in advance

EDIT:

After another reinstallation I am getting the error when I make Keyboard Interrupt, it says:

CTraceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 7, in <module>
    from mps_youtube import main
  File "/home/pi/.local/lib/python3.5/site-packages/mps_youtube/__init__.py", line 8, in <module>
    init.init()
  File "/home/pi/.local/lib/python3.5/site-packages/mps_youtube/init.py", line 67, in init
    load_player_info(config.PLAYER.get)
  File "/home/pi/.local/lib/python3.5/site-packages/mps_youtube/util.py", line 408, in load_player_info
    g.mpv_version = _get_mpv_version(player)
  File "/home/pi/.local/lib/python3.5/site-packages/mps_youtube/util.py", line 446, in _get_mpv_version
    o = subprocess.check_output([exename, "--version"]).decode()
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1244, in _execute_child
    part = os.read(errpipe_read, 50000)
KeyboardInterrupt

**Comment by Rom1deTroyes** [comment]
Le dimanche 01 avril 2018 à 02:26:37 (-0700), amodeo12 a écrit :
> Hi everyone,

Hello !

> After installing mps-youtube in RPi with Raspbian Jessie following
> the instructions (with pip3) I try to execute it and I get the error:

Can you tell what the output of :
$ mpsyt -v
$ python -V
$ pip -V

If your system use python Python 2.7, you will not see things installed
with pip3, but only thoses installed with pip2 !

++
    Romain
-- 
si l'abbé Reumaux dit
dix mots, rebelle à six :
syllabaire maudit !
dîme au rebelle assis.
		-- Schulz, Rémi

**Comment by vn-ki** [comment]
mpsyt has incredibly slow startup time on a RPi (I have been there). It usually takes around 15 seconds on my RPi 2, but I have seen it taking up to 30 seconds to just startup. So just give it enough time to start up (Wait for atleast a minute).

One of the main reasons for the slow startup is youtube-dl. They have done an experimental lazy-loading-extractor feature (https://github.com/rg3/youtube-dl/pull/8497) which should improve the speed, but I've never tried it with mpsyt. Feel free to try and report back here.

**Comment by Gelixen** [comment]
Getting same error `bash: mpsyt: command not found` on my RPI 3B

**Comment by ritiek** [comment]
I am going to close this as @amodeo12 was able to fix the original issue `-bash: mpsyt: command not found mpsyt`.

Also as @vn-ki mentioned, it indeed takes a while for mps-youtube to launch on low powered devices like Raspberry Pi, etc. So, grab a coffee and wait. If it takes insanely long (like 5 mins+), please open a separate issue instead.
