### ISSUE TITLE
[minor issue] handling of disabled comments.

### ISSUE THREAD

**Issue by pirate486743186** [mps-youtube/mps-youtube#820]
This is a minor issue. Disabled comments could be handled more gracefully. When comments are disabled, it gives:

Error fetching data. Possible network issue.
Youtube Error 403: The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.

**Comment by ritiek** [comment]
> The video identified by the `videoId` parameter has disabled comments.

I thinks its alright the current way it is. We can play the video just fine and this error occurs only when requesting for comments.

**Comment by Razesdark** [comment]
I've added a PR for a small fix. It just removes the random HTML code which is passed from the API
