### ISSUE TITLE
Playback ERROR: "token" parameter not in video

### ISSUE THREAD

**Issue by filalex77** [mps-youtube/mps-youtube#822]
## Issue

As in the title, mpsyt throws this error after trying to run a video (no matter if with video output or not):

    ERROR: qnr2-Z6siHQ: "token" parameter not in video info for unknown reason;
    please report this issue on https://yt-dl.org/bug .
    Make sure you are using the latest version; see  https://yt-dl.org/update on how to update.
    Be sure to call youtube-dl with the --verbose flag and include its complete output.

If I run `mpv` or `youtube-dl` directly on that URL, it works fine. Please let me know if I can supply additional information.

## Your Environment

Distro: Void Linux

`mpsyt --version`:

    mpsyt version      : 0.2.8
    notes              : released 17 February 2018
    pafy version       : 0.5.3.1 (youtube-dl backend)
    youtube-dl version : 2018.04.03
    Python version     : 3.6.5 (default, Mar 29 2018, 16:38:38)
    [GCC 7.3.0]
    Processor          :
    Machine type       : x86_64
    Architecture       : 64bit,
    Platform           : Linux-4.15.12_1-x86_64-with-glibc2.3.4
    sys.stdout.enc     : UTF-8
    default enc        : utf-8
    Config dir         : /home/brightone/.config/mps-youtube
    env:TERM           : st-256color
    env:SHELL          : /bin/zsh
    env:LANG           : en_US.UTF-8

I use `mpv` as my player.

`mpv --version`:

    mpv 0.27.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
     built on Fri Feb 16 12:17:03 UTC 2018
    ffmpeg library versions:
       libavutil       55.78.100
       libavcodec      57.107.100
       libavformat     57.83.100
       libswscale      4.8.100
       libavfilter     6.107.100
       libswresample   2.9.100
    ffmpeg version: 3.4.2

**Comment by ritiek** [comment]
I'd suggest you try again after upgrading `youtube-dl` (new releases since you opened this). Also, this could be helpful https://github.com/rg3/youtube-dl/issues/13045#issuecomment-300716289.

If still no luck, what does this give you:
```
$ youtube-dl -gf best https://www.youtube.com/watch?v=fzQ6gRAEoy0
```
