### ISSUE TITLE
Move command mv not triggering playlist-save

### ISSUE THREAD

**Issue by nikisix** [mps-youtube/mps-youtube#829]
mpv --version
mpv 0.28.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sat Apr 21 19:46:22 BST 2018
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: 4.0

OSX (current)

mpsyt --version
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2018.02.11
Python version     : 3.6.5 (default, Mar 30 2018, 06:41:53)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
Processor          : i386
Machine type       : x86_64
Architecture       : 64bit,
Platform           : Darwin-17.5.0-x86_64-i386-64bit
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /Users/nicktomasino/.config/mps-youtube
env:TERM           : screen-256color
env:SHELL          : /bin/zsh
env:LANG           : en_US.UTF-8

**Comment by tinydynamite00** [comment]
Would you mind sharing the exact command you are issuing and what you expect to happen? 

Note: the <code>mv</code> command allows a playlist to be renamed. 
Ex: run <code>ls</code> to display saved playlists. Run <code>mv 2 new_playlist_name</code>. The playlist is already saved; it simply gets moved into new_playlist_name. 
If you are trying to move the contents of one playlist into another, you can <code>open playlist_number</code>, then use <code>add</code> + the track number(s) + name_of_playlist into which to copy your selections. Delete duplicates, if necessary.

**Comment by ritiek** [comment]
@nikisix You need to manually save your playlist afterwards using `save <playlist_name>`. You want to use the same `<playlist_name>` to override your old playlist.

**Comment by nikisix** [comment]
Ahh! Thanks
