### ISSUE TITLE
Problem playing last item: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>

### ISSUE THREAD

**Issue by bossman762x39** [mps-youtube/mps-youtube#830]
i get the error Problem playing last item: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>
when i do for example / cats to search for cat videos mpsyt opens i get the logo and opening screen and i can do help screen but not do anything else 

mpsyt version      : 0.2.8
i am on macos high sierra 
i am using mpv
i have had a ton of issues prior to this and honestly could be i am new to terminal. 

EDIT***figured it out with messing around some more. had to update certifications in python once updated certications command in python everything is working sorry for the early post should of kept messing with it.

**Comment by bossman762x39** [comment]
figured it out with messing around some more. had to update certifications in python once updated certications command in python everything is working sorry for the early post should of kept messing with it.

**Comment by rpdelaney** [comment]
Please post your solution including the command(s) you ran to fix it. You are not the only person affected by this issue. Thanks.

**Comment by ac130kz** [comment]
This happend to me, but it was due to time synchronization issues.

**Comment by kashopi** [comment]
Here you can find the fix in MacOS: https://stackoverflow.com/questions/40684543/how-to-make-python-use-ca-certificates-from-mac-os-truststore

```
cd /Applications/Python\ 3.6/
./Install\ Certificates.command
```

**Comment by Razesdark** [comment]
OP seems to have resolved the issue himself. Closing this issue
