### ISSUE TITLE
mpsyt in terminal wont work if there is no sudo at install ?

### ISSUE THREAD

**Issue by icf20** [mps-youtube/mps-youtube#832]
installed via ` pip3 install --user mps-youtube  `

in terminal
```
mpsyt 
mpsyt: command not found  
```
how works 
` /home/user/.local/bin/mpsyt    `

opensuse TW

**Comment by ritiek** [comment]
You need to add this location `~/.local/bin/` to your PATH variable. [Here is how you can do it](https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path).

Calling `$ mpsyt` should then work.
