### ISSUE TITLE
[Question] Is it possible to pause or goto prev/next from another terminal?

### ISSUE THREAD

**Issue by nealot** [mps-youtube/mps-youtube#834]
If you have two terminals open, one empty and another playing a song from mpsyt, is it possible to run something like mpsyt --{command] and have it affect the first terminal? Could I send a signal to the process to pause or skip? I'm wondering because I wanted to integrate it with [polybar](https://github.com/jaagr/polybar).

**Comment by ritiek** [comment]
Hi, thank you for introducing me to [polybar](https://github.com/jaagr/polybar)! :)

Yes, mps-youtube supports mpris2 API! There is no proper documentation at the moment to learn how to get this working. So, I'll write whatever I know.

- You'll first need to remove any old libraries and install newer ones.
```bash
$ apt purge python3-gobject python3-dbus
$ apt install libgirepository1.0-dev libcairo2-dev
$ pip3 install PyGObject
$ pip3 install dbus-python
```
- Install [playerctl](https://github.com/acrisci/playerctl#installing) (easy to use, there are many others too) to control mpris supported players.

- Then run your `mpsyt` instance (re-run it if already running) and play this song (my favorite at the moment) in 2nd terminal.
```
$ mpsyt playurl https://youtube.com/watch?v=HQnC1UHBvWA
```

- Run this to list your running dbus instances.
```bash
$ playerctl --list-all
# This should display something like
# mps-youtube.instance24818
```

- Let's pause the current song.
```bash
$ playerctl --player=mps-youtube.instance24818 pause
```

- If the above works you're good to go!
```bash
$ playerctl --help
```

FYI mps-youtube sets the bus name as https://github.com/mps-youtube/mps-youtube/blob/9771d33d390dd6550f82bba16df4871d590071c3/mps_youtube/mpris.py#L36-L38

**Comment by nealot** [comment]
Thank you! This was exactly what I was looking for :)

**Comment by hrnr** [comment]
Thanks @ritiek for a guide. We probably do not advertise MPRIS2 strongly enough.

Library fiddling should not be generally necessary, but of course depends on your system. We use pretty old `dbus-python`. https://dbus.freedesktop.org/doc/dbus-python/tutorial.html

playerctl can also pick any player automatically, so if you are not running more that one player at a time, you can just directly use `playerctl pause` etc. This allows you to write a generic applet to control any player supporting MPRIS2. Most of the desktop environments offer some applet, for polybar there is https://github.com/jaagr/polybar/pull/456 (unfinished).

**Comment by ritiek** [comment]
> Library fiddling should not be generally necessary, but of course depends on your system.

Yep, I personally had to install `libgirepository1.0-dev` and `libcairo2-dev` otherwise I wasn't able to `pip install PyGObject`. Just thought would mention them, since it took me a while to find these correct libraries. Also `pygobject` and `dbus` are installable from apt too, but are probably outdated.

**Comment by Vaishnavikumara** [comment]
Playerctl is unable to pause the video. Please help @ritiek
