### ISSUE TITLE
Update images in README.md 

### ISSUE THREAD

**Issue by Razesdark** [mps-youtube/mps-youtube#845]
When np1 took down his repositories, he also took down a lot of images that we were using to show users the features of the program. We should probably get the old ones back, or replace them with new ones.

As for hosting them on github pages, orphan-branch, docs folder in develop or separate repo? Any thoughts?

**Comment by ids1024** [comment]
Ah, good point; I hadn't thought of/noticed this.

It seems the images are accessible on web.archive.org, so we don't need to create new ones (but could): http://web.archive.org/web/20180517021507/github.com/mps-youtube/mps-youtube

I think it's probably best not to add unnecessary binary files to the main repository, in develop/master. Perhaps add a `gh-pages` branch and host them there?

**Comment by richardofortune** [comment]
Definitely pro- gh-pages approach. It's the first thing I looked for when I noticed the images were no longer displaying.

**Comment by ids1024** [comment]
@Razesdark Care to take a shot at fixing this? I think you should be able to create a new branch for gh-pages, and then PR the new urls for the README.

**Comment by Razesdark** [comment]
@ids1024 I've added a branch called gh-pages that has the images. We might have to set the source in the repository settings, cause i'm currently getting 404s on `http://mps-youtube.github.io/mps-youtube/album-1.png` for example. I'll PR the readme when the images are being served.

**Comment by ids1024** [comment]
I pushed an empty `index.html` file, which seems to have fixed it.
