### ISSUE TITLE
how to get the current playing song using bash script?

### ISSUE THREAD

**Issue by cevhyruz** [mps-youtube/mps-youtube#877]
I want to display currently playing song in tmux status..  is this possible?.. thanks..

**Comment by vn-ki** [comment]
mpsyt implements mpris interface. This means you can control mpsyt using mpris.

So, make sure mpris is enabled in mpsyt, install [playerctl](https://github.com/acrisci/playerctl), and do `playerctl metadata title`. If you have more than one player with mpris, you have to specify the name in `playerctl`

**Comment by cevhyruz** [comment]
I'm not quite sure about enabling mpris in mpsyt.. what do you mean by that? i tried the help but no luck..

**Comment by cevhyruz** [comment]
I finally got it working with ```playerctl metadata tiltle``` maybe i mispelled something or what but anyways thanks for the fast response. cheers! I'll close this issue now
