### ISSUE TITLE
MPRIS process exited of crashed.

### ISSUE THREAD

**Issue by cevhyruz** [mps-youtube/mps-youtube#880]
## Issue
while playing songs, I sometimes hit return ```[CTRl-C] ``` to select another from the menu. but after this mpsyt will return ```MPRIS process exited of crashed.```  the selected song will still play though.. 

it's no harm actually but I have some scripts that use playerctl to query metadata from mps-youtube and I noticed that if the MPRIS crash the playerctl can't detect the MPRIS player anymore unless I restart the mpsyt again.

##  Environment

I'm using ```mplayer``` as the default player.
this command fails if MPRIS crashed. ```playerctl --list-all```
mpsyt version:
```
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2018.01.27
Python version     : 3.6.6 (default, Jun 27 2018, 14:44:17) 
[GCC 8.1.0]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-4.14.0-kali3-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/devs/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : C.UTF-8
```

**Comment by cevhyruz** [comment]
Thanks for that! running from develop branch fixes the issue for me.

**Comment by nealot** [comment]
@ritiek Any ideas when the next release will be? I'm also running some playerctl scripts and this problem continues to disrupt things. I'd rather use the version that my package manager provides instead of running from the develop branch since it's easier to manage.
