### ISSUE TITLE
youtube_dl error: RegexNotFoundError even after update of mps-youtube and youtube-dl

### ISSUE THREAD

**Issue by DJJ88** [mps-youtube/mps-youtube#884]
## Your Environment

Hello 
I recently got the error below when using mps-youtube. The funny thing is that it happen to work sometime and I can play a video. But most of the times, this error pops up.
I installed the latest version of mps-youtube -v0.2.8 using pip3 ins and the error persisted.
I installed the latest version of youtube-dl using pip and the error was not resolved.
I tried to stream a video directly using youtube-dl and it worked fine. 
My video player is mpv
I'm on debian 9. 

Please Let me know if you need more info.
Best regards
                                                                                                                                              [1/12>
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/djj/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1163, in _decrypt_signature
    video_id, player_url, s
  File "/home/djj/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1074, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/djj/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1135, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/home/djj/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 782, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are usin

**Comment by williamd1k0** [comment]
Same issue on Windows 10

**Comment by omega64** [comment]
Same error here! I think youtube change something, and mps-youtube devs should investigate...

**Comment by omarroth** [comment]
Take a look at rg3/youtube-dl#17457 and rg3/youtube-dl#17464 for more information as to what the problem is. Essentially, YouTube recently tweaked their signature function, so other projects have been catching up. There should already be a fix pushed for youtube-dl, so it's strange that it's still being encountered.

**Comment by ilkerkorkut** [comment]
For Mac users ;
`class Mpsyoutube < Formula
  include Language::Python::Virtualenv

  desc "Terminal based YouTube player and downloader"
  homepage "https://github.com/mps-youtube/mps-youtube"
  url "https://github.com/mps-youtube/mps-youtube/archive/v0.2.8.tar.gz"
  sha256 "d5f2c4bc1f57f0566242c4a0a721a5ceaa6d6d407f9d6dd29009a714a0abec74"
  revision 4

  bottle do
    cellar :any_skip_relocation
    sha256 "0ea34a095f7f53773519e9a36a198ddc71eabb60b87537d126d02ff084646055" => :mojave
    sha256 "e8bda076e052abeae08101720c9117c24baa4a5f561e544ef870ba97c76b98e4" => :high_sierra
    sha256 "fec849d308e04483377b412ed2ea2b6061420cbfb266947f57226e607368545f" => :sierra
    sha256 "9761dff9eb00b7d03ae4e45eb2c1285e3f9f7e139bed5f98bce1523bffe4039d" => :el_capitan
  end

  depends_on "python"
  depends_on "mpv" => :recommended
  depends_on "mplayer" => :optional

  resource "pafy" do
    url "https://files.pythonhosted.org/packages/41/cb/ec840c79942fb0788982963b61a361ecd10e4e58ad3dcaef4f0e809ce2fe/pafy-0.5.4.tar.gz"
    sha256 "e842dc589a339a870b5869cc3802f2e95824edf347f65128223cd5ebdff21024"
  end

  resource "youtube_dl" do
    url "https://files.pythonhosted.org/packages/70/0a/183d24d2cf3bbb9b9874ed4dfb3e3bf732775ad0bbc89ba819bdc613ee9c/youtube_dl-2018.9.10.tar.gz"
    sha256 "f3be4598bb5029299d46533d3a7bd94b3ff5e391ee2bd8dbbf70288c67cbc8a6"
  end

  def install
    venv = virtualenv_create(libexec, "python3")

    ["youtube_dl", "pafy"].each do |r|
      venv.pip_install resource(r)
    end

    venv.pip_install_and_link buildpath
  end

  test do
    Open3.popen3("#{bin}/mpsyt", "/september,", "da 1,", "q") do |_, _, stderr|
      assert_empty stderr.read, "Some warnings were raised"
    end
  end
end
`
Save that file and `brew install --build-from-source MpsYoutube.rb`
I updated the resource "youtube_dl" with new version under https://pypi.org/project/youtube_dl/ according to that error.

**Comment by DJJ88** [comment]
I think the issue is solved. Many thanks for your comments. I'm closing the issue
