### ISSUE TITLE
ubuntu apt install vs pip3 and moved playlists

### ISSUE THREAD

**Issue by icf20** [mps-youtube/mps-youtube#908]
so if  on PC1 mpsyt is install via pip3 the playlist is on` /home/user/.config/mps-youtube/playlists/` if this folder is moved to another PC2 but here mpsyt is installed via apt the playlist is not recognized, installing on PC2 via pip3 solves the problem

**Comment by kraetzin** [comment]
I'm assuming that this was resolved? If the playlist folder was not recognised then the it may have been an older version of mps-youtube, which stored playlists differently.

**Comment by icf20** [comment]
i just wanted to put this here in case anyone ask for something like that
