### ISSUE TITLE
MPSYT and Set Player

### ISSUE THREAD

**Issue by MartinPPG** [mps-youtube/mps-youtube#933]
Hello, I am trying to use MPS-Youtube, because just this app for me showing, that it can play Youtube just in terminal.

I successfully installed MPSYT trought Python3.6 Portable but I didn't found how to setup Player for it.
I do everything without problem, MPSYT working fine, but cannot play anything. I installed all needed applications for it: FFmpeg, MPV, MPlayer. After these tries I didn't found online solution.

I have Windows 10 Home Insider Preview (Version: 1809, Build: 18252.1000)
MPS-Youtube [Version](https://ctrlv.sk/2Lud)
MPV [Version](https://ctrlv.sk/CP7Z)
MPlayer [Version](https://ctrlv.sk/OaPd)
FFmpeg [Version](https://ctrlv.sk/C8JD)

I Hope someone try to help, Thanks!

**Comment by kekePower** [comment]
Hi.

Launch mps-youtube and type "set player <YourOption>".

**Comment by Sasmitadn** [comment]
If you install mpv use "pip3 install mpv". You can try "pkg install mpv".

launch mpsyt and write "set player mpv"

I hope this work for you. Enjoy

**Comment by ritiek** [comment]
I'll be closing this since the above solutions should solve this.
