### ISSUE TITLE
signature extraction failed

### ISSUE THREAD

**Issue by githubgnulinux** [mps-youtube/mps-youtube#938]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1162, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1073, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1134, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 782, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m;

**Comment by ritiek** [comment]
Update youtube-dl:
```
$ pip3 install youtube-dl -U
```

**Comment by soanvig** [comment]
I'm extremely excited about `mps-youtube`, but I cannot use, even though I have as fresh `youtube-dl` as possible.

Got the same error on most of the movies, while they can still be downloaded through `youtube-dl`.

I have `youtube-dl` installed manually via `curl`, and mps-youtube installed via system repository.  Could it be cause, that - somehow - `mps-youtube` is using old version of `youtube-dl`?
