### ISSUE TITLE
Can't change API key on mps-youtube.

### ISSUE THREAD

**Issue by CocoCocoAlx** [mps-youtube/mps-youtube#950]
Hello. Apparently, I've exceeded my Youtube quota. I have created a new API key and when I want to add it to the program, it tells me that it is not a valid key or that it is exceeded. How do I change the API key? Thank you, everyone.

Running
mpsyt version      : 0.2.8
notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.01.24
Architecture       : 32bit, ELF
Platform           : Linux-4.18.0-3-686-i686-with-Sparky-5-Nibiru

OS: SparkyLinux 5 LXQt
Media player used: mpv 0.29.1

**Comment by neoromantique** [comment]
Same issue.

**Comment by CocoCocoAlx** [comment]
I've solved that cleaning mps-youtube config directory and re-added API from the application. Thanks.
