### ISSUE TITLE
[urgent] Problem playing last item: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Migacz85** [mps-youtube/mps-youtube#953]
AFter giving the number of video to play and pressing the enter key this error message is present. Not with all videos but with some. When trying to quit and restart mpsyt problrem persist. Maybe after longer time it will play the movie but not sure.

mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.02.18
Python version     : 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, 
Platform           : Linux-4.14.101-1-MANJARO-x86_64-with-arch-Manjaro-Linux
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/migacz/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_GB.UTF-8

**Comment by Bloodclaw** [comment]
I Have the same problem

**Comment by Migacz85** [comment]
For those who can't live without mpsyt and when bug persist
Quick workaround:
 
1. Write x and number of video you want to play
2. In new konsole or place when you can run command write:
mpv
3. Press ctrl+v (or other shourtcat you have for pasting from clipboard)
4. Enter

**Comment by Vrihub** [comment]
> Quick workaround:
... or use youtube-dl (which is what mpv does in the background)

**Comment by pirate486743186** [comment]
It still doing that? I haven't seen this error for a while now. Youtube also increased the resolution of normal videos recently, so it's possible, that it was a youtibe bug.

**Comment by Migacz85** [comment]
How it could be a youtube bug if the link was opening correctly in other program ?

**Comment by Vrihub** [comment]
I can confirm that the problem seems to have disappeared. I can see all the videos correctly now.

**Comment by Migacz85** [comment]
same here - super strange. What was that ?

**Comment by StylinGreymon** [comment]
videos seem to be loading for me again, but no longer display titles and aren't in 1080p anymore.

**Comment by pirate486743186** [comment]
mps can only deal with videos in one piece(video/audio). 1080p are now separate video and audio streams. This is why you can't see them. (also the minimum is raised to 360)

Titles seam normal to me. (i'm on Linux)

@Migacz85
Like i said, probably a small youtube side bug that they fixed.

**Comment by pirate486743186** [comment]
@Migacz85 
You can close issues you started your self.
