### ISSUE TITLE
Keyboard shortcuts don't work as expected.

### ISSUE THREAD

**Issue by GokhanPolat** [mps-youtube/mps-youtube#956]
After using Mps-youtube for a few months without problems, some keyboard shortcuts don't work as expected now.

'q', '<'  act as shortcuts to the next item '>' in the playlist window.

**I have try some differences for investigating errors.**
- Changing the terminal app (iTerm/Mac OS terminal)
- Changing the shell (bash/zsh)
- Changing the login user on my mac
- Trying with python/homebrew 
- Trying development version 
`pip3 install --user -U git+https://github.com/mps-youtube/mps-youtube.git`
- Changing player mpv/mplayer 

## Your Environment

mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.03.01
Python version     : 3.7.2 (default, Feb 12 2019, 08:16:38)
[Clang 10.0.0 (clang-1000.11.45.5)]
Processor          : i386
Machine type       : x86_64
Architecture       : 64bit,
Platform           : Darwin-17.7.0-x86_64-i386-64bit
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /Users/dev/.config/mps-youtube
env:TERM           : screen-256color
env:SHELL          : /bin/zsh
env:LANG           : en_US.UTF-8

OS: MacOS Hight Sierra 10.13.6
Term: iTerm2

**Comment by pirate486743186** [comment]
they work fine for me (on linux)
Try deleting the config files.
on linux they are at ".config/mps-youtube"

**Comment by GokhanPolat** [comment]
thanks @pirate486743186,
I tried this approach and nothing had changed.

**Comment by pirate486743186** [comment]
upgrade to latest mac os/python?

**Comment by GokhanPolat** [comment]
Yes, the python is up to date.
I still haven't figured out why I'm having this problem.

```
mpsyt -v
mpsyt version         : 0.2.8
   notes              : released 17 February 2018
pafy version          : 0.5.4 (youtube-dl backend)
youtube-dl version    : 2019.03.09
Python version        : 3.7.3 (default, Mar 27 2019, 09:23:39)
...
```

**Comment by GokhanPolat** [comment]
i think this is mpv issue. 
There are some problems with the 'shift +' shortcuts of mpv (uppercase letters or alternative keys).

**Comment by pirate486743186** [comment]
.... test with mplayer instead?

**Comment by GokhanPolat** [comment]
I tried it, nothing changed.
