### ISSUE TITLE
not playing videos

### ISSUE THREAD

**Issue by Rheyd** [mps-youtube/mps-youtube#976]
ERROR: 4TB10gonKlU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output

i got this error at first then i uninstall and reinstall youtube-dl

the error went away, but when i tried to select a song this appeared

pAgnJDJN4VA; webm 160k; 3 Mb   

nothing more, and nothing was playedf

**Comment by Rheyd** [comment]
side note, youtube-dl works just fine, i tried with videos and it worked fine, i'll try to get a fresh start for the mps

**Comment by kkkrist** [comment]
> side note, youtube-dl works just fine, i tried with videos and it worked fine, i'll try to get a fresh start for the mps

I'm seeing this too, but in fact the youtube-dl version I was using (2019.04.17) wouldn't work all the same. So I upgraded youtube-dl to 2019.04.24, reinstalled/rebuilt mps-youtube and now everything works fine again.

before:

```
❯ mpsyt --debug
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.04.01
Python version     : 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)]
Processor          : i386
Machine type       : x86_64
Architecture       : 64bit,
Platform           : Darwin-18.5.0-x86_64-i386-64bit
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /Users/krist/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/zsh
env:LANG           : de_DE.UTF-8
could not load MPRIS interface. missing libraries.
```

after:

```
❯ mpsyt --debug
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.04.24
Python version     : 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)]
Processor          : i386
Machine type       : x86_64
Architecture       : 64bit,
Platform           : Darwin-18.5.0-x86_64-i386-64bit
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /Users/krist/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/zsh
env:LANG           : de_DE.UTF-8
could not load MPRIS interface. missing libraries.
```

**Comment by Rheyd** [comment]
i tried to update the version of the youtube-dl and it still didn't worked, instead i downgraded the mps-youtube version, i don't know up to which version it still works, but it works fine for me this version.

mps-youtube-94e9cb41a365ca3d477370c179eaebfb9283a9e3

i should have mentioned that i'm using it in a raspberry pi 3b+
maybe it was relevant, maybe in the future i'll make further test to see which version is supported in the raspbian OS
