### ISSUE TITLE
Youtube Error 403: Access Not Configured When I change API Key

### ISSUE THREAD

**Issue by GMahir** [mps-youtube/mps-youtube#978]
When I change default API key with my own, I get this error:

> Youtube Error 403: Access Not Configured. YouTube Data API has not been used in project 1031674311074 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=1031674311074 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

My API key is enabled for that project. I've done this before with mps-youtube, maybe a year ago, and had no problems with it. 
I even tried generating a new key yesterday, applied that and still getting the same error. It feels like I misconfigured something in my Google API Project but I don't know what it could be.

Here is "mpsyt --version" :

> mpsyt version      : 0.2.8
>    notes           : released 17 February 2018
> pafy version       : 0.5.4 (youtube-dl backend)
> youtube-dl version : 2019.05.11
> Python version     : 3.6.7 (default, Oct 22 2018, 11:32:17) 
> [GCC 8.2.0]
> Processor          : x86_64
> Machine type       : x86_64
> Architecture       : 64bit, ELF
> Platform           : Linux-4.15.0-48-generic-x86_64-with-LinuxMint-19-tara
> sys.stdout.enc     : UTF-8
> default enc        : utf-8
> Config dir         : /home/gexzir/.config/mps-youtube
> env:TERM           : xterm-256color
> env:SHELL          : /bin/bash
> env:LANG           : en_US.UTF-8
> env:LANGUAGE       : en_US

**Comment by ikuraj** [comment]
same issue here... any solutions?

**Comment by isakrubin** [comment]
same... after a while it shows "http not supported", like it's trying to access youtube over http instead of https

**Comment by kkkrist** [comment]
Same problem here. Additionally I got an email from YouTube a few days ago stating access to the YouTube Data API Service has been disabled for the key's project due to 90 days of inactivity. That's just not true, and the traffic stats on the dev console dashboard clearly shows it. What's going on here?!

**Comment by vnckppl** [comment]
Same issue here. Also, with the default api key I keep getting this error for every item: 

> Problem playing last item: HTTP Error 403: Forbidden

**Comment by ritiek** [comment]
Could you guys try again creating a new project. Make sure you "Enable APIs and Services" from your project's dashboard and choose "YouTube Data API" when it asks what is to be enabled. Then go about creating a new "API Key" from your credentials page. Then copy and set this key in mpsyt with:
```
> set api_key AIzaSyC.......
```

I just created a key for myself and this seems to be working for me.

**Comment by kkkrist** [comment]
I just took another Google Account and set up a new project with a new api key. Then deleted my `~/.config/mps-youtube` folder, started mpsyt, set the api_key config. Still some videos play flawlessly, some don't – now with a very different, probably not related error:

https://gist.github.com/kkkrist/2d1824037deff93e9a030af37f169069

Maybe we need to bump youtube-dl? All videos that wouldn't play with mpsyt 0.2.8 (youtube-dl 2019.04.24) did play fine with youtube-dl standalone 2019.06.08 – including those who 403ed out previously.

I'm on macOS with Homebrew btw.

Thanks for your help, much appreciated!

**Comment by ritiek** [comment]
@kkkrist Yep, as you guessed the problem is with mps-youtube using outdated youtube-dl version. Also, I think it's best to install mps-youtube from source for now as there hasn't been a new mps-youtube release since an year. I don't have any experience with homebrew but you may have luck removing homebrew mps-youtube and youtube-dl packages and then install them using pip with:
```
$ pip3 install -U git+https://github.com/mps-youtube/mps-youtube
$ pip3 install -U youtube-dl
```

With this you should most likely have mps-youtube using the latest youtube-dl release.

**Comment by kkkrist** [comment]
I see. youtube-dl is fine via homebrew, it's at 2019.06.21 now btw. Hmm… I'd much prefer using a package manager to limit manual updating and Python easily getting messed up on macOS when mixing up built-in modules, pip, homebrew, Python 2.7 vs. 3+ etc. On the other hand, this is such great and useful software that I still might risk doing it ;-)

Probably way off topic here, but why has there been no release for a while? Any showstoppers? At this point current master might probably be more stable than 0.2.8 due to YouTube API changes alone I guess?

**Comment by ritiek** [comment]
> Probably way off topic here, but why has there been no release for a while? Any showstoppers?

AFAIK only @ids1024 has control over releases and he isn't actively maintaining the project any more, so I have no say when the next release is planned.

> At this point current master might probably be more stable than 0.2.8 due to YouTube API changes alone I guess?

For most YouTube related stuff mps-youtube just uses youtube-dl, so everything should probably work fine if youtube-dl is up to date even when installing mps-youtube v0.2.8 from the PyPI release, but there are [other bug fixes and features](https://github.com/mps-youtube/mps-youtube/compare/v0.2.8...develop) that have been added those haven't yet made it into a release yet.

**Comment by kkkrist** [comment]
Bummer. Thanks for clarification and keeping the project up! I hope @ids1024 will consider cutting a new release or making one of you guys a maintainer in the future. This project is quite a success and he can be proud of it ;-)

**Comment by GMahir** [comment]
I guess I'm going to close it. My SSD failed and now I'm running Arch Linux on USB memory. So I had to make a fresh install of mpsyt. I also created a new project and used new api key and voilà! everything works as it should. Here is my new mpsyt --version, it might help anyone else who has this problem:

> 
> mpsyt version      : 0.2.8
>    notes           : released 17 February 2018
> pafy version       : 0.5.4 (youtube-dl backend)
> youtube-dl version : 2019.06.21
> Python version     : 3.7.3 (default, Jun 24 2019, 04:54:02) 
> [GCC 9.1.0]
> Processor          : 
> Machine type       : x86_64
> Architecture       : 64bit, ELF
> Platform           : Linux-5.1.15-arch1-1-ARCH-x86_64-with-arch
> sys.stdout.enc     : UTF-8
> default enc        : utf-8
> Config dir         : /home/gexzir/.config/mps-youtube
> env:TERM           : xterm-256color
> env:SHELL          : /bin/bash
> env:LANG           : en_US.UTF-8
> env:LANGUAGE       : en_US
> 
As you can see, apart from Python and GCC, I have a newer version of youtube-dl (from 2019.05.11 to 2019.06.21). Next time I have any problem with this, I'll check for updates.
