### ISSUE TITLE
YouTube playback HTTP is not supported

### ISSUE THREAD

**Issue by jcousins-ynap** [mps-youtube/mps-youtube#986]
Search for `chilledcow` (been my favourite for 4/5 years now)
```sh
/chilledcow
```

Play the first link (the live stream)
```sh
1
```

Experience sad error stating
```sh
Problem playing last item: lofi hip hop radio - beats to relax/study to ERROR: hHW1oY26kxQ: Youtube says: HTTP is not supported.
```

Using mpsyt version
```sh
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.04.24
Python version     : 3.7.3 (default, Apr 25 2019, 16:34:30)
[Clang 10.0.1 (clang-1001.0.46.4)]
Processor          : i386
Machine type       : x86_64
Architecture       : 64bit,
Platform           : Darwin-18.6.0-x86_64-i386-64bit
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /Users/j.cousins/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/zsh
env:LANG           : en_GB.UTF-8
```

mpv config (empty file)

---

Any idea why this might be occurring? In desperation, I have added my API to the mpsyt config.
Homebrew is up-to-date, as is youtube-dl and mpsyt as of writing.

**Comment by evolutionxbox** [comment]
Sorry. I should have posted this issue from my personal account.

This seems to only be an issue for streaming. The following URLs can demonstrate the issue 
* https://youtu.be/hHW1oY26kxQ
* https://youtu.be/SmbdY5FpRwA
* https://youtu.be/j3tJF_Z_RdI

**Comment by evolutionxbox** [comment]
Follow up: a local VLAN disabled http access by accident.
Please consider this issue closed.

**Comment by evolutionxbox** [comment]
Is there any way to force HTTPS?

**Comment by kraetzin** [comment]
I belive this is could be a change from Youtube causing problems somewhere. I just recently started having the issue also but it's inconsistent. For example all of your URLs work fine for me currently. As far as I can tell all urls should be requested as https anyway so I'm not certain where the error is. I'll keep a look out to see if I can narrow things down a bit.

**Comment by ritiek** [comment]
I think mps-youtube/pafy#235 should fix this.

>  I just recently started having the issue also but it's inconsistent. For example all of your URLs work fine for me currently.

Yep, that's what also seems like to me. Those URLs work fine for me as well.

Also see mps-youtube/pafy#234

**Comment by drasbeck** [comment]
Definitely seems like the solution to the problem. Any idea when this will this make it to release?

I've leisurely running a homebrew install of mps-youtube and would like to keep it so. =)

**Comment by oliverseal** [comment]
here's more or less how I solved this until it gets released:
```sh
mkdir -p ~/src/pafy
git clone git@github.com:mps-youtube/pafy.git ~/src/pafy
cd ~/src/pafy
MPSYT=`which mpsyt`
MPSYT_PYTHON=`head -1 $MPSYT | cut -d'!' -f 2`
$MPSYT_PYTHON -m pip install .
```

This will essentially install the latest pafy into the same python env that mpsyt is using.

**Comment by Jeronimo17** [comment]
```
youtube-dl mLeQ3HC9xqw
[youtube] mLeQ3HC9xqw: Downloading webpage
[youtube] mLeQ3HC9xqw: Downloading video info webpage
ERROR: This video contains content from WMG, who has blocked it in your country on copyright grounds.
```
Mpsyst -> **HTTP is not supported**

**Comment by Jeronimo17** [comment]
So when loading a url list, it stops when this happens

**Comment by drasbeck** [comment]
> here's more or less how I solved this until it gets released:
> 
> ```shell
> mkdir -p ~/src/pafy
> git clone git@github.com:mps-youtube/pafy.git ~/src/pafy
> cd ~/src/pafy
> MPSYT=`which mpsyt`
> MPSYT_PYTHON=`head -1 $MPSYT | cut -d'!' -f 2`
> $MPSYT_PYTHON -m pip install .
> ```
> 
> This will essentially install the latest pafy into the same python env that mpsyt is using.

@oliverseal awesome, is your mpsyt also installed via homebrew? Also, before I venture forth, what are the steps to revert this? I'm rusty at best in python envs and I would like to be able to just run `brew upgrade` whenever this thing is ready.

**Comment by Jeronimo17** [comment]
> So when loading a url list, it stops when this happens

mps-youtube-develop/mps_youtube/commands/search.py

```
@command(r'url\s(.*[-_a-zA-Z0-9]{11}.*)', 'url')
def yt_url(url, print_title=0):
    """ Acess videos by urls. """
    url_list = url.split()

    g.model.songs = []

    for u in url_list:
        try:
            p = util.get_pafy(u)



            g.browse_mode = "normal"
            v = Video(p.videoid, p.title, p.length)
            g.model.songs.append(v)
        except (IOError, ValueError) as e:
            g.message = c.r + str(e) + c.w
            g.content = g.content or content.generate_songlist_display(
                    zeromsg=g.message)
```

**Comment by ritiek** [comment]
For anyone still facing this problem, upgrade your pafy to v0.5.5 or greater with:
```
$ pip3 install pafy -U
```
and should now be fixed.

**Comment by dnhuan** [comment]
My mpsyt sometimes fail to run properly (this happens in 2-3 months). I solved most of the cases just by upgrading the package and dependencies to the latest version.
#1044

**Comment by madjuran** [comment]
pip3 install --upgrade mps-youtube
but mps-youtube already was up to date, so I update youtube-dl (very first dependency)
pip3 install --upgrade youtube-dl

**Comment by rocketinventor** [comment]
Hi, I am using the latest distributable on Windows 10 (`mpsyt-0.2.8.exe`). I am using my own API Key and search works okay. However, any time that I try to search or download anything I get this error:

`Problem playing last item: ERROR: [ID]: Youtube says: HTTP is not supported.`

I have tried all of the following:
```
pip3 install --upgrade mps-youtube
pip3 install pafy -U
pip3 install --upgrade youtube-dl```

Is this fixed in the current branch (non-built)? What is the resolution?

Thanks!
