### ISSUE TITLE
Crash when exceeding the quota

### ISSUE THREAD

**Issue by orbea** [mps-youtube/mps-youtube#997]
mps-youtube will crash when the quota has been exceeded which sometimes happens.

## Issue / Suggestion
```
$ mpsyt /test
Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/pafy/util.py", line 34, in call_gdata
    data = g.opener.open(url).read().decode('utf-8')
  File "/usr/lib64/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 11, in <module>
    load_entry_point('mps-youtube==0.2.8', 'console_scripts', 'mpsyt')()
  File "/usr/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python3.7/site-packages/mps_youtube/__init__.py", line 8, in <module>
    init.init()
  File "/usr/lib64/python3.7/site-packages/mps_youtube/init.py", line 59, in init
    cache.load()
  File "/usr/lib64/python3.7/site-packages/mps_youtube/cache.py", line 34, in load
    pafy.load_cache(cached['pafy'])
  File "/usr/lib64/python3.7/site-packages/pafy/pafy.py", line 184, in load_cache
    set_categories(newcache.get('categories', {}))
  File "/usr/lib64/python3.7/site-packages/pafy/pafy.py", line 171, in set_categories
    catinfo = call_gdata('videoCategories', query)
  File "/usr/lib64/python3.7/site-packages/pafy/util.py", line 42, in call_gdata
    raise GdataError(errmsg)
pafy.util.GdataError: Youtube Error 403: The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.
```

## Your Environment

I am running `Slackware64-current`.
```
$ mpsyt --version
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.07.12
Python version     : 3.7.3 (default, Apr  3 2019, 21:34:18) 
[GCC 8.3.0]
Processor          : AMD FX(tm)-6350 Six-Core Processor
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.1.16-x86_64-AMD_FX-tm-6350_Six-Core_Processor-with-slackware-14.2
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/orbea/.config/mps-youtube
env:TERM           : rxvt-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.utf8
```

**Comment by nickpufferfish** [comment]
A possible fix could be to implement an option of using personal Youtube API keys?

**Comment by ids1024** [comment]
> A possible fix could be to implement an option of using personal Youtube API keys?

There already is.

`set api_key <key>`

**Comment by orbea** [comment]
> A possible fix could be to implement an option of using personal Youtube API keys?

I am not reporting that I am running into the quota, but that mps-youtube is crashing when it reaches the limit. This used to fail gracefully, I would guess something in youtube or youtube-dl changed.

**Comment by pucerpocok** [comment]
Hi,
Yes, there is an option to set the api_key, and for example I set it earlier.
However it seems when mpsyt is started the default key is used, which results in the crash with this error message (please notice the project ID at the end):
`Youtube Error 403: Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=422897895433`
While in the `.config/mps-youtube/config` file I see my own api_key.

**Comment by itanoss** [comment]
When I am trying to change api key with my own one:
```
> set api_key <my_api_key>
Invalid key or quota exceeded, <my_api_key>
```
The `my_api_key` was copied from google console.

**Comment by orbea** [comment]
I am not sure what happened, but I am no longer getting a crash and have not changed anything regarding youtube-dl or mps-youtube.

```
Error fetching data. Possible network issue.
Youtube Error 403: The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.
```

**Comment by benburkhart1** [comment]
I can confirm this is occurring even with a custom API key set.

The offending code is here:

https://github.com/mps-youtube/pafy/blob/develop/pafy/util.py#L30

It's reading from g and is not something you can override:

https://github.com/mps-youtube/pafy/blob/develop/pafy/g.py#L24

**Comment by overnxt** [comment]
I update it on: /home/{your user}/.local/lib/python3.7/site-packages/pafy/g.py on line "api_key = ", adding my api key and now is working.

**Comment by itanoss** [comment]
In my case, my own api key was created 3 years ago. With that key, mps always show exceeding quota message, but no api usage recorded on api console.

After recreating both project and api key on the console, everything works fine.

**Comment by trongthanh** [comment]
I just fixed this using @adamnovak guide above. Just list `~/.config/mps-youtube/` and remove whatever `cache_py_*` file there.

I guess when I started mpsyt the first time, I didn't use my own API key, so the default one is cached and used when the app is bootstrapped.

**Comment by egrieco** [comment]
I was getting the same error when running any command except `mpsyt --help`. Even `mpsyt set` was failing.

As @adamnovak and @trongthanh have suggested, I ran the following command:

`rm -v ~/.config/mps-youtube/cache_py_*`

Now I can run mpsyt and set my own api key.

**Comment by LaurentDumont** [comment]
I just ran into this but using `set` allowed me to use my own API key (after generating one). I'm not too sure why the project is bootstraped with a generic key that isn't generated by the user. I'd rather have that step be part of the installation process than random 403 when the quota is reached.

MPS didn't crash but it did error out with a warning.

**Comment by orbea** [comment]
mpsyt is essentially dead now so w/e...

**Comment by kurokirasama** [comment]
is there an alternative?_?

**Comment by Alux-Alpha** [comment]
For me, I deleted `~/.config/mps-youtube` the cache.py file. It tarted working fine
